### ISSUE TITLE
Whole body 3d keypoints

### ISSUE THREAD

**Issue by lisa676** [zju3dv/EasyMocap#1]
Thanks for this pre-release of wonderful work. We are eagerly waiting for whole body keypoints and SMPL support. Is there any expected date for next commit?

**Comment by chingswy** [comment]
We will release this part as soon as possible.

**Comment by chingswy** [comment]
We have released it. You can have a try!

**Comment by lisa676** [comment]
@chingswy  Thanks for informing me. 

I have some questions. 

1: When I run `demo_mv1pmf_smpl`, getting keypoint error `smooth_body`. I check the code and I found that there is problem on [this line](https://github.com/zju3dv/EasyMocap/blob/ba6e58d56e0ab2b7c492476fe2dcc8fa80dfd865/code/pyfitting/optimize_simple.py#L337) because you defined `loss_dict` dictionary [here](https://github.com/zju3dv/EasyMocap/blob/ba6e58d56e0ab2b7c492476fe2dcc8fa80dfd865/code/pyfitting/optimize_simple.py#L329) but there is no keypoints with the name of `smooth_body`. There are two keypoints `k3d` and `reg_poses_zero` instead of `smooth_body`. If I use `reg_poses_zero` then I am getting right output of SMPL. So is it bug or I am going in wrong way? 

2: Second question is that, it can produce 3D keypoints but what about 3D visualization? Same as [this visualization](https://github.com/zju3dv/EasyMocap/blob/master/doc/feng/skel.gif). Would you like to release this nice visualization code? This is nice visualization of 3D keypoints.

**Comment by chingswy** [comment]
The bug is fixed and the visualization code is released.

**Comment by lisa676** [comment]
@chingswy  Thanks for the update. 

Still I have some more questions.

1: Would you like to tell me that which toolbox you used for Camera calibration? It will be more easy for members to use same strategy.

2: As this work is multiview so how we can read about this multiview algorithm? Which algorithm you implemented in this work or if you have developed your own algorithm then from where I can read more about it. 

Thanks for your support.

**Comment by chingswy** [comment]
1. We use [OpenCV Calibration](https://docs.opencv.org/master/dc/dbb/tutorial_py_calibration.html)
2. I just implented [triangulation](https://en.wikipedia.org/wiki/Triangulation_(computer_vision)) in this work

**Comment by lisa676** [comment]
So what if we want to test this work with any open source video (e.g YouTube)? How to handle the camera parameters in this situation?

Other thing I checked that this work can get multiview and output as multiview or output a only single view from single input. I mean we can not get output like MVPose (mutiview input but single output by fusion) as you mentioned in your work that in future it will be added here. It will be another great commit.

**Comment by chingswy** [comment]
We have not supported the monocular video input at present. More features will be added in the future.
