### ISSUE TITLE
repro and detec results are good but repro_smpl doesn't show anything

### ISSUE THREAD

**Issue by leilaUEA** [zju3dv/EasyMocap#100]
Hi, I have tested the single person demo file (mv1p.py) on some videos from the MADS dataset (created by city university of HongKong), It has 3 camera videos, They have used this calibration toolbox: http://www.vision.caltech.edu/bouguetj/calib_doc/index.html (The C implementation of this toolbox is included in OpenCV)

I edited the calibration .yml files manually using linux gedit text editor, videos dimensions are 512 × 384. Unfortunately I could not get the SMPL output, I used this command:

PYOPENGL_PLATFORM=osmesa python ./apps/demo/mv1p.py ./data --out ./data/output/smpl --vis_det --vis_repro --undis --sub_vis 1 2 3 --vis_smpl

The input videos and calibration files: https://file.io/k0KKuOqvWapY
Here are some results:

**Detections:**
![000000](https://user-images.githubusercontent.com/43270413/140987241-9d0b44f8-379a-4a89-94a2-dd2e679c4b3e.jpg)
**Re-Projections:**
![000000](https://user-images.githubusercontent.com/43270413/140987314-4e7790b7-bfd1-4880-9312-c4c660286ab8.jpg)
**SMPL output:**
![000000](https://user-images.githubusercontent.com/43270413/140987399-fcdeb865-8023-4330-aa36-37ae5dee50ba.jpg)
**SMPL reprojections:**
![000000](https://user-images.githubusercontent.com/43270413/140987444-f0f77f2c-3b21-4406-a157-5c302192c189.jpg)
**SMPL .JSON file:**
![Untitled](https://user-images.githubusercontent.com/43270413/140993164-65bb6c69-d92c-47b8-acaf-30697dad861e.png)

I would appreciate if you could guide me how I can solve the problem with the SMPL output.
Thanks very much in advance.

**Comment by leilaUEA** [comment]
Thanks very much for your response,now the output SMPL can be seen! I scaled the translation matrix similar to the CMU panoptic (pre_panoptic.py)
![000000](https://user-images.githubusercontent.com/43270413/141024899-fb430e84-ea5c-4a57-be8a-b2632f16cdc0.jpg)

SMPL reprojection still is in the corner (sometimes comes to the center with few joints in the form of a small bbox), considering this, can I use the output SMPL file as a confirmed output or more scaling/modification should be done?
![000000](https://user-images.githubusercontent.com/43270413/141025762-43386645-0ac6-43b2-a1f0-4ae95776d942.jpg)

**Comment by chingswy** [comment]
It seems that the fitting result is correct while there may be some errors in `smpl_repro`.

**Comment by leilaUEA** [comment]
Thanks very much for your help, so I will close this issue as the problem is solved
