### ISSUE TITLE
Problems on 3D keypoints by using mvmp on other datasets

### ISSUE THREAD

**Issue by Xianjin111** [zju3dv/EasyMocap#106]
Thank you for your work. I have problems when running the mvmp.py on our datasets, the results of vis_det is correct, but the result of vis_repro is not correct (only one person can be reprojected).
![2D](https://user-images.githubusercontent.com/46471572/142991439-bc4e3e58-ec6b-4656-a8c9-b35f56378d02.jpeg)
![3D](https://user-images.githubusercontent.com/46471572/142991443-806f2bc6-cc3e-400e-8073-d2015ed4c5a9.jpeg)

Could you please help me deal with this problem? thx

**Comment by chingswy** [comment]
Maybe you have wrong with your calibration results. We assume that the ground plane should be `z=0` and the metric should be `meter`. You can check your calibration like [this](https://github.com/zju3dv/EasyMocap/blob/master/apps/calibration/Readme.md).

**Comment by Xianjin111** [comment]
> 

Thx. I will try the suggestion.

**Comment by visonpon** [comment]
Hi, @Xianjin111 I also encountered this problem, did you find  solution?
