### ISSUE TITLE
question about smpl issue (smpl twisted in some frames)

### ISSUE THREAD

**Issue by leilaUEA** [zju3dv/EasyMocap#109]
I have used a 3 camera dataset as an input, the smpl model in most of the frames are fine, in some frames it get twisted, does it happen because of openpose problem and occolusion?I wonder if we have two camera on each side (i.e. 5 cameras instead of 3) that would solve the issue?

here is smpl reprojection of continuous frames, the left arm openpose key points are miscalculated in the second camera for few frames

![000438](https://user-images.githubusercontent.com/43270413/145593358-49e0f21e-2e3a-42ad-a5ee-ed1b64794bfd.jpg)
![000439](https://user-images.githubusercontent.com/43270413/145593365-ace2fce5-e521-4786-8a8c-49486c8b0a27.jpg)
![000440](https://user-images.githubusercontent.com/43270413/145593373-374e685c-3380-4848-b836-57940444d47c.jpg)
![000441](https://user-images.githubusercontent.com/43270413/145593384-64734bde-bd63-4bbd-b7f4-e5bbd47b9c7f.jpg)
![000442](https://user-images.githubusercontent.com/43270413/145593391-ff61ef41-8aef-4759-a676-d931373e2bab.jpg)
![000443](https://user-images.githubusercontent.com/43270413/145593405-274cb524-948d-49ad-8bcd-bab0fc77fc69.jpg)
![000444](https://user-images.githubusercontent.com/43270413/145593415-b4d9f496-1146-41d8-ae8e-dfa3198f4334.jpg)
![000445](https://user-images.githubusercontent.com/43270413/145593430-18fd4667-22be-4519-8544-bf5e1844972b.jpg)
![000446](https://user-images.githubusercontent.com/43270413/145593441-6a8fb773-dec3-4ee0-b050-fe4f53005138.jpg)
![000447](https://user-images.githubusercontent.com/43270413/145593456-036ab98b-0bf1-466e-b62c-a7ade7ce9fdd.jpg)
![000448](https://user-images.githubusercontent.com/43270413/145593465-b2ec17ea-d430-46f9-981c-98fd43d8de98.jpg)

![000438](https://user-images.githubusercontent.com/43270413/145591383-479ac0b9-e546-4d6a-a3a8-f53827e23729.jpg)
![000439](https://user-images.githubusercontent.com/43270413/145591394-83f1ec05-36f6-4736-bea3-ceac41888bab.jpg)
![000440](https://user-images.githubusercontent.com/43270413/145591404-787e95b1-9b4c-443c-8791-a779211b6874.jpg)
![000441](https://user-images.githubusercontent.com/43270413/145591411-30c6e0b8-3051-4746-847c-0657df037b26.jpg)
![000442](https://user-images.githubusercontent.com/43270413/145591418-277744b3-7cd2-4d89-bc8c-845eedea8c82.jpg)
![000443](https://user-images.githubusercontent.com/43270413/145591425-f0f75759-69d9-472b-90fe-9d039a8c381b.jpg)
![000444](https://user-images.githubusercontent.com/43270413/145591434-4252bf81-9bc3-4506-82d5-29f60bc23741.jpg)
![000445](https://user-images.githubusercontent.com/43270413/145591443-6a8009cd-2dd7-4b78-b0b0-0bc2f01e68d7.jpg)
![000446](https://user-images.githubusercontent.com/43270413/145591453-63f704fc-170e-4a7f-808b-5498b4fb75a1.jpg)
![000447](https://user-images.githubusercontent.com/43270413/145591460-03f42957-9436-41e2-8f53-42817c146669.jpg)
![000448](https://user-images.githubusercontent.com/43270413/145591468-2c7ce331-6ab4-41f3-a0cf-1457a6b10708.jpg)

**Comment by leilaUEA** [comment]
first camera:
![000438_rendered](https://user-images.githubusercontent.com/43270413/145594151-053bab09-c1e8-41c0-97a3-6f4473c23fdf.png)
![000439_rendered](https://user-images.githubusercontent.com/43270413/145594175-b42bf29f-4116-4f97-8224-14982cf86449.png)
![000440_rendered](https://user-images.githubusercontent.com/43270413/145594194-9b2219f1-2c32-4dd9-9686-ea63be4ba112.png)
![000441_rendered](https://user-images.githubusercontent.com/43270413/145594206-36249fed-1969-4813-8f69-6aaba080457f.png)
![000442_rendered](https://user-images.githubusercontent.com/43270413/145594217-7580d4dd-4b8b-47da-b57e-7b896b6330c6.png)
![000443_rendered](https://user-images.githubusercontent.com/43270413/145594227-478c7a66-2386-4104-997e-8d37bf028725.png)
![000444_rendered](https://user-images.githubusercontent.com/43270413/145594235-bf70ee81-bfa8-4814-a18e-6e3fb365dd0b.png)
![000445_rendered](https://user-images.githubusercontent.com/43270413/145594241-e477365f-bc62-449b-96ee-8cceb434a972.png)
![000446_rendered](https://user-images.githubusercontent.com/43270413/145594250-b5007481-8576-476e-922d-7fe0fd8f4c57.png)
![000447_rendered](https://user-images.githubusercontent.com/43270413/145594262-810fac06-9d33-447b-9153-bf78c98d1d8a.png)
![000448_rendered](https://user-images.githubusercontent.com/43270413/145594273-06fbd2fd-b111-4e93-b85a-2825c572bb1a.png)

**Comment by leilaUEA** [comment]
second camera
![000438_rendered](https://user-images.githubusercontent.com/43270413/145594585-4cc3d091-91e3-4f7a-bf29-a66b6cc6dd25.png)
![000439_rendered](https://user-images.githubusercontent.com/43270413/145594601-69b2118d-f3af-43be-a256-550e61c045e2.png)
![000440_rendered](https://user-images.githubusercontent.com/43270413/145594614-bf294aeb-0662-4428-b16b-69223b374cf4.png)
![000441_rendered](https://user-images.githubusercontent.com/43270413/145594622-f7b3fde1-ddfa-496a-aca4-927fe79030d3.png)
![000442_rendered](https://user-images.githubusercontent.com/43270413/145594630-5925a74e-574f-44f1-a2a0-263921233fab.png)
![000443_rendered](https://user-images.githubusercontent.com/43270413/145594640-8903b676-c058-41ff-843c-e73476d9666d.png)
![000444_rendered](https://user-images.githubusercontent.com/43270413/145594655-be7d08ad-3311-4d9c-873a-9877edc375c0.png)
![000445_rendered](https://user-images.githubusercontent.com/43270413/145594667-0725564a-c451-425e-abcc-0ce19ac44965.png)
![000446_rendered](https://user-images.githubusercontent.com/43270413/145594686-924b8eb8-8be7-4499-ad14-b4fa79ba5572.png)
![000447_rendered](https://user-images.githubusercontent.com/43270413/145594695-eae6aa83-0398-4cd6-aeaf-64644bbcfea6.png)
![000448_rendered](https://user-images.githubusercontent.com/43270413/145594708-818f9f37-7b8e-4293-93c5-6af7e831bbe7.png)

**Comment by leilaUEA** [comment]
![000438_rendered](https://user-images.githubusercontent.com/43270413/145596887-f92cf8be-4c78-4c1c-9f38-5cee6afd5fe6.png)
![000439_rendered](https://user-images.githubusercontent.com/43270413/145596904-46521496-95d0-4aed-b012-9d561f2eb016.png)
![000440_rendered](https://user-images.githubusercontent.com/43270413/145596918-a714679d-ebf7-4c6b-8ceb-2e54a1a8a689.png)
![000441_rendered](https://user-images.githubusercontent.com/43270413/145596932-f2e48de8-8fe9-42a4-ac32-ed3c7ac08039.png)
![000442_rendered](https://user-images.githubusercontent.com/43270413/145596946-ae4a134d-76a5-4bfd-81bb-02e77e22c4b4.png)
![000443_rendered](https://user-images.githubusercontent.com/43270413/145596956-dc7a3490-033e-48c5-8f3d-fada4feb147a.png)
![000444_rendered](https://user-images.githubusercontent.com/43270413/145596969-a0348ecf-ab45-4c13-b13a-1c60f1599632.png)
![000445_rendered](https://user-images.githubusercontent.com/43270413/145596982-162baab2-ea70-40d6-ad0a-fceb403fec72.png)
![000446_rendered](https://user-images.githubusercontent.com/43270413/145596995-cfb714a7-cda2-425a-a2a1-f3e4bd2e5e8e.png)
![000447_rendered](https://user-images.githubusercontent.com/43270413/145597005-2aa06e89-a87f-4e87-9814-65fd70e56002.png)
![000448_rendered](https://user-images.githubusercontent.com/43270413/145597022-61f612e8-e3a3-4194-bb6a-f942445b5bcf.png)

**Comment by chingswy** [comment]
It seems that the optimization falls into local optimal and generates a bad result.

**Comment by leilaUEA** [comment]
it was also mentioned smpl optimization doesn't use nose keypoints

**Comment by leilaUEA** [comment]
> 

it was also mentioned smpl optimization doesn't use nose keypoints, don't know if it affected the result

**Comment by chingswy** [comment]
Maybe fixed in current version.
