### ISSUE TITLE
Different cameras

### ISSUE THREAD

**Issue by missphyrgames** [zju3dv/EasyMocap#11]
Hello,

I was wondering if you can use different camera models for each camera, or do they all have to be the same model?

Thanks!

**Comment by carlosedubarreto** [comment]
Hello @missphyrgames 
I've been using different cameras for that, to be honest, I'm using different smartphones.
I guess what I usually have problems are the calibration of them.

**Comment by chingswy** [comment]
The cameras don't have to be the same. The only thing you should care is that you must set the proper camera parameters for each camera.

**Comment by missphyrgames** [comment]
Thank you @carlosedubarreto and @chingswy for that!

Just as a clarification, I wanted to know if my understanding of the steps to get this up and running were correct. 

1. I've setup the SMPL folder with all the required files (as mentioned in the README.md file)
2. I've installed all the required libraries
3. Now this is where I'm confused. It's not mentioned anywhere in the docs of how to calculate the intrinsic and extrinsic camera values. I looked at the file provided in the example zju-ls-feng folder, but it's all gibberish to me. Hopefully either of you could shed some light on this. I did find this library (https://github.com/ethz-asl/kalibr), is this what I should use to calibrate the multiple cameras?

4. Then I'm assuming I would run `scripts/preprocess/extract_video.py` script with the openpose parameter
5. After this, I would run the `code/demo_mv1pmf_skel.py` to get the skeletal render
6. Finally, I can use the information provided in output.md to export it into a .bvh format

I'm sorry if this is all mentioned clearly on the docs but I seem to not understand how to get it running for my own videos. Thanks again!

**Comment by carlosedubarreto** [comment]
I think your description is correct.

I just did some things different.

I calibrated the intrinsic using some other script I found somewhere I dont remember, and calibrated the extrinsic using the code provided in this repository.
I used the extract script, to extrac the video to images,
then I ran opepose on my own,
then I ran the extract again to it can take the anottations.

Then I ran the demo_mv1pmf_skel.py
to get the keyposes3d and now I'm using this result to creat an addon to import it to blender.

To use the bvh export, you should run the other script, the `python code/demo_mv1pmf_smpl.py`  one.

But I see you are on the right track IMHO.

And thanks for the link to Kalibr, I'm going to test it and see if it makes my calibration better. I'm still suffering with it.

**Comment by chingswy** [comment]
Thank you @carlosedubarreto for your helpful understanding. I think the most common problem is the step of camera calibration. I will add a script to calibrate intrinsics parameters recently. [OpenCV Tutorial](https://docs.opencv.org/master/dc/dbb/tutorial_py_calibration.html) helps me a lot to understand the calibration.

**Comment by missphyrgames** [comment]
Thanks @carlosedubarreto! Truly grateful for the description! I'll have another go with this again. 

Let me know what the results of Kalibr lead to!

**Comment by missphyrgames** [comment]
I'm very sorry to ask this again after both your help on this, but I'm struggling a lot on how to calculate the intrinsic and extrinsic values.

So my current understanding is (using the opencv link that @chingswy has kindly provided) that I have to print a checkerboard on to a piece of paper and hold up that checkerboard and run the script separately for each camera. To illustrate my point better, what I mean is I will take the checkerboard pattern and hold it up to the first camera, take a photo, and run the script to retrieve the intrinsic parameters. Then repeat those steps again for each camera in my setup? (A side question for this process is do I have to manually make it fit your yaml format?)

For the extrinsic parameters, my understanding is that I place the checkboard pattern where it will be visible to all the cameras (on the floor for example) and then take a picture on all of the cameras. Then run the scripts/calibration/calib_extri.py which will give me the extrinsic parameters.

Thank you so much again @carlosedubarreto  and @chingswy for all your help!

**Comment by carlosedubarreto** [comment]
@missphyrgames 

Please, take a look at this link of a previous issue and see if the explanations and code can help you

https://github.com/zju3dv/EasyMocap/issues/7#issuecomment-799202981

**Comment by missphyrgames** [comment]
Thanks @carlosedubarreto, that helped a bunch!

This is going to be another question (potentially very silly), but what I gathered from the point of calibrating the camera is to adjust for any distortion it may have. So does this mean I can move the camera to a different position in the real world and not have to calibrate both intrinsic and extrinsic again?

**Comment by missphyrgames** [comment]
That makes much more sense now, thanks @chingswy!! I'll have a go with the calibration soon and after that will close the issue.

**Comment by missphyrgames** [comment]
I came across something while creating the intri.yml file. In the zju-ls-feng intri.yml file it specifies the dist matrices as
```yaml
dist_1: !!opencv-matrix
   rows: 5
   cols: 1
```

but the data/examples/calibration/intri.yml file specifies it as 

```yaml
dist_1: !!opencv-matrix
   rows: 1
   cols: 5
```

Does it matter which one I use?

**Comment by chingswy** [comment]
It doesn't matter. Thank you for pointing out that.

**Comment by missphyrgames** [comment]
Thanks @chingswy!

**Comment by missphyrgames** [comment]
I've managed to calculate the intrinsic values for each of my cameras and created the intri.yml file. However, while calculating the extrinsic values, I get the following error:

```
Traceback (most recent call last):
  File "calib_extri.py", line 57, in <module>
    calib_extri_pipeline(args.path, args.out, args.rate, args.debug, args)
  File "calib_extri.py", line 30, in calib_extri_pipeline
    debug=debug, remove=False, resize_rate=resize_rate)
  File "..\..\code\mytools\camera_utils.py", line 105, in FindChessboardCorners
    ret, corners = _FindChessboardCorners(gray, patternSize, False)
TypeError: _FindChessboardCorners() takes from 1 to 2 positional arguments but 3 were given
```

The code I ran was:
```python
python scripts/calibration/calib_extri.py -i ./data/examples/calibration/extri_images -o ./data/examples/calibration --debug --pattern 9,6 --grid 0.024
```

I went to the ```mytools\camera_utils.py``` script and went to the specified line and found this piece with an extra parameter:

```
ret, corners = _FindChessboardCorners(gray, patternSize)
if not ret:
   ret, corners = _FindChessboardCorners(gray, patternSize, False)
```

**Comment by missphyrgames** [comment]
I've managed to get a final output after hours of work. It's still not ideal, maybe due to inaccurate calibration or lack of cameras, but I'll keep trying it out to get more accurate results. Thanks @chingswy and @carlosedubarreto for the help on getting this set up!
