### ISSUE TITLE
关于相机外参标定的问题

### ISSUE THREAD

**Issue by Cuanmaomao** [zju3dv/EasyMocap#115]
你好，请问一下：所有相机拍摄标定板时，必须让标定板放地面上吗？还是所有相机都看到的位置都可以？
标定完成后，默认的世界坐标系这样的吗？
                                          x方向：[1,0,0]
                                          y方向：[0,1,0]
                                          z方向：[0,0,1]

**Comment by chingswy** [comment]
如果放到地面上的话默认坐标系就是这样的

**Comment by Cuanmaomao** [comment]
谢谢啦，明白了
