### ISSUE TITLE
OpenPose consumes more than 8Gb of GPU memory on initial 2D extraction

### ISSUE THREAD

**Issue by VisionaryMind** [zju3dv/EasyMocap#116]
Within the first few milliseconds of running extract_2d, OpenPose consumes all of the GPU memory and crashes. with an [out of memory errors](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1527). I have attempted to lower image resolution or use only one image (by deleting all video extracted images), and this still happens. The command used was:

`python scripts/preprocess/extract_video.py ~/data/video --handface`

It will crash and consume all memory with or without the _handface_  or disabled _hires_ arguments. 

You have listed Yolo-HRNet as a supported alternative, but the code is missing support for this mode. A Detector module is called, but it is not present in the respository and I could not find any implementation of it elsewhere. Here is the error:

```
Traceback (most recent call last):
  File "scripts/preprocess/extract_video.py", line 285, in <module>
    extract_yolo_hrnet(image_root, annot_root, args.ext, args.low)
  File "scripts/preprocess/extract_video.py", line 203, in extract_yolo_hrnet
    from easymocap.estimator import Detector
ImportError: cannot import name 'Detector' from 'easymocap.estimator' (/easymocap/easymocap/estimator/__init__.py)
```
Starting with line 203 of extract_video.py:

```
def extract_yolo_hrnet(image_root, annot_root, ext='jpg', use_low=False):
    imgnames = sorted(glob(join(image_root, '*.{}'.format(ext))))
    import torch
    device = torch.device('cuda')
    **from easymocap.estimator import Detector**
```

Everything is setup on my workstation properly. I have CUDA 11.2 / cuDNN 8.2.1, and other libraries such as VIBE work without a problem. It appears OpenPose is the issue. Any advice to get this up and running would be appreciated.

**Comment by VisionaryMind** [comment]
After some digging, it would appear that OpenPose is simply a dinosaur. It is not well maintained and still relies on CUDA versions 10 or below. Here is a [thread](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1913) talking about this problem. That is why VIBE doesn't have this problem (they don't rely on the outdated OpenPose). Until the OpenPose developers decide to bring their code up to date, any project that uses it will have low adoption rates. Please consider either working around the copyright issue with Yolo-HRNet or implementing another library that can work with modern implementations of CUDA / cuDNN. I am reluctant to downgrade my system to CUDA 10.1 simply to use EasyMocap.

**Comment by chingswy** [comment]
Hello, I update the code to support mediapipe, which is easy to install with CPU. Just pull the code and run
```bash
# detect the body keypoints
python3 apps/preprocess/extract_keypoints.py ${data} --mode mp-pose
# detect the body, hand face
python3 apps/preprocess/extract_keypoints.py ${data} --mode mp-holistic
```
However, mediapipe only supports 1 person now. And the definition of the face keypoints is not the same as OpenPose.

**Comment by sparshgarg23** [comment]
Hello,thanks for providing the update,I have one question when we execute scripts/preprocess/extract_video,the script relies on using openpose keypoints as shown in line 225 in preprocess/extract_video.py

Would it be possible to use the results of mediapipe in this script. similar to the way extract_keypoints.py is using

**Comment by chingswy** [comment]
Hello, `apps/preprocess/extract_image.py` + `apps/preprocess/extract_keypoints.py` have all the functions of `scripts/preprocess/extract_video.py`. The old script will be deprecated.

**Comment by sparshgarg23** [comment]
so just to rephrase the functionality i am expecting can be achieved with extract_keypoints and there is no need to use extract_video right.

**Comment by chingswy** [comment]
Yes

**Comment by sparshgarg23** [comment]
ok thanks for taking the time to get back in touch with me.
