### ISSUE TITLE
Mediapipe predict strange results

### ISSUE THREAD

**Issue by JACKYLUO1991** [zju3dv/EasyMocap#117]
<img width="437" alt="微信截图_20211228135835" src="https://user-images.githubusercontent.com/21237742/147533127-d3f134db-bf28-4297-8ca5-d0ec4f4ca890.png">
But Openpose succeed...

**Comment by chingswy** [comment]
It seems that some keypoints wrong on the heat...Could you show the detection results?

**Comment by NishilVani** [comment]
Do you found any solution ?

**Comment by JACKYLUO1991** [comment]
@NishilVani I think it has to do with the fact that the order of the face landmarks does not correspond.
