### ISSUE TITLE
[Question] Did you support MVPose (CVPR 2019) in PyTorch here?

### ISSUE THREAD

**Issue by liqikai9** [zju3dv/EasyMocap#118]
Thanks for your great work! I was wondering whether you have implemented your work [MVPose](https://github.com/zju3dv/mvpose)  on CVPR 2019 in the PyTorch version? If you have done, I will be very glad if you can offer the source code! Thanks agan.

**Comment by chingswy** [comment]
This repo's implementation is not as the same as the origin. This [operation](https://github.com/zju3dv/EasyMocap/blob/master/doc/mvmp.md#1-reconstucting-human-pose) have the similar functions for this task.
