### ISSUE TITLE
where 's the calib_all.py

### ISSUE THREAD

**Issue by songkk** [zju3dv/EasyMocap#119]
some blogs say there is a file calib_all.py, 
python3 apps/calibration/calib_all.py --ground ${ground} --match ${match} --intri ${ground}/intri.yml --extri ${ground}/extri.yml --out ${match}/out-ba --undis
while I can't find it?

**Comment by chingswy** [comment]
This part is not public now and will be released in the future.

**Comment by Shihaijun408** [comment]
郭博士，您好!我参考您的知乎做相机标定，思路清晰。在进行BA处理时，github上发现没有calib_all.py。您能把这个脚本分享一份吗？需要借用BA绑定毕业，比较着急，在线等ing。如果可以请给我的邮箱发一份，谢谢！420923952@qq.com
