### ISSUE TITLE
Paper for EasyMocap or more details somewhere?

### ISSUE THREAD

**Issue by jamalknight** [zju3dv/EasyMocap#129]
Hi there

Where can I find more info about EasyMocap? Is there a paper describing it somewhere with details?
It uses OpenPose, would it be safe to assume that EasyMocap is heavily based on OpenPose?

Regards,
Jamal

**Comment by chingswy** [comment]
There is no paper describing the repo now. We will update the documents for this purpose.
It is not heavily based on OpenPose, we also support other 2D keypoints method like mediapipe.
