### ISSUE TITLE
about the effect of MV1P function between version 0.1 and 0.2

### ISSUE THREAD

**Issue by JordenQiao** [zju3dv/EasyMocap#13]
the effect of v0.1 
![image](https://user-images.githubusercontent.com/47941141/115531200-16d23a80-a2c7-11eb-9a84-775996316220.png)

the effect of v0.2
![image](https://user-images.githubusercontent.com/47941141/115531236-218ccf80-a2c7-11eb-9b42-a2c3c10dce1c.png)

the effect of v0.2 seems to be worse than effect v0.1. Any idea why?

Thanks a lot

**Comment by chingswy** [comment]
It seems that the two versions are both wrong. Maybe there exist some errors in your camera calibration.
You can check out the `apps/calibration/check_calib.py` to check the camera parameters.
