### ISSUE TITLE
Can EasyMocap run in realtime?

### ISSUE THREAD

**Issue by siyuan-peng** [zju3dv/EasyMocap#131]
I'm working on a real-time project. I'm wondering if I could adapt EasyMocap to achieve realtime performance.
I followed the quickstart and found that the triangulation & rendering processes are incredibly slow. 
Is it possible for EasyMocap to run in realtime? Or does it only run on offline videos?
Thank you!

**Comment by chingswy** [comment]
This repo is designed to run mocap on offline videos, not for realtime purpose.
