### ISSUE TITLE
extract_2d not found in extract_keypoints.py

### ISSUE THREAD

**Issue by kaufManu** [zju3dv/EasyMocap#132]
When running `apps/preprocess/extract_keypoints.py` in the `openpose` mode, the script tries to import

```
from easymocap.estimator.openpose_wrapper import extract_2d
```

However, this function does not exist in the specified place. There's a function called `extract_2d` in `scripts/preprocess/extract_video.py`. Can the latter replace the former?

**Comment by chingswy** [comment]
I will fix it later.

**Comment by chingswy** [comment]
Fix it.
