### ISSUE TITLE
extri.yml

### ISSUE THREAD

**Issue by caiyongqi** [zju3dv/EasyMocap#133]
请问用自己数据集时，extri.yml中的R和T是世界坐标系到相机坐标系的旋转和平移吗？

**Comment by caiyongqi** [comment]
对于一个3D 人体scene（.obj)，我有使用blender从N个视角下渲染的N个图片和N个相机参数（世界坐标系到相机坐标系的旋转R和平移T，以及内参K)。请问我可以把它当作只有1帧的视频，从而来估计该人体的SMPL在世界坐标系下的vertices坐标吗? 它似乎不太能工作:(左out/smpl/repro/, 右out/smpl/smpl）
![000000](https://user-images.githubusercontent.com/47025383/157016851-f02461b0-d364-4b18-851a-a9c672768b4d.png)
![000000](https://user-images.githubusercontent.com/47025383/157016921-c56cb871-33e3-438c-adef-2f8f5d7403ab.jpg)

**Comment by chingswy** [comment]
Extrinsic parameter contains `R`,`T` for each camera, where `RX + T` converts point `X` in world coordinate to camera coordinate.

**Comment by caiyongqi** [comment]
> Extrinsic parameter contains `R`,`T` for each camera, where `RX + T` converts point `X` in world coordinate to camera coordinate.

So the camera parameters in extri.yml are also like this? In addition, what about the axes? I use MeshLab to open the output vertices but get weird visualizations. It doesn't seem to be the default coordinate system in OpenGL (the x-axis is left, the y-axis is up, satisfying the right-hand rule).
![image](https://user-images.githubusercontent.com/47025383/157050386-1fd42d39-c219-4cad-b19f-5b49006b666a.png)

**Comment by chingswy** [comment]
Your camera parameter must be wrong. The definition of blender may be a little different from OpenCV.

**Comment by chingswy** [comment]
Z represents up vector and xOy forms the ground plane. They follow right hand rule.
