### ISSUE TITLE
糟糕的重投影结果

### ISSUE THREAD

**Issue by wkMvg** [zju3dv/EasyMocap#134]
hi，
我使用4个相机，首先用open pose估计2d pose结果看起来非常好；然后我运行mv1p.py估计smpl，得到了非常差的repro结果
下边是我的冲投影结果
![000003](https://user-images.githubusercontent.com/48551366/157154254-ec699019-719e-4bbb-b91e-541113df6726.jpg)
开始我是我的标定问题，我就用了您工程的标定方法进行标定，calib check结果如下，冲投影结果看起来不错，但是使用这个外参运行mv1p.py估计smpl，得到的repro结果还是如上图一样差，请问还有什么可能 的原因造成这个错误结果的出现吗？
![000000](https://user-images.githubusercontent.com/48551366/157154010-f7e278ea-9f2f-4102-b614-74a8054f5df3.jpg)

**Comment by chingswy** [comment]
可以提供测试数据与运行指令

**Comment by wkMvg** [comment]
外参标定：
因为opencv的角点检测结果不准确，这里我用了matlab的角点检测结果，这两个角点坐标系一个在棋盘格左上角，一个在右下角，这里我直接用matlab的坐标系；在获取图像时，已经提前做了去畸变，所以这里内参的畸变都是0，外参标定的数据如下：
[extrin_data.zip](https://github.com/zju3dv/EasyMocap/files/8203329/extrin_data.zip)
[intrin_data.zip](https://github.com/zju3dv/EasyMocap/files/8203332/intrin_data.zip)
外参标定运行指令：python3 apps/calibration/calib_extri.py ${extri} --intri ${intri}/output/intri.yml
openpose指令：python3 scripts/preprocess/extract_video.py ${data} --openpose <openpose_path>
回归smpl指令：python3 apps/demo/mv1p.py ${data} --out ${data}/output/smpl --vis_det --vis_repro --undis --sub_vis 0 1 2 3  --vis_smpl
非常感谢

**Comment by chingswy** [comment]
看上去是棋盘格的检测结果是错误的；可以看0和2号相机，同样颜色的棋盘格点对应的不是同样的点

**Comment by wkMvg** [comment]
是的，我发现我的matlab的四个view的角点顺序是不一致的，这造成了我的重投影结果很差
