### ISSUE TITLE
正确的3d重投影，错误的smpl重投影

### ISSUE THREAD

**Issue by wkMvg** [zju3dv/EasyMocap#135]
Hi，
![000004](https://user-images.githubusercontent.com/48551366/157360893-a44f7478-6473-4ab3-a311-df57348b738a.jpg)
![000004](https://user-images.githubusercontent.com/48551366/157360922-ca806ac0-dc5c-493c-8cae-41e6318567c3.jpg)
![000004](https://user-images.githubusercontent.com/48551366/157361045-93ebaf47-5cc7-43b2-b745-ccfe292025c1.jpg)
![000004](https://user-images.githubusercontent.com/48551366/157361067-dad2d7c9-b0f9-45bf-984c-11c741865feb.jpg)

从上到下四张图像分别是open pose的2d skeleton，计算3d skeleton的重投影图像，拟合smpl参数后的skeleton和smpl的重投影图像。
3d skeleton正确可以说明我的外参标定是正确的，那么还有可能是什么原因造成smpl参数回归错误呢
python3  apps/demo/mv1p.py datapath --out datapath/output/smpl --vis_det --vis_repro --undis --sub_vis 0 1 2 3 --vis_smpl

**Comment by chingswy** [comment]
看上去基本正确,可以测试一下其他姿态的结果.

**Comment by wkMvg** [comment]
![000160](https://user-images.githubusercontent.com/48551366/157385162-8775782f-169b-4c4b-b059-9d46efc4654c.jpg)
![000160](https://user-images.githubusercontent.com/48551366/157385294-3370f7d8-03ca-4960-b5a6-3edae8f82c53.jpg)
![000211](https://user-images.githubusercontent.com/48551366/157385330-c6a9e329-83d9-4d19-b2b1-8f8c344e6e8b.jpg)
![000211](https://user-images.githubusercontent.com/48551366/157385377-a799d9c7-c255-4e77-978b-09619c5219ac.jpg)
这是一些其他姿态的结果，都是3d keypoint的重投影看起来比较准确，smpl的重投影却有很大的偏差，会是什么原因呢？非常感谢您的回复

**Comment by wkMvg** [comment]
![image](https://user-images.githubusercontent.com/48551366/157394402-c35c6418-0253-4e2e-822b-e281bf4ee3c8.png)
我可视化了3d点和最终输出的smpl 感觉下半身的效果要比上半身的好，是上半身和下半身的loss有不同的权重分布吗

**Comment by wkMvg** [comment]
![1646812060(1)](https://user-images.githubusercontent.com/48551366/157395942-10401d97-3d13-4095-a737-acd52b28b511.png)
黄色的是最终输出的smpl 红色的是用来回归的3d点

**Comment by wkMvg** [comment]
我仔细阅读了代码，发现了两个关于帧间的pose和keypoints的smooth loss，因为我的原始数据帧率较低，导致这两项loss非常高，导致最终得到的smpl错误，注释掉这两个loss之后，结果正常了。所以现在我就close issue了

**Comment by caiyongqi** [comment]
> 我仔细阅读了代码，发现了两个关于帧间的pose和keypoints的smooth loss，因为我的原始数据帧率较低，导致这两项loss非常高，导致最终得到的smpl错误，注释掉这两个loss之后，结果正常了。所以现在我就close issue了

你好，我现在碰到了类似的困难。我的open pose的2d skeleton，计算3d skeleton的重投影图像和smpl的重投影图像看起来还好，但是拟合smpl参数后的skeleton结果非常糟糕。您能给点意见吗? 谢谢。（我使用的是静态的场景，即有多个相机但是只有一帧，这会有影响吗?）
![000000](https://user-images.githubusercontent.com/47025383/159838469-315e27be-9c7a-4d15-bac0-88d521bd26e3.jpg)
![000000](https://user-images.githubusercontent.com/47025383/159838435-0bae5221-7c44-4ac1-a3ce-22450bc39784.jpg)
![000000](https://user-images.githubusercontent.com/47025383/159838495-a1da4d95-8b36-4047-9558-b687a143a8f3.jpg)
![000000](https://user-images.githubusercontent.com/47025383/159838524-d24c5e79-6931-49e9-95e7-275e1822acc3.jpg)
#138
