### ISSUE TITLE
Increase video resolution

### ISSUE THREAD

**Issue by jamalknight** [zju3dv/EasyMocap#139]
If I would like to increase the capture area ie. increase the distance between cameras, can I use a higher resolution image? So instead of using a video resolution of 1280x720, can I record in HD (1920x1080) or 4K (3840x2160)?

I would imagine processing times would increase.

Or will the images be downsized to 1280x720 anyway and won't make much difference?

Thanks

**Comment by chingswy** [comment]
You can use a higher resolution image. The processing times will not increase much except the rendering process.

**Comment by jamalknight** [comment]
Thanks!
