### ISSUE TITLE
Spin Installation

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/EasyMocap#14]
I was following the instructions, but seems there was some confusion.

The instruction said
0.2 (Optional) SPIN model
Fetch the extra data here ([http://visiondata.cis.upenn.edu/spin/dataset_extras.tar.gz](http://visiondata.cis.upenn.edu/spin/dataset_extras.tar.gz)) and place the smpl_mean_params.npz to data/models/smpl_mean_params.npz.

But that file there was no **smpl_mean_params.npz**

Searching, I found that the smpl_mean_params.npz is in the link bellow
[http://visiondata.cis.upenn.edu/spin/data.tar.gz](http://visiondata.cis.upenn.edu/spin/data.tar.gz)

**Comment by chingswy** [comment]
Thank you very much!
