### ISSUE TITLE
scale about 3Dkeypoints

### ISSUE THREAD

**Issue by violet257** [zju3dv/EasyMocap#143]
Hi, thanks for your contribution on this useful toolbox.
In your code, preprocess/pre_panoptic.py, apply SCALE = 100
 to the camera transformation matrix and some 3D keypoints, I wonder why. 
Since I use it to generate smpl mesh, and reproject it back to images plane, it will cause some shifting if human close to camera.

**Comment by chingswy** [comment]
Hello, this `scale100` is only for panoptic dataset as their unit is `cm` instead of `meter` we use.

**Comment by violet257** [comment]
Thanks! I wonder weather you have met this problem, the projection becomes wrong if humans are close to the camera
![000000](https://user-images.githubusercontent.com/101210250/163248236-46e21b01-5fde-4a13-9f6b-d97d8f5a557d.png)
![000001](https://user-images.githubusercontent.com/101210250/163248528-926cac77-c064-4fc8-b58d-101f8f3e9aae.png)

**Comment by chingswy** [comment]
Hello, the input image must be `undistort` before you reproject the SMPL to image.
