### ISSUE TITLE
There is a big gap between the joint points obtained by openpose and smpl model, how to fit?

### ISSUE THREAD

**Issue by Alex-JYJ** [zju3dv/EasyMocap#144]
![6b5767c7f01da6dae52bbe1b0d153de](https://user-images.githubusercontent.com/36917338/162866844-2fd68c49-db5f-4f94-a8d4-b833315e9b3e.png)
![53fee38fe85861fe5d54dfc194f1f37](https://user-images.githubusercontent.com/36917338/162867100-f5c9c061-25da-4ee3-a841-242ec3928297.png)

As shown in the figure above, there is a large gap between the joint points obtained by openpose and the joint points defined by smpl (x) model, which may be the reason for the error of the following reprojection results. How to solve this problem in model fitting?Thanks！

![image](https://user-images.githubusercontent.com/36917338/162867497-e8edc779-a99e-442b-82ee-72f121c3256f.png)
![image](https://user-images.githubusercontent.com/36917338/162867559-9ce8c049-9796-4eee-8d88-f2d8b8e65666.png)
The above are the results of repro and repro_ smpl respectively, repro is very good, but repro_ smpl has obvious errors in hip, knee and 4 foot joints.

**Comment by chingswy** [comment]
Hello, this result may caused by bad fitting.

**Comment by Alex-JYJ** [comment]
> Hello, this result may caused by bad fitting.

Thanks for your reply, I finally found it is because the bad predicted `params['shapes'] ` after lots of experiments. 
If I changed `params['shapes'][0]` by hand, it can fit better. So how can I change the optimizeShape function to fit my data? If you can give some advice, I will appreciate it very much!
https://github.com/zju3dv/EasyMocap/blob/60a1fade5ef3e921130c776713e36e798c487587/easymocap/pipeline/basic.py#L59-L65
I used SMPLX model, and I have tried to change the kintree to `CONFIG['bodyhandface']['kintree'][1:]`. But it doesn't seem to work.

**Comment by chingswy** [comment]
Maybe `weight_shape` is too large. Idealy, if you set `weight_shape=0.`, you will get the best repro_keypoints.

**Comment by Alex-JYJ** [comment]
I tested `reg_shapes=0` just now, it doesn't work. If I set `weight_shape=0`, then loss will be 0. The shape params will not be optimized?

**Comment by chingswy** [comment]
It supposed to work if you set `reg_shapes=0`.

**Comment by Alex-JYJ** [comment]
I changed the loss about shapes, and solved the problem! Thanks for your work and reply, I will close the issue.
