### ISSUE TITLE
How to create J_regressor_body25.npy

### ISSUE THREAD

**Issue by wngTn** [zju3dv/EasyMocap#145]
Hey everybody,

how exactly can you create regressors such as `J_regressor_body25.npy`. If someone could show me a link or something I would highly appreciate it!

**Comment by Alex-JYJ** [comment]
https://smpl-x.is.tue.mpg.de/  
register and download

**Comment by wngTn** [comment]
Thank you for your answer,  but download what exactly?

**Comment by chingswy** [comment]
Hello, this file is from previous works but I forget which one.

**Comment by QiFuChina** [comment]
> Thank you for your answer, but download what exactly?

Hello, I have same question like you. I also looking for the J_regressor_body25.npy and other .txt files that should be placed under ` data/smplx ` . Could you please tell me which item to get this ?
