### ISSUE TITLE
Extrinsic Calibration

### ISSUE THREAD

**Issue by tonywin6** [zju3dv/EasyMocap#148]
Hello, I have a few questions to ask.
1. How long videos or how many pictures are needed to record intrinsic and extrinsic parameters?
2. Calibrate extrinsic parameters. When recording a video, does the chessboard need to be moved when it is placed on the ground?
3. If calibrating extrinsic parameter needs move the chessboard, what method is used to move it?

**Comment by chingswy** [comment]
1. We recommand using ~200 images to calibrate intrinsic parameters. You could record 2000 frames and sample from them.
2. Placed on the ground.

**Comment by LRuid** [comment]
Calibrate extrinsic parameters.If chessboard is placed on the wall , What will the result be？
