### ISSUE TITLE
check calibration cube

### ISSUE THREAD

**Issue by pablovela5620** [zju3dv/EasyMocap#150]
I'm not sure what I'm doing wrong, but these are the images I get when checking calibration for 2 cameras

![image](https://user-images.githubusercontent.com/25287427/167041376-6ccda8b8-2773-4063-ad35-e47fb65de59b.png)
![image](https://user-images.githubusercontent.com/25287427/167041383-a3d402b2-29b1-42e8-bb63-12d9fc9d0123.png)

when using the first test, I get much more reasonble results
![image](https://user-images.githubusercontent.com/25287427/167041582-fdaad815-f5de-412c-8240-1c405e1ce505.png)
![image](https://user-images.githubusercontent.com/25287427/167041591-c339f762-abb2-4e29-a51c-d9f36b77b586.png)

While in the documentation it shows a much more clean cube, I also noticed the issue #71 had similar problems. Any idea what may be going on? I manually labeled the checkerboard so I don't believe its a problem with that (though they may not be the highest possible precision)

Any idea whats going on?

**Comment by chingswy** [comment]
Hello, your pattern of the chessboard may be wrong. It's must be not **centrosymmetric**.

**Comment by pablovela5620** [comment]
Looks like I'm still having the same problem. For context I used the pattern you linked above, set the --grid value to 0.02, collected ~15 images for each camera to generate the intrinic parameters and ~8 images for the extrinsic parameters (for a quick and dirty test). This what I get for the --vis --s
how when doing calibrate camera
![000000](https://user-images.githubusercontent.com/25287427/167216308-028ba78d-3d28-49a1-9990-4a9dd3d1b337.jpg)

but for the cube calibration test I get
![image](https://user-images.githubusercontent.com/25287427/167216404-d332a830-86e7-400d-84e4-9e1285acd9a1.png)
![image](https://user-images.githubusercontent.com/25287427/167216421-935785d0-f5bd-4fd1-81ad-d82e8878cbd8.png)

Could this be an issue with the scale/grid parameters? I noticed that in the example provided a much much larger checkerboard is used

**Comment by pablovela5620** [comment]
Wanted to add a few things. It seems like the detection/3d skeleton recon/smpl fitting are working, but the smpl repro is not and I'm not sure if this has to do with the potentially bad extrinsic parameters. Attached videos to show

https://user-images.githubusercontent.com/25287427/167231842-68b37346-1791-4ec4-a23e-693d62241e9e.mp4

https://user-images.githubusercontent.com/25287427/167231858-98e54058-391e-499f-86b3-063db36ed31e.mp4

https://user-images.githubusercontent.com/25287427/167231863-2650a8ca-2c9a-482a-95f9-beb7a4e8594d.mp4

**Comment by chingswy** [comment]
Hello, the videos cannot be played. The length of the edge of the showed `cube` is `1meter`.

**Comment by pablovela5620** [comment]
Sorry about that, fixed with gifs instead. In that case it sounds like the issue is potentially the size of the cube considering your square size is 200mm v.s. the 22mm I'm using. 

I'm still not fully sure why the reprojected smpl keypoints are failing while everything else seems to be okay. Does this have to do with the calibration or is it an unrelated problem?
![detect](https://user-images.githubusercontent.com/25287427/167252310-0f5f1ea7-fc07-4118-b164-8fdda15d789e.gif)

![repro](https://user-images.githubusercontent.com/25287427/167252646-d38a3c08-7bec-4da0-8c3d-54d1ecbdbf09.gif)

![repro_smpl](https://user-images.githubusercontent.com/25287427/167252575-5d50429a-eb31-4900-8212-5336e131a49a.gif)
![smpl](https://user-images.githubusercontent.com/25287427/167252578-e69306bc-cca4-4097-b446-702f577bb086.gif)

**Comment by chingswy** [comment]
Hello, if the rendered mesh seems good, it's all ok. Don't care about the reprojected SMPL joints. Maybe there is some bug.

**Comment by pablovela5620** [comment]
Understood, thanks! I think I may have found the bug. It looks like the keypoints confidence values are being set to 0 when projected from 3d->2d. I added an ugly workaround for now to verify. 

On line 89 of mv1p.py
```python
if args.vis_repro:
    keypoints = body_model(return_verts=False, return_tensor=False, **param)[0]
    kpts_repro = projectN3(keypoints, dataset.Pall)
    kpts_repro[:, :, -1] = 1
    dataset.vis_repro(images, kpts_repro, nf=nf, sub_vis=args.sub_vis, mode='repro_smpl')
```

But otherwise it sounds like as long as SMPL are showing up and original reprojection is good, the calibration is working?

**Comment by chingswy** [comment]
Yes.
