### ISSUE TITLE
About use open3d skeletons SMPL keypoints

### ISSUE THREAD

**Issue by NeekHua** [zju3dv/EasyMocap#152]
I want use easymocap package bone reconstruction and visualization SMPL model 24 key points for output.I read [https://github.com/zju3dv/EasyMocap/blob/b2d5bbcfd75a705e49eb3a6800be2d8b2e758bae/doc/realtime_visualization.md](url)
and change the same as oepnpose json file ,but open3d don't get any message.
I think easymocap is support openpose body_25 model output and bone reconstruction , maybe  I need change model.
What should I do? any  reply is appreciation for me

**Comment by chingswy** [comment]
Hello, I don't support reconstruction SMPL keypoints.

**Comment by NeekHua** [comment]
ok,thanks your reply

**Comment by Alex-JYJ** [comment]
> Hello, I don't support reconstruction SMPL keypoints.

Actually, I think you have got SMPL keypoints in the mv1p.py.
When I use mv1p.py to get keypoints, if I set `body_model(return_verts=True, return_tensor=False, **param)` https://github.com/zju3dv/EasyMocap/blob/c27bcf905d65f14907ebde0c1054e204c872cfb8/apps/demo/mv1p.py#L87, then I get `J_transformed` from lbs https://github.com/zju3dv/EasyMocap/blob/c27bcf905d65f14907ebde0c1054e204c872cfb8/easymocap/smplmodel/lbs.py#L233, is  `J_transformed`  SMPL keypoints?
