### ISSUE TITLE
About realtime visualization

### ISSUE THREAD

**Issue by NeekHua** [zju3dv/EasyMocap#153]
through this website [https://github.com/zju3dv/EasyMocap/blob/b2d5bbcfd75a705e49eb3a6800be2d8b2e758bae/doc/realtime_visualization.md](url)
I use open3d server realtime visualization own keypoints online,but I find open3d server visualization have delayed.
I find my port always changed and  in server,foraward and  update geometry is longer than offical example .
![image](https://user-images.githubusercontent.com/32665609/167332373-99c3a885-81ae-4b21-bfda-09cdc94fcc1b.png)

What should I do ?
Best wishes for everyone.

**Comment by chingswy** [comment]
How do you send the data? It's supposed to keep the port once connected.

**Comment by NeekHua** [comment]
@chingswy  I only build server  through
` python3 apps/vis/vis_server.py --cfg config/vis3d/o3d_scene.yml`
and in else code send 3d points to server.

**Comment by NeekHua** [comment]
I get my error,It's my wrong .Thanks author reply
