### ISSUE TITLE
funcl1 and funcl2 do the same calculation in easymocap/pyfitting/lossfactory.py

### ISSUE THREAD

**Issue by pzxdd** [zju3dv/EasyMocap#159]
`funcl2 = lambda x: torch.sum(x**2)`

`funcl1 = lambda x: torch.sum(torch.abs(x**2))`

funcl1 needs to be changed as  below:
`funcl1 = lambda x: torch.sum(torch.abs(x2))`

**Comment by chingswy** [comment]
Thanks.
