### ISSUE TITLE
shape params do not update when use mv1p demo

### ISSUE THREAD

**Issue by mhz9123** [zju3dv/EasyMocap#164]
thank for your impressive work.
after running mv1p demo, shape params do not update, body_params['shapes'] is [0,0,0,0,0,0,0,0,0,0]. 
1、question1
it uses /easymocap/pyfitting/optimize_simple.optimizeShape() to train shape params, i add a flag in closure() when debug, find  body_params['shapes'] update every iter, but finish fitting.run_fitting(), body_params['shapes'] back to [0,0,0,0,0,0,0,0,0,0].why?
2、question2
in closure(),  body_model(return_verts=False, return_tensor=True, only_shape=True, **new_params), i set  only_shape=False as optimize R、T and POSE in _optimizeSMPL(),  everything is ok, it works, shape params update.  why?

感谢作者的工作，让我学习到很多东西。
当我运行完mv1p这个demo，发现形状参数并没有优化，全都是0。
1、问题1
/easymocap/pyfitting/optimize_simple.optimizeShape() 是训练shape参数的代码，我在closure() 添加了断点调试，在每个迭代中，参数都更新，但是完成fitting.run_fitting()这个代码后，shape参数又回到了全0状态。这是为什么？
2、问题2
在optimizeShape()的closure()中，我把body_model()的only_shape置为False，就像优化R、T and POSE一样，默认都是False. 最终正常了，最终参数也都更新了。为什么？

**Comment by chingswy** [comment]
可能有什么代码上的问题，我回头检查一下。
