### ISSUE TITLE
demo with openpose

### ISSUE THREAD

**Issue by luoww1992** [zju3dv/EasyMocap#167]
there are many wrong in demo with openpose,
so do you have a plan to fix it ?
and  i notice the args  --smooth3d has no func to do it.

**Comment by chingswy** [comment]
> there are many wrong in demo with openpose, so do you have a plan to fix it ? 

What's wrong do you mean?

> and i notice the args --smooth3d has no func to do it.

Yes. This smooth is unnecessary as we perform offline optimization among all frames.

**Comment by luoww1992** [comment]
@chingswy 
so do you have a plan to fix the  demo with openpose ?

**Comment by chingswy** [comment]
Not use `--smooth3d`.
