### ISSUE TITLE
global rotation problem in SMPLlayer forward

### ISSUE THREAD

**Issue by Alex-JYJ** [zju3dv/EasyMocap#168]
https://github.com/zju3dv/EasyMocap/blob/c27bcf905d65f14907ebde0c1054e204c872cfb8/easymocap/smplmodel/body_model.py#L368
Why is the rotation matrix transposed here, that is, inversed? Here https://github.com/zju3dv/EasyMocap/issues/103#issuecomment-968869019 you mentioned that `Rh` can be directly substituted into the `pose` parameter, but the use of the `pose` parameter after it is converted into a matrix does not need to be inversed. Did I get it wrong？
I try to remove the transpose, and the result can fit very well, but the `Rh` obtained will take a negative sign, and it will be different when it is converted into an Euler angle.

**Comment by chingswy** [comment]
Hello, vertices's shape is `Nx3`, to rotate the vertices, we should use `V @ R.T`, or `R @ V.T`
