### ISSUE TITLE
convert2bvh 相关问题

### ISSUE THREAD

**Issue by baojunshan** [zju3dv/EasyMocap#169]
作者您好，想请教一下，生成的bvh文件如何把第一帧设置为T-pose？并且，目前的bvh好像是在相机坐标系下的，如何转为地面坐标系呢？

**Comment by chingswy** [comment]
你好，可以在Blender里面操作，将第一帧数据的姿态参数修改为0。
目前的bvh应该就是在世界坐标系下的。

**Comment by baojunshan** [comment]
> 你好，可以在Blender里面操作，将第一帧数据的姿态参数修改为0。 目前的bvh应该就是在世界坐标系下的。

感觉回复，我再尝试一下
