### ISSUE TITLE
Distortion handled correctly in Quickstart?

### ISSUE THREAD

**Issue by kaufManu** [zju3dv/EasyMocap#171]
I'm not sure whether image distortion is handled correctly in the Quickstart guide (I'm referring to this one: https://github.com/zju3dv/EasyMocap/blob/master/doc/quickstart.md).

From what I can see the following happens:
 - The images are extracted from a video and then fed to Openpose for 2D keypoint detections. During this stage, the images are not undistorted, i.e. 2D keypoints are detected in distorted images.
 - I cannot find any code that considers distortion in the triangulation or reprojection function (i.e. [simple_recon_person](https://github.com/zju3dv/EasyMocap/blob/c27bcf905d65f14907ebde0c1054e204c872cfb8/easymocap/mytools/reconstruction.py#L92)), but I think this should happen somewhere since the 2D keypoints are detected on the original, distorted images.
 
I am not sure if this is correct, hence this question. What I think would be the right way to go is:
- Either undistort the images and then in the 3D triangulation and backprojection the distortion can be ignored (which is what currently happens, except that the 2D keypoints are detected on distorted images if I'm not mistaken).
- Or leave the images as is, but then distortion must be considered in the triangulation and backprojection.

**Comment by chingswy** [comment]
Hello, this code runs detection on distorted images and undistort the 2D keypoints. Check this [line](https://github.com/zju3dv/EasyMocap/blob/c27bcf905d65f14907ebde0c1054e204c872cfb8/easymocap/dataset/base.py#L501) please.

**Comment by kaufManu** [comment]
Ah I see - thanks for the clarification!
