### ISSUE TITLE
Still interested in internet video mocap? 

### ISSUE THREAD

**Issue by marcboivin** [zju3dv/EasyMocap#172]
Hi,
I was doing research on recomposing 3D model from OpenPose data using a single, uncalibrated, camera feed. I stumbled on your repo by chance (looking for stuff around the body25 model) and noticed you had a teaser of such a thing in the readme.

Looked at the code and I don't see anything in there that would allow processing from an uncalibrated camera.

Do you still have interest in pushing this aspect? 

Kind regards,

**Comment by jryebread** [comment]
bump, when will the internet video mocap code be added?

**Comment by gqbay** [comment]
According to this repo, it will be released very soon. Documentation is in preparation stage already 🙏🤞

https://github.com/chingswy/easymocap-public-doc

**Comment by chingswy** [comment]
We have already released it.

**Comment by impactcolor** [comment]
Any one have any code examples of the internet video?

**Comment by chingswy** [comment]
> 

Check here for the example dataset and code[url](https://chingswy.github.io/easymocap-public-doc/quickstart/quickstart.html#demo-on-monocular-videos)
