### ISSUE TITLE
MANO output all zero

### ISSUE THREAD

**Issue by walsvid** [zju3dv/EasyMocap#174]
Following doc->quick start, using demo data and run
```
python3 apps/demo/mv1p.py ${data} --out ${data}/output/manol --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --body handl --model manol --gender male --vis_smpl
```
The output of mano pose params are all zeros, and the hands are always flat.
<img width="807" alt="image" src="https://user-images.githubusercontent.com/17134911/179505072-2e1f4a49-cf23-4c6b-9d53-e0cc16a9a613.png">
<img width="446" alt="image" src="https://user-images.githubusercontent.com/17134911/179505126-66ace79f-9b34-478b-8487-180556c17353.png">

However, when using smpl-x as body model, the results are correct.
<img width="438" alt="image" src="https://user-images.githubusercontent.com/17134911/179505295-35372677-d909-4c11-828e-f0fde866fea0.png">

When I look at previous issues, it seems that previous users have not encountered this problem. Are there any update introduce inconsistent behavior?

**Comment by Seasandwpy** [comment]
Hi, I also encounter the same problem. Did you solve the bug in the end @walsvid ?

**Comment by walsvid** [comment]
@Seasandwpy I did not solve the proplem. I think it may related to libraries version.
