### ISSUE TITLE
Can‘t get the 3D result’

### ISSUE THREAD

**Issue by Taylorminer** [zju3dv/EasyMocap#175]
When I send the 3D data in realtime_visualization.md. After I run a server The terminal like this:
![IMG_20220720_172320](https://user-images.githubusercontent.com/41726592/179948027-dcfa1c35-c7c5-4b4f-9e00-262f33555925.jpg)

I can't run the code(sen the 3D data) in the terminal. It seems that I can't send the data in the terminal directly.

**Comment by chingswy** [comment]
You should open a new terminal.

**Comment by Taylorminer** [comment]
> 

Thanks !!!

**Comment by Taylorminer** [comment]
@chingswy  Thanks for your reply. I'am a little confuse that if I test mvmp.py on my dataset, Should I detect the 2d keypoints to get the annots files ?
