### ISSUE TITLE
The json files in keypoints3d folder are empty

### ISSUE THREAD

**Issue by Taylorminer** [zju3dv/EasyMocap#176]
When I test mvmp.py on my own datasets, the json files in keypoints3d folder are empty.  The files in detec and keypoints2d seem normal. I debug this program, and I find that "(proposal != -1).sum() < cfg.min_views"(line 71 in associate.py). Thus, the program skip the following step("keypoints3d = batch_triangulate(keypoints2d, Pused)" line 75  in associate.py)). Can you tell me why I get this error?

**Comment by chingswy** [comment]
This step is check the minimal views. This may occur when the cameras are sparse or the scene is crowded.

**Comment by Taylorminer** [comment]
@chingswy Thanks for your reply. It seems some wrong in camera calibration. It work after I delete " k3d[:, 0] *= -1" like #155, but I don't know the reason.
