### ISSUE TITLE
json.decoder error (Mediapipe)

### ISSUE THREAD

**Issue by Vinayky86** [zju3dv/EasyMocap#178]
Hello.. thanks for this amazing development..
I was trying to use mediapipe for MV1P and i followed these steps 
1 - python apps/preprocess/extract_image.py 0_input\project 
2 - python apps/preprocess/extract_keypoints.py 0_input\project --mode mp-pose
and 
3 - python apps/demo/mv1p.py 0_input/project --out 1_output/project --vis_det --vis_repro --sub_vis 1 2 3 4 --vis_smpl 

but when i run 3rd steps (mv1p.py),  getting this error

Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 117, in <module>
    mv1pmf_skel(dataset, check_repro=True, args=args)
  File "apps/demo/mv1p.py", line 35, in mv1pmf_skel
    images, annots = dataset[nf]
  File "c:\mocap\easymocap\easymocap\dataset\mv1pmf.py", line 72, in __getitem__
    images, annots_all = super().__getitem__(index)
  File "c:\mocap\easymocap\easymocap\dataset\base.py", line 482, in __getitem__
    annot = read_annot(annname, self.kpts_type)
  File "c:\mocap\easymocap\easymocap\mytools\file_utils.py", line 46, in read_annot
    data = read_json(annotname)
  File "c:\mocap\easymocap\easymocap\mytools\file_utils.py", line 19, in read_json
    data = json.load(f)
  File "C:\Users\Vinayky86\anaconda3\envs\easymocap\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Vinayky86\anaconda3\envs\easymocap\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Vinayky86\anaconda3\envs\easymocap\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Vinayky86\anaconda3\envs\easymocap\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 19 (char 20)

Please correct me if I am doing any wrong steps 
thank you ...!!!

**Comment by chingswy** [comment]
Hello, you can print the filename when the error occurs.

**Comment by Vinayky86** [comment]
thanks for your response..!! 
am i following the right steps..?
1 - python apps/preprocess/extract_image.py 
2 - python apps/preprocess/extract_keypoints.py 
3 - python apps/demo/mv1p.py

"Actully i don't know lot of things about coading,  
can you please direct me what is the main reason of this error"
thanks a lot..!!

**Comment by chingswy** [comment]
Seems the file is corrupted. You can remove the `annots` folder and generate again.

**Comment by Vinayky86** [comment]
thanks...
i did this step around 4 times delete and regenerate the annots. but nothing happened. 
but i found little difference in mediapipe's annots 
in openpose annots  -  "filename": "images\\1\\000000.jpg",
in mediapipe annots -  "filename": "1\000000.jpg",
can it cause the Json.decoder error..?

**Comment by chingswy** [comment]
No. This won't cause the decode error.

**Comment by Vinayky86** [comment]
Ok thanks for your reply..!!!  I will try

**Comment by NishilVani** [comment]
The Problem is in the json files there should be two \\ in filename but there is only one

**Comment by chingswy** [comment]
Thanks @NishilVani . Maybe it's a bug in windows? I didn't test the code on Windows now.

**Comment by Vinayky86** [comment]
Thank you very much @NishilVani your code successfully convert .json file for each cameras, but easymocap giving same jsondecoder error. BTW thanks again for your help you are very kind, really appreciate 🙏🙏

**Comment by Vinayky86** [comment]
Thank you very much  @ferhatsb  exactly..👌you have solved the problem..👏👏❤️
