### ISSUE TITLE
there is a 3d view controle problem.

### ISSUE THREAD

**Issue by vicentowang** [zju3dv/EasyMocap#181]
when I change the 3d view of chessboard,  there is some kind of lost control of the 3d view rotation, becasue of some unexpected auto rotate from x-axis 

![image](https://user-images.githubusercontent.com/49265512/183880249-4761c11c-24f4-40ca-8de0-c07fa82bd602.png)

**Comment by chingswy** [comment]
Maybe you press key `a` for automatic rotation?

**Comment by vicentowang** [comment]
> Maybe you press key `a` for automatic rotation?

still, i wanna to find the reason for the problem.

**Comment by chingswy** [comment]
You can use mouse to change the 3d view. Nothing will happen.

**Comment by vicentowang** [comment]
> I change the 3d view of chessboard, there is some kind of lost control of the 3d view rotation

 exactly, I just change the 3d view of chessboard using mouse  , there is some kind of lost control of the 3d view rotation.

**Comment by chingswy** [comment]
Sorry, I have no idea.
