### ISSUE TITLE
COLMAP camera data and weird SMPL results

### ISSUE THREAD

**Issue by SuwoongHeo** [zju3dv/EasyMocap#182]
Hi, 

I tried the calibrated camera data using COLMAP rather than using any calibration method. The visualization of predicted SMPL is shown below, 
![image](https://user-images.githubusercontent.com/30944168/184113137-f01259d8-41c5-4878-8d66-b54e212be15b.png)

Here is the re-projection of triangulated 3D keypoints, 
![image](https://user-images.githubusercontent.com/30944168/184113524-cb2dc548-442e-4444-a73b-c548a5793d2e.png)

Since the re-projected keypoints are located well, I don't think it is a problem of wrongly predicted 2D keypoints or the scale. Is there any idea to solve this problem? 

+) I had tried to adjust the regularization weight (to zero). The shape seems very twisted. 

+) It seems like the coordinate conventions of COLMAP and Easymocap are different. When I reconstruct a scene with calibration data of those, the pose of the reconstructed mesh is different like below.  Is it the cause of the problem above?
![image](https://user-images.githubusercontent.com/30944168/184114346-00a53583-0f45-4c28-b36f-e4e4ad3a395b.png)

**Comment by chingswy** [comment]
Hello, our method assumes that the unit of camera parameters is `meter`. Always the calibration of COLMAP is without scale.

**Comment by SuwoongHeo** [comment]
@chingswy Thanks for quick reply! :) Could you please explain me bit more why scale is matter here?

**Comment by chingswy** [comment]
Hello, SMPL is learned from thousands of 3D body scans. The shape space of SMPL is limited to the scans.

**Comment by SuwoongHeo** [comment]
@chingswy I didn't realize an exact scale is important for estimating SMPL in multiview images. Thanks, I`ll close this issue.

**Comment by chingswy** [comment]
@SuwoongHeo In fact, we can extract the skeleton even without scale. We will add a scale parameter later.

**Comment by conradmccarthy6** [comment]
Hi @chingswy, have you implemented a scale parameter yet? This would be very helpful for combining SfM data with EasyMocap!
