### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/media/qing/Project/openpose'

### ISSUE THREAD

**Issue by mertmerci** [zju3dv/EasyMocap#183]
Hello, 

thank you for the repository!

I am trying to run the command 'python3 scripts/preprocess/extract_video.py ${data} --handface', even though I used it before I get the following error: 

python3 scripts/preprocess/extract_video.py ${data} --handface
cameras:  1 2 3
skip  seq/annots/1
skip  seq/annots/2
Traceback (most recent call last):
  File "scripts/preprocess/extract_video.py", line 275, in <module>
    extract_2d(args.openpose, image_root, 
  File "scripts/preprocess/extract_video.py", line 63, in extract_2d
    os.chdir(openpose)
FileNotFoundError: [Errno 2] No such file or directory: '/media/qing/Project/openpose'

I am using 3 cameras, the annotations are generated for the first two but in the last one the code is terminated with the error. 

Do you have any suggestions? 
Thanks in advance!

**Comment by chingswy** [comment]
Please use new pipeline now:
```bash
python3 apps/preprocess/extract_keypoints.py ${data} --mode openpose --hand --face
```

**Comment by danzelus** [comment]
How fix it in windows?
