### ISSUE TITLE
Cannot build the colab example.

### ISSUE THREAD

**Issue by codesoft00** [zju3dv/EasyMocap#186]
Colab : https://colab.research.google.com/drive/1Cyvu_lPFUajr2RKt6yJIfS3HQIIYl6QU?usp=sharing

I tried to build it using colab, but it failed.
fail step : SMPL reconstruction
how to solve this problem?

"error message"
triangulation: 100% 800/800 [03:58<00:00,  3.35it/s]
dump: 100% 800/800 [00:00<00:00, 5928.50it/s]
loading: 100% 800/800 [00:01<00:00, 460.71it/s]

/content/EasyMocap/easymocap/pyfitting/lbfgs.py:264: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  ../torch/csrc/utils/python_arg_parser.cpp:1174.)
  p.data.add_(step_size, update[offset:offset + numel].view_as(p.data))
-> [Optimize global RT  ]:   2.0s
-> [Optimize 3D Pose/800 frames]:   9.6s
-> [Optimize 2D Pose/800 frames]: 407.6ms
render:   0% 0/800 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/EasyMocap/apps/demo/mv1p.py", line 117, in <module>
    mv1pmf_smpl(dataset, args)
  File "/content/EasyMocap/apps/demo/mv1p.py", line 88, in mv1pmf_smpl
    dataset.vis_smpl(vertices=vertices[0], faces=body_model.faces, images=images, nf=nf, sub_vis=args.sub_vis, add_back=True)
  File "/content/EasyMocap/easymocap/dataset/mv1pmf.py", line 47, in vis_smpl
    self.writer.vis_smpl(render_data, images, cameras, outname, add_back=add_back)
  File "/content/EasyMocap/easymocap/mytools/writer.py", line 72, in vis_smpl
    from ..visualize.renderer import Renderer
  File "/content/EasyMocap/easymocap/visualize/renderer.py", line 4, in <module>
    import pyrender
ModuleNotFoundError: No module named 'pyrender'
/content

**Comment by chingswy** [comment]
Please run
```bash
pip install pyrender
```

**Comment by codesoft00** [comment]
Solved this problem.
