### ISSUE TITLE
No module named 'easymocap.estimator.openpose_wrapper'

### ISSUE THREAD

**Issue by puppet101** [zju3dv/EasyMocap#187]
I met this error when extracting keypoints, maybe the  file  'openpose_wrapper' is missing~  Thank you!

**Comment by abuklea** [comment]
I'm also getting this error and can't find any information on fixing it... can I please get some help here?
Thank you!!

**Comment by chingswy** [comment]
Fix it.

**Comment by puppet101** [comment]
Great, thank you!
