### ISSUE TITLE
ImportError: cannot import name 'CfgNode' from 'easymocap.config'

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/EasyMocap#189]
Hello. 
I tried tot run the monocular example, and followed the quick start instruction. Everything seems that installed correctly, but when running,  this command

python apps/demo/mocap.py D:/MOCAP/Easymocap0.2_v1/EasyMocap/0_videos/1v1p/videos/0+000553+000965.mp4 --work internet

I've got this error
(easymocap) D:\MOCAP\Easymocap0.2_v1\EasyMocap>python apps/demo/mocap.py D:/MOCAP/Easymocap0.2_v1/EasyMocap/0_videos/1v1p/videos/0+000553+000965.mp4 --work internet
Traceback (most recent call last):
  File "D:\MOCAP\Easymocap0.2_v1\EasyMocap\apps\demo\mocap.py", line 4, in <module>
    from easymocap.config import Config, CfgNode
ImportError: cannot import name 'CfgNode' from 'easymocap.config' (c:\mocap\easymocap-master\easymocap\config\__init__.py)

Do you know what could be wrong?

**Comment by carlosedubarreto** [comment]
I just noticed the problem, the path seems to be hard coded
![image](https://user-images.githubusercontent.com/4061130/186095572-4f381b9b-06d4-4abc-a3e9-65b75681fcda.png)

**Comment by carlosedubarreto** [comment]
one notice for people that may have the same problem, move the easymocap folder do c:\mocap\easymocap-master and it will work.

I had lots of other problems but watching the errors was not that difficult to fix (if you have some python experience)

**Comment by chingswy** [comment]
Hello, @carlosedubarreto , have you run `python3 setup.py develop` in the new folder? The easymocap maybe link to the old folder.

**Comment by carlosedubarreto** [comment]
That is odd. I ran the command on a new virtual enviroment.
Maybe I have some configuration on somewhere I dont remember 😅
