### ISSUE TITLE
Error converting to BVH (TypeError: string indices must be integers)

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/EasyMocap#190]
when I run the script to convert to bvh from the monocular solution I have this error. Can you help with this problem?

below is the screenshot
![image](https://user-images.githubusercontent.com/4061130/186110521-003fcd7c-24c2-4d9f-9d41-7b04c2c94d23.png)

**Comment by carlosedubarreto** [comment]
ALso found where to fix.
On the read_SMPL change this

![image](https://user-images.githubusercontent.com/4061130/186118151-2341bf0f-5450-49ba-9917-736adf09b879.png)

**Comment by chingswy** [comment]
Sorry for that, I have fixed it.

**Comment by carlosedubarreto** [comment]
thanks.
BTW you guys are rocking on this new version 👏
