### ISSUE TITLE
FileNotFoundError: .../lib/python3.9/site-packages/easymocap-0.2-py3.9.egg/easymocap/dataset/smpl_vert_sym.txt not found

### ISSUE THREAD

**Issue by duongnt** [zju3dv/EasyMocap#191]
Looks like this file is missing?

**Comment by duongnt** [comment]
looks like a pyenv problem.

**Comment by YaoBeiji** [comment]
lib\site-packages\easymocap-0.2.1-py3.7.egg\easymocap\dataset\smpl_vert_sym.txt not found.

**Comment by chingswy** [comment]
Please use `python3 setup.py develop` to install.
