### ISSUE TITLE
\\output-smpl-3d\\smplmesh

### ISSUE THREAD

**Issue by Vinayky86** [zju3dv/EasyMocap#192]
Hello thanks for this amazing Development..!!

I am trying Monocular internet tracking and facing this error..
![monocular ](https://user-images.githubusercontent.com/105794090/186350597-09f689ea-671a-495d-9350-374f17f47e7c.png)
.

**Comment by chingswy** [comment]
Hello, it seems that you don't install the `torch` with `cuda`

**Comment by Vinayky86** [comment]
oh..thanks for you quick reply, I'm going to try and will update here thank a lot

**Comment by Vinayky86** [comment]
Now it is working with no issue.
I'm using this 
conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch

thanks
