### ISSUE TITLE
run Visualization: the number of human exceeds!

### ISSUE THREAD

**Issue by Lruidong** [zju3dv/EasyMocap#196]
hi，i have a probmel. my visualizer show some irregular skeletons with only send one  .josn file. as folow is my error and cfg file
> vie_server.py

```(l_easymocap) lrd@rtx3090-Super-Server:~/data/lrd/easymocap_filer/EasyMocap$ python3 apps/vis/vis_server.py --cfg config/vis3d/o3d_scene.yml 
[Info] capture the screen to /home/lrd/data/lrd/easymocap_filer/vis3d/output/skel-body25
[Vis Info] [0 0 0], x: [1 0 0], y: [0 1 0]
[Info] server start
[Info] Connect: ('127.0.0.1', 55218)
[Error] the number of human exceeds!
[Info] Disonnect: ('127.0.0.1', 55218)
[Error] the number of human exceeds!
[Error] the number of human exceeds!
[Error] the number of human exceeds!
[Error] the number of human exceeds!
-> [forward             ]: 399.2ms
-> [set vertices        ]:   2.1ms
-> [update geometry     ]:  73.5ms
-> [capture             ]:  41.9ms
```

> vis_client.py

`python3 apps/vis/vis_client.py --path /home/lrd/data/lrd/easymocap_filer/000000.json --host 127.0.0.1 --port 9999`

> o3d_scene.yml
only modify against `python3 apps/vis/vis_server.py --cfg config/vis3d/o3d_scene.yml write True out ${vis}/output/skel-body25 camera.cz 3. camera.cy 0.5`
```
#write: False 
write: True
#out: 'none' 
out: '/home/lrd/data/lrd/easymocap_filer/vis3d/output/skel-body25'

camera:
  phi: 0
  theta: -30
  cx: 0.
  #cy: 0.5
  cy: 0. 
  cz: 6. 
  #cz: 3.
```

> o3dwrapper.py
```
def create_coord(camera = [0,0,0], radius=1, scale=1):
    camera_frame = TriangleMesh.create_coordinate_frame(
            size=radius, origin=camera)
    camera_frame.scale(scale,np.array([0,0 ,0])) #125 
    return camera_frame
```
![image](https://user-images.githubusercontent.com/48819558/189255379-790af10b-21b8-4f74-ae8f-2faeb53a22cb.png)

**Comment by Lruidong** [comment]
send _smpl/keypoints3d_ ,it work. send _smpl/keypoints3d/000000.json_ ,it error.why? How do I make it work？

**Comment by chingswy** [comment]
Hello, the `vis_client.py`assume you give a folder instead of a file.

**Comment by Lruidong** [comment]
thanks.
