### ISSUE TITLE
Openpose wrapper creating invalid json files at annots

### ISSUE THREAD

**Issue by ferhatsb** [zju3dv/EasyMocap#198]
Hi, 

This is probably Windows specific.

The annots created by  `estimator/openpose_wrapper.py` creates json files as;
```json
{
    "filename": "images\1\000000.jpg",
    "height": 1024,
    "width": 1024,
    "annots": [ ],
    "isKeyframe": false
}
```
via `convert_from_openpose` calling ` save_annot` at `annotator/file_utils.py`. 

filename field is resolved as "images\\\\1\\\\000000.jpg" (see double backslashes) however `print(out_text, file=open(file, 'w'))` removes escapes like new lines but also double backslashes. As you can see single backslash is alone escape character at json so output file is invalid and you can not processes them.

Json dump can not be used due to `file_utils.annot2string` creating string with new lines etc.

To prevent the issue I have eventually added another `elif` with condition filename and doubled the double backslashes to `annot2string`. 

```python
 if key != 'annots':
            if key == 'isKeyframe':
                res = '"{}": {}'.format(key, tobool(value))
            elif key == 'filename':
                res = '"{}": "{}",'.format(key, value.replace('\\', "\\\\"))
            elif isinstance(value, str):
                res = '"{}": "{}",'.format(key, value)
            elif isinstance(value, bool):
```

Now it creates as `"filename":"images\\\\1\\\\000000.jpg"....``

**Comment by chingswy** [comment]
Thank you, I will update this.

**Comment by chingswy** [comment]
Fix it.
