### ISSUE TITLE
iMocap code is not available

### ISSUE THREAD

**Issue by fabienbaradel** [zju3dv/EasyMocap#202]
Hi,
I am interested about the code release of your paper "Motion Capture from Internet Videos" but I cannot find it in your repo.
When do you plan to release it?
Thanks,

**Comment by NewCoderQ** [comment]
You can find it [here](https://chingswy.github.io/easymocap-public-doc/quickstart/quickstart.html#demo-on-monocular-videos).

**Comment by fabienbaradel** [comment]
Amazing thanks a lot! :)

**Comment by fabienbaradel** [comment]
Thanks @NewCoderQ , but I am looking for the method presented in the paper "Motion Capture from Internet Videos" with multiple videos of the same event and uncalibrated/asynchronized cameras. And it seems that the method is not available on the link you shared..
Am i doing something wrong?

**Comment by chingswy** [comment]
This part is not available now. You can use the current released monocular method.
