### ISSUE TITLE
auto_track keep creating new pid

### ISSUE THREAD

**Issue by yqtl** [zju3dv/EasyMocap#205]
Hi,
Thank you for the work! I have a question:
For a video sequence with two persons, I followed the mvmp procedure, and until run the app/demo/auto_track.py, the number of detected person is below 2.
But after running the auto_track, in output-track/keypoints3d, the id increases to more than 30.
Do you have any suggestions how to limit this?
Thanks.

**Comment by chingswy** [comment]
The number of the id doesn't affect the results. You can just ignore it.

**Comment by chingswy** [comment]
Hello, this is a hyper-parameters for tracking. You can use this locally.

**Comment by raflitp** [comment]
Hi ! Did you find the cause and the solve to this case ??

**Comment by yqtl** [comment]
> Hi ! Did you find the cause and the solve to this case ??

Hi,

I am not working on this for a while. Probably there is update on master for that fix, or have you tried to increase window size?

**Comment by raflitp** [comment]
> > Hi ! Did you find the cause and the solve to this case ??
> 
> Hi,
> 
> I am not working on this for a while. Probably there is update on master for that fix, or have you tried to increase window size?

Hi thanks for the reply, I've tried to increase the window_size but the outcome it give an error said something about SVT so I can't put it more than 15 not sure what it is, haven't figure out the cause for this. And there's no fix in the master about this
