### ISSUE TITLE
About yolo-hrnet mode 2d point detection 

### ISSUE THREAD

**Issue by Taylorminer** [zju3dv/EasyMocap#206]
Thanks for your work! When I detect the 2d point with yolo-hrnet mode. 
It shows:
`0: 0it [00:00, ?it/s]
1: 0it [00:00, ?it/s]
2: 0it [00:00, ?it/s]`
And the images folder is empty. I wonder know the yolo4.weights file is which on in https://github.com/AlexeyAB/darknet/wiki/YOLOv4-model-zoo. Can you help me ?

**Comment by chingswy** [comment]
This [file](https://drive.google.com/open?id=1L-SO373Udc9tPz5yLkgti5IAXFboVhUt)

**Comment by stevechaw** [comment]
How to detect 2D points with yolo-hrnet, I follow the Install.md, but I get raise NotImplementedError

**Comment by stevechaw** [comment]
> 

Thanks for your reply, I find the code!

**Comment by Vishnu-bhat** [comment]
can't i use python scripts/preprocess/extract_video.py 0_input/project --mode yolo-hrnet
its not working ...its saying that  cannot import name 'Detector' from 'easymocap.estimator.yolohrnet_wrapper'
