### ISSUE TITLE
Calibration example

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/EasyMocap#21]
Can you share the calibration footage?

I tried make the calibration of my own footage,but it was not working.
I would like to test a footage that works, so I could compare and see what I'm doing wrong.

Can you share the calibration footage for intrinsic and extrinsic calibration?

If you can share the information on the camera used it would be also great, because I have a feeling that the type of camera can be the issue on my calibration tests.

Btw, now it much easier to do the calibration, you did an amazing job. Looks like it just need some tweaks

Thanks

**Comment by carlosedubarreto** [comment]
I'm fanally understanding this new version. and it is muuuuuuch better than v 0.1

My major 2 problems:
1 - better calibration... I saw that my camera 2 had a poor calibration, and that was easy to see vieweing the distorted pictures output. I think, the better, less distorted output we have, the better calibration we have done.
2 - the extrinsic calibration was no good, because the calibration script couldnt find the checkboard

From the pitcture below, I can see that now the calibration for the extrinsic worked

![000000](https://user-images.githubusercontent.com/4061130/115899465-266f9180-a435-11eb-93ae-959309b1138c.jpg)


Thanks a lot.... These last days were amazing trying easymocap, your new script made it much easier!!!!

**Comment by carlosedubarreto** [comment]
Also noticed some other thing....
Looks like my resolution  is not good enought to the calibration recognize correcly.
![image](https://user-images.githubusercontent.com/4061130/115916767-9db02000-a44b-11eb-9b66-4fe86bb2de19.png)

Here you can see that it messes a little bit.
I'm thinknig of doing this recognition manually. I think it can be a good solution.

I'll test and post the results here (i think tweaking the chessboard json is the way to do that)

I'm trying this solution because I dont want to use a higher resolution image (because of computational costs) and dont want to re-record the videos I did. this re-recording was the most time consuming part of the process.

**Comment by carlosedubarreto** [comment]
Doing the manual tweaks on the extrinsic calibration worked much better than I expected!!!!
Look at the result

https://user-images.githubusercontent.com/4061130/115925018-e4574780-a456-11eb-90bd-d0a80dd61a2f.mp4

**Comment by chingswy** [comment]
Good news! I'm very happy to see this code works!
If you want to calibrate the camera automatically, you should acquire a chessboard as large as possible.
By the way, this chessboard is not necessary if you can manually measure the length of the grid on the floor and label the correspondence points in the images. I will update this part later.

**Comment by carlosedubarreto** [comment]
That even more good news.
Thanks a lot for your time on this project.
