### ISSUE TITLE
Can't run a server

### ISSUE THREAD

**Issue by IshuoF** [zju3dv/EasyMocap#215]
Hi, I'm doing mvmp, and I try to visualize my result. However, the  visualization window doesn't show up.

AttributeError: 'VisOpen3DSocket' object has no attribute 'serversocket'

this ERROR message shows on my cmd winsows. is there any solution ?

**Comment by chingswy** [comment]
Hello, the visualization `vis_server.py` must run at a local computer with screen.

**Comment by IshuoF** [comment]
![image](https://user-images.githubusercontent.com/82537320/197396286-f22d8115-0829-4bbe-9fc7-9988f48c3552.png)

Yeah, I'm running the command on my computer. It shows same error message

**Comment by chingswy** [comment]
Can you paste the full log?

**Comment by IshuoF** [comment]
![image](https://user-images.githubusercontent.com/82537320/197396917-d43dbaa6-6cee-4782-9a8c-1cfa5b6a0033.png)

yes, here is

**Comment by chingswy** [comment]
Seems like the version bug.
Try to comment the `line 49` of `easymocap/visualize/o3dwrapper.py`.

**Comment by IshuoF** [comment]
Thank you a lot. It finally works.
