### ISSUE TITLE
Some confusion about the difference between the mocap with SMPL-X parameters

### ISSUE THREAD

**Issue by EAST-J** [zju3dv/EasyMocap#216]
In the [here](https://github.com/zju3dv/EasyMocap/blob/master/doc/02_output.md#attention-for-smplsmpl-x-users), you explained the difference between the $Rh$ with the global_orient in SMPL. I wonder what $R$ in the $V=RX(theta, beta)+T$ refers to? The matrix form of the $Rh$? And in the $R'@(RX + T) + T'$, These two $R$ have the same meaning? Or the latter $R$ refers to the matrix form of the global_orient parameters in the SMPL?

**Comment by chingswy** [comment]
Hello, the `R` refers to the matrix form of the `Rh`. Here we show how to transform the coordinates of the SMPL parameters, which is used in other projects like NeuralBody.

**Comment by EAST-J** [comment]
> Hello, the `R` refers to the matrix form of the `Rh`. Here we show how to transform the coordinates of the SMPL parameters, which is used in other projects like NeuralBody.

Thank for immediate reply, So the equation $R'@(RX + T) + T'$ are used for transforming the SMPL coordinate to world coordinate?

**Comment by chingswy** [comment]
No. `R, T` represent the global orientation and translation for transforming the SMPL coordinate to the world coordinate. `R', T'` are used to transform the parameter from one world coordinate to another world coordinate.
