### ISSUE TITLE
Using Easymocap commercially?

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/EasyMocap#22]
Thanks a lot for this amazing work.
I'm building an addon that makes easier to people import easymocap data inside blender, and some of the people that uses this addon do it for commercial work.

I wanted to ask if easymocap can be used commercially. so I can answer better the people that asks that.

**Comment by chingswy** [comment]
It seems that SMPL model can not be used commercially.

**Comment by carlosedubarreto** [comment]
The result of keypoint3d folder uses SMPL?
In the worst case cenario, I think that output would be enough.

**Comment by chingswy** [comment]
If you only use the results of simple triangulation, it's maybe OK.
