### ISSUE TITLE
How to get 2d data from 4-views without saving it as .json file also as input for triangulation？

### ISSUE THREAD

**Issue by LRuid** [zju3dv/EasyMocap#222]
hi! I want to make a real-time system using Easymocap. but I won't intermediate the data storage form.  What data structure should I use?  Can you help me?
目前我利用multiprocess模块4个进程去提取视频的图片，同时开一个进程去检测图片的keypoints，但是中间数据是以.json文件的形式储存的，我想让它在内存中存储使用之后就删除掉，同时4个视角的帧需要对应，然后去三角化。我该利用什么样的数据结构解决这个问题？能否指导我一下。感谢

**Comment by chingswy** [comment]
Recommend to use socket to send the `json` format informations.

**Comment by LRuid** [comment]
> Recommend using socket to send the `JSON` format information.

1.not save .json file. only send json format information using socket ?

**Comment by chingswy** [comment]
1. yes
2. You should understand these functions and just select the needed.

**Comment by LRuid** [comment]
> 1. yes
> 2. You should understand these functions and just select the needed.
1.yolo-hrnet can use now?
2.if can't use, i should how use openpose? 
`cmd = './build/examples/openpose/openpose.bin --image_dir {} --write_json {} --display 0'.format(image, keypoints)`
It saves .json file directly without pausing.How do I get 2d data without saving?Where to find references?

**Comment by LRuid** [comment]
i use yolo-hrnet to get 19 keypoints ，can it use body_25 to vis_3d？vis_3d only use output of openpose?

**Comment by LRuid** [comment]
i am using python's multiprocessing library.i run 4 process ,it not work ,output not memory .as follows ,my code and error. 

Then i run 2 process, it work . but i not specify GPU.` Auto-detecting all available GPUs...,`
What can I do to specify that process 1 uses GPU 0 and process 2 uses GPU 1?or other better ways to use openpose model. Please give me some reference . Thanks

```
from multiprocessing import Process
for i in range(4):
    p = Process(target=runing_openpose,args=(image_root,))
    p.start()
```
```
def runing_openpose(image_root):
    sys.path.append('/usr/local/python')
    from openpose import pyopenpose as op
    params = dict()
    params["model_folder"] = "MODELS"
    opWrapper = op.WrapperPython()
    opWrapper.configure(params)
    opWrapper.start()
    imagePaths = op.get_images_on_directory(image_root)
    for imagePath in imagePaths:
        datum = op.Datum()
        imageToProcess = cv2.imread(imagePath)
        datum.cvInputData = imageToProcess
        opWrapper.emplaceAndPop(op.VectorDatum([datum]))
        print("Body keypoints: \n" + str(datum.poseKeypoints))
```

> Starting OpenPose Python Wrapper...
> Starting OpenPose Python Wrapper...
> Starting OpenPose Python Wrapper...
> Starting OpenPose Python Wrapper...
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
> E1114 21:21:01.461006 21528 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.462309 21514 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.465152 21509 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.471258 21520 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.481060 21508 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.489166 21521 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.497902 21527 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.502249 21509 common.cpp:121] Cannot create Curand generator. Curand won't be available.
> E1114 21:21:01.505977 21508 common.cpp:121] Cannot create Curand generator. Curand won't be available.
> E1114 21:21:01.514278 21516 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> E1114 21:21:01.516794 21520 common.cpp:121] Cannot create Curand generator. Curand won't be available.
> E1114 21:21:01.523866 21528 common.cpp:121] Cannot create Curand generator. Curand won't be available.
> E1114 21:21:01.531649 21514 common.cpp:121] Cannot create Curand generator. Curand won't be available.
> F1114 21:21:01.532974 21508 syncedmem.hpp:22] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

*** Check failure stack trace: ***
    @     0x7f64eab4c0cd  google::LogMessage::Fail()
    @     0x7f64eab4df33  google::LogMessage::SendToLog()
    @     0x7f64eab4bc28  google::LogMessage::Flush()



> Starting OpenPose Python Wrapper...
> Starting OpenPose Python Wrapper...
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
> Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
Body keypoints: 
[[[4.5617700e+02 2.5491418e+02 9.7750974e-01]
  [5.0641528e+02 2.9397977e+02 8.1965744e-01]
........

**Comment by chingswy** [comment]
You can use `CUDA_VISIBLE_DEVICES=0 && openpose.bin xxx`.

**Comment by Sherlock0606** [comment]
> hi! I want to make a real-time system using Easymocap. but I won't intermediate the data storage form. What data structure should I use? Can you help me? 目前我利用multiprocess模块4个进程去提取视频的图片，同时开一个进程去检测图片的keypoints，但是中间数据是以.json文件的形式储存的，我想让它在内存中存储使用之后就删除掉，同时4个视角的帧需要对应，然后去三角化。我该利用什么样的数据结构解决这个问题？能否指导我一下。感谢

请问你现在解决了这个问题了吗

**Comment by LRuid** [comment]
> > hi! I want to make a real-time system using Easymocap. but I won't intermediate the data storage form. What data structure should I use? Can you help me? 目前我利用multiprocess模块4个进程去提取视频的图片，同时开一个进程去检测图片的keypoints，但是中间数据是以.json文件的形式储存的，我想让它在内存中存储使用之后就删除掉，同时4个视角的帧需要对应，然后去三角化。我该利用什么样的数据结构解决这个问题？能否指导我一下。感谢
> 
> 请问你现在解决了这个问题了吗

开了4个队列。然后不保存json，但是模型只能开一个。实时的话可能需要自己部署模型，使输入变成4个，然后直接输出4个，最后三角化

**Comment by Sherlock0606** [comment]
> > > hi! I want to make a real-time system using Easymocap. but I won't intermediate the data storage form. What data structure should I use? Can you help me? 目前我利用multiprocess模块4个进程去提取视频的图片，同时开一个进程去检测图片的keypoints，但是中间数据是以.json文件的形式储存的，我想让它在内存中存储使用之后就删除掉，同时4个视角的帧需要对应，然后去三角化。我该利用什么样的数据结构解决这个问题？能否指导我一下。感谢
> > 
> > 
> > 请问你现在解决了这个问题了吗
> 
> 开了4个队列。然后不保存json，但是模型只能开一个。实时的话可能需要自己部署模型，使输入变成4个，然后直接输出4个，最后三角化

感谢
