### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml' -- Quickstart demo for multiple cameras

### ISSUE THREAD

**Issue by domattioli** [zju3dv/EasyMocap#223]
I installed the easy mocap library using [these instructions](https://chingswy.github.io/easymocap-public-doc/install/install.html#install-easymocap-quickly), and `conda list` confirms a succesful installation:
```
# Name                    Version                   Build  Channel
easymocap                 0.2                       dev_0    <develop>
```

But running the mocap.py demo line in the [Quickstart demo for multiple cameras](https://chingswy.github.io/easymocap-public-doc/quickstart/quickstart.html#demo-for-motion-capture) yields a ModuleNotFoundError pointing to the easymocap configuration:
```
/home/.../EasyMocap$ python3 apps/demo/mocap.py ${data} --work lightstage-dense-smplh --subs_vis 01 --ranges 0 800 1
Traceback (most recent call last):
  File "/home/.../EasyMocap/apps/demo/mocap.py", line 4, in <module>
    from easymocap.config import Config, CfgNode
  File "/home/.../EasyMocap/easymocap/config/__init__.py", line 8, in <module>
    from .yacs import CfgNode
  File "/home/.../EasyMocap/easymocap/config/yacs.py", line 28, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

My conda environment includes `yaml = 0.2.5`. Is the easymocap module misconfigured in my environment?

**Comment by chingswy** [comment]
Try to install it with `pip install PyYAML`

**Comment by domattioli** [comment]
No luck -- `Requirement already satisfied: PyYAML`
[terminal_printout-conda_list.txt](https://github.com/zju3dv/EasyMocap/files/9910769/terminal_printout-conda_list.txt)

**Comment by chingswy** [comment]
It's weird. Can you run `import yaml` in a new python terminal?

**Comment by chingswy** [comment]
Closed as no response.
