### ISSUE TITLE
2-people monocular demo

### ISSUE THREAD

**Issue by tommyshelby4** [zju3dv/EasyMocap#224]
I try to run the monocular demo using a 2-people video as input and it runs fine but the SMPL fitting is only performed for the person closer to the camera. Is it possible that SMPL fitting is performed for both people in the scene?

**Comment by chingswy** [comment]
We don't support it in current version. We will support it later.

**Comment by tommyshelby4** [comment]
Thank you. One more question for the monocular demo. I am trying to run it using the SMPLX model instead of the baseline SMPL model but I am facing issues. I have created a .yml for the model entry in the **mocap_index.yml** file, which I attach. I believe I need to edit the first line of the file but I cannot figure out which model class to use for the SMPLX setting. 
`module: "easymocap.body_model.smplxSMPLlayer"
args:
  model_path: "data/smplx/smplx/SMPLX_NEUTRAL.pkl" 
  model_type: "smplx"
  device: "cuda"
  regressor_path: "data/smplx/J_regressor_body25_smplx.txt"
  use_pose_blending: True
  use_shape_blending: True
  use_lbs: True`

**Comment by chingswy** [comment]
Hello, we don't support smplx now. It's difficult to make it compatible.
