### ISSUE TITLE
realtime visualization error

### ISSUE THREAD

**Issue by Taylorminer** [zju3dv/EasyMocap#226]
When I run :"python3 apps/vis/vis_server.py --cfg config/vis3d/o3d_scene.yml write True out ${vis}/output/skel-multi camera.cz 3. camera.cy 0.5".But,there is a bug:

usage: vis_server.py [-h] [--cfg CFG] [--local_rank LOCAL_RANK] [--debug]
                     [--opts OPTS [OPTS ...]]
vis_server.py: error: unrecognized arguments: write True out data/mvpose/class/test/output/skel-multi camera.cz 3. camera.cy 0.5
Can you help me?

**Comment by chingswy** [comment]
```bash
python3 apps/vis/vis_server.py --cfg config/vis3d/o3d_scene.yml --opts write True out ${vis}/output/skel-multi camera.cz 3. camera.cy 0.5
```

**Comment by chingswy** [comment]
Reopen it if any questions.
