### ISSUE TITLE
How to get total 137 openpose keypoints from SMPLX vertices regression?

### ISSUE THREAD

**Issue by Alex-JYJ** [zju3dv/EasyMocap#232]
The file `J_regressor_body25_smplx.txt` you provided is $118\times 10475$, while openpose output $137$ keypoints. How can I regress the total $137$ keypoints from SMPLX vertices? Could you please provide another version of `J_regressor_body25_smplx.txt` that is $137\times 10475$ or some advice about how to generate this file? Thanks a lot!

**Comment by chingswy** [comment]
Hello, we drop the keypoints of the contour of face. [Previous work](https://github.com/vchoutas/smplx/blob/main/smplx/lbs.py#L30) use a function to find the dynamic landmarks insteard of a simple `J_regressor`. So we can't integrate these points.

**Comment by Alex-JYJ** [comment]
Thank you for your quick reply! I'll go and learn from that work.
