### ISSUE TITLE
About the losses in optimizing SMPL parameters

### ISSUE THREAD

**Issue by siyuan-peng** [zju3dv/EasyMocap#237]
Hello there, I am reading your code about fitting SMPL pose parameters from 3D BODY25 joints. 
I noticed that you have defined 5 types of losses (LossKeypoints3D, LossSmoothBodyMean, LossSmoothPoses, LossRegPoses, LossInit). 
I understand what the first 3 losses are doing, but I'm a little confused about the latter two. 
Could you please explain what they mean, and why they help with optimization?

More specifically, for LosRegPoses, how is dividing the square of pose parameters by nFrames help with optimization?
For LossInit, why should we penalize the distance to the initial pose?

Thanks!

**Comment by chingswy** [comment]
We often divide the loss by `number of frames` as the length of the sequence is various.
We penalize the distance to the initial pose to make the optimization more robust.

**Comment by siyuan-peng** [comment]
> We often divide the loss by `number of frames` as the length of the sequence is various. We penalize the distance to the initial pose to make the optimization more robust.

What about LossRegPosesZero? What do SMPL_POSES_ZERO_INDEX and SMPL_JOINT_ZERO_INDEX mean? 
I'm guessing that they are trying to embed prior knowledge about human skeleton into the optimization process, i.e. penalizing impossible joint rotations. But I'm not sure.

Thank you again for your great work!

**Comment by chingswy** [comment]
Yes, you are right.
