### ISSUE TITLE
请教一下，您的标定板是如何购买/制作的？

### ISSUE THREAD

**Issue by peiyubin** [zju3dv/EasyMocap#241]
感谢您的开源分享！
我想问您一下，项目中进行标定时使用的标定板是如何购买/制作的？我还没有见过如此大块的标定板哈哈= =。
如果我只是搞一块不错的平直模板然后贴上自己打印的棋盘格，会影响标定的效果吗？
期待您的指导。

**Comment by chingswy** [comment]
你好，我是使用的打印店的KT板，材质比较软，你可以使用硬一点的木板，对最终结果影响不大。

**Comment by peiyubin** [comment]
> 你好，我是使用的打印店的KT板，材质比较软，你可以使用硬一点的木板，对最终结果影响不大。

好的，谢谢您~

**Comment by LRuid** [comment]
> 你好，我是使用的打印店的KT板，材质比较软，你可以使用硬一点的木板，对最终结果影响不大。

您好，有没有拍好的标定板数据集？我因为一些原因无法搭建拍摄环境。我想先测试一下标定的代码。
