### ISSUE TITLE
question about "unproj" on 1v1p mode

### ISSUE THREAD

**Issue by skcskc7** [zju3dv/EasyMocap#242]
Hi,

I want to know about "unrproj" parameters in cfg_exp.yml on 1v1p mode.

I noticed that changing the value of the unproj parameter from True to False and running the optimizer speeds up the extraction.

![image](https://user-images.githubusercontent.com/22520046/206209941-580d3bf8-93a2-4acc-bc6e-6dd1d6cecc71.png)

What does "unrproj" mean and how does it affect pose extraction results?

**Comment by chingswy** [comment]
Hello, the `unproj` means unproject the 2D  keypoints from image sapce to camera space.
