### ISSUE TITLE
Bad fitting result for MANO

### ISSUE THREAD

**Issue by EAST-J** [zju3dv/EasyMocap#261]
Hi, I'm using the tool to do the motion capture for hand, but some results seem very strange. Here are some examples.
![000000](https://user-images.githubusercontent.com/51024280/213452407-d1761d25-5d86-44f5-aa68-7c65b30aa6a9.jpg)
![000000_](https://user-images.githubusercontent.com/51024280/213452426-b18d23e9-009f-4491-be98-b393eaa0dc8a.jpg)
The bad results may be caused by hand-object interaction, I tried to modify the [weight](https://github.com/zju3dv/EasyMocap/blob/7a80646902420692dcb2376abbd23ec5d0138d6d/easymocap/pipeline/weight.py#L12) . But there is no obvious effects. Could you give some advice to improve the result?

**Comment by chingswy** [comment]
Obtaining more accurate 2D estimations of the hand keypoints can greatly enhance the tracking performance. If possible, try using more advanced or precise methods for 2D hand pose estimation. This will provide a stronger foundation for the subsequent tracking process.

**Comment by lxiaan** [comment]
hi, could i know how you calibrated your cameras? I have a setup similar to yours. Currently I put a two sided chessboard in the center and run the calibration scripts, but that seems to have some issues. I've tried manually annotating the chessboard for the cameras underneath so the chessboard keypoints detected by the bottom cameras align with the chessboard keypoints for the cameras above, but that doesnt work either.

**Comment by EAST-J** [comment]
> I have a setup similar to yours. Currently I put a two sided chessboard in the center and run the calibration scripts, but that seems to have some issues. I've tried manually annotating the chessboard for the cameras underneath so the chessboard keypoints detected by the bottom cameras align with the chessboard keypoints for the cameras above, but that doesnt work either.

The video sequence above is from the DexYCB datasets with calibrated cameras, I do not calibrate the cameras by myself.

**Comment by lxiaan** [comment]
got it, thanks!
