### ISSUE TITLE
Can you explain the princple of skeleton visualization？

### ISSUE THREAD

**Issue by jeffreyking23** [zju3dv/EasyMocap#266]
Hi，I read the code about visualization and found that skeleton is changed from sphere_faces_20.txt and sphere_vertices_20.txt。
Can you clarify how to get the skeleton from a sphere and 3D keypoints coordinates？

**Comment by raypine** [comment]
The goal is to transform the canonical sphere at the origin to an ellipsoid connecting two adjacent keypoints (a bone).
The transformation mat can be calculated via IK as in [here](https://github.com/zju3dv/EasyMocap/blob/2544c970ef7dce5cfc0e1f26f903a75dc4007963/easymocap/visualize/skelmodel.py#L14). P.S., rotmat.T seems useless.
