### ISSUE TITLE
i have this problem after replace model.py &  mvp1.py files in esaymocap folder .

### ISSUE THREAD

**Issue by elakki1** [zju3dv/EasyMocap#27]
![06C7A617-322E-49E8-B428-1121C05EC765](https://user-images.githubusercontent.com/85573145/121217082-215c8980-c89f-11eb-80b9-56eebf4c8a84.jpeg)
@carlosedubarreto  

`

**Comment by carlosedubarreto** [comment]
try to run the code and add in the end 

`--end 320`

Looks like there is a problem at frame 324 that is throwing the error.

**Comment by elakki1** [comment]
i have 2 mobiles , one is android another one is android. so i use these
mobiles for  creating calibration videos.

**Comment by carlosedubarreto** [comment]
You should have no problem using you android phones. You just have to calibrate it.
Di you have any results using the `--end 320` option?
