### ISSUE TITLE
How to convert standard SMPL to EasyMocap format?

### ISSUE THREAD

**Issue by xiyichen** [zju3dv/EasyMocap#271]
To be precise, how can I obtain the Rh and Th from the standard SMPL outputs from human mesh recovery methods (e.g. PARE, VIBE)?

**Comment by Dipankar1997161** [comment]
> To be precise, how can I obtain the Rh and Th from the standard SMPL outputs from human mesh recovery methods (e.g. PARE, VIBE)?

Hey, @xiyichen, did you figure out how to achieve it? If so could you share it
