### ISSUE TITLE
why def batch_triangulate()  compute Au and Av using Au = conf * (uP2 - P0) insteadf of Au =(uP2 - P0)？what is meaning of conf?

### ISSUE THREAD

**Issue by Ruid6** [zju3dv/EasyMocap#278]
def batch_triangulate() in reconstruction,py ,line 66-68,Does this increase accuracy？i dont understand.
![image](https://user-images.githubusercontent.com/48819558/222435435-478e1dec-2775-4b80-98bd-9047ffe49a2c.png)

**Comment by chingswy** [comment]
Yes, this can consider the `confidence` of each joint at each view.

**Comment by chingswy** [comment]
You can check [this work](https://arxiv.org/abs/1905.05754)
