### ISSUE TITLE
Rvec values For Human3.6m? What is Rvec in Extrinsic

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/EasyMocap#279]
Thanks for the work on EasyMocap!

I was able to retrieve all the camera parameters from the  metadata.xml of h36m dataset, however, When I checked the extri.yml format here, It includes 3 vectors R_(3,1), (3,3)Rotation matrix and 1,3(Translation).
What could be the rvec value here?

Will it be simply like:
**rvec = cv2.Rodrigues('R')[0]**

**With the R being a 3x3 matrix from the camera params? Or will it be something else?**

I look forward to know about this, since It is necessary to generate the SMPL paramters too. 
Thank you

**Comment by chingswy** [comment]
Just use this:
```bash
from easymocap.mytools.camera_utils import write_camera
```

**Comment by Dipankar1997161** [comment]
> Just use this:
> 
> ```shell
> from easymocap.mytools.camera_utils import write_camera
> ```

I mean, I am using  public dataset, moreover, human3.6m, so I cannot calibrate it manually. 

How will that python file still be useful then?  Just pass the images or videos of h36m and we shall get the output? 

Could you say

**Comment by chingswy** [comment]
I know what you mean. If you get the `K, dist, R, T`, just use this function to store the `intri.yml`, `extri.yml` as EasyMocap formats.

**Comment by Dipankar1997161** [comment]
> I know what you mean. If you get the `K, dist, R, T`, just use this function to store the `intri.yml`, `extri.yml` as EasyMocap formats.

Actually yes, I have retrived the K, dist, R and T for all cameras of h3.6m xml file, however, they are in json format.  
So for using the the Write_camera function, I need to create 2 yml files of intri and extri And pass that as an input to the function, right?

**def write_camera(camera, path):**

This line uses 2 inputs, path is thr corresponding location of the yml files. And what about the camera? What should that include?  

Sorry, am new into this field so asking for clarity

**Comment by chingswy** [comment]
I have updated a script to clarify this;
```bash
python3 scripts/dataset/pre_h36m_camera.py path/to/your/H36M_ROOT output/path
```

**Comment by Dipankar1997161** [comment]
Thank you for that script. I shall dive into it. 
One more question, 
It's mentioned for retrieving the SMPL parameters from EasyMocap, we need the OpenPose, which is kinda hard to install on Linux..

Is there an alternative that I can use in this case? My ultimate goal is to use NeuralBody for Synthesis,  so I need the SMPL parameters for the videos

**Comment by chingswy** [comment]
You can use `yolo-hrnet` for 2D pose estimation.
