### ISSUE TITLE
Errors on Linux (Ubuntu) when running quickstart example

### ISSUE THREAD

**Issue by FrankSpalteholz** [zju3dv/EasyMocap#28]
First of all thank you very much for this great repo! When trying the quick-start example i'm facing some errors where i'd really appreciate some help: 

1. After processing the videos:

Traceback (most recent call last):
  File "scripts/preprocess/extract_video.py", line 267, in <module>
    join(args.path, 'openpose_render', sub), args)
  File "scripts/preprocess/extract_video.py", line 56, in extract_2d
    os.chdir(openpose)
FileNotFoundError: [Errno 2] No such file or directory: '/media/qing/Project/openpose'

2. After triangulation:

-> [Optimize global RT  ]:   0.9ms
Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 109, in <module>
    mv1pmf_smpl(dataset, args)
  File "apps/demo/mv1p.py", line 71, in mv1pmf_smpl
    weight_shape=weight_shape, weight_pose=weight_pose)
  File "/home/frankfurt/dev/EasyMocap/easymocap/pipeline/basic.py", line 77, in smpl_from_keypoints3d2d
    params = multi_stage_optimize(body_model, params, kp3ds, kp2ds, bboxes, Pall, weight_pose, cfg)
  File "/home/frankfurt/dev/EasyMocap/easymocap/pipeline/basic.py", line 18, in multi_stage_optimize
    params = optimizePose3D(body_model, params, kp3ds, weight=weight, cfg=cfg)
  File "/home/frankfurt/dev/EasyMocap/easymocap/pyfitting/optimize_simple.py", line 301, in optimizePose3D
    params = _optimizeSMPL(body_model, params, prepare_funcs, postprocess_funcs, loss_funcs, weight_loss=weight, cfg=cfg)
  File "/home/frankfurt/dev/EasyMocap/easymocap/pyfitting/optimize_simple.py", line 246, in _optimizeSMPL
    final_loss = fitting.run_fitting(optimizer, closure, opt_params)
  File "/home/frankfurt/dev/EasyMocap/easymocap/pyfitting/optimize.py", line 38, in run_fitting
    loss = optimizer.step(closure)
  File "/home/frankfurt/dev/EasyMocap/easymocap/pyfitting/lbfgs.py", line 307, in step
    orig_loss = closure()
  File "/home/frankfurt/dev/EasyMocap/easymocap/pyfitting/optimize_simple.py", line 227, in closure
    new_params = func(new_params)
  File "/home/frankfurt/dev/EasyMocap/easymocap/pyfitting/optimize_simple.py", line 121, in interp_func
    params[key][nf] = interp(params[key][left], params[key][right], 1-weight, key=key)
IndexError: index 800 is out of bounds for dimension 0 with size 800

Then triangulation runs a second time:
(with same error like above) and this one:

Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 108, in <module>
    mv1pmf_skel(dataset, check_repro=True, args=args)
  File "apps/demo/mv1p.py", line 35, in mv1pmf_skel
    images, annots = dataset[nf]
  File "/home/frankfurt/dev/EasyMocap/easymocap/dataset/mv1pmf.py", line 73, in __getitem__
    annots = self.select_person(annots_all, index, self.pid)
  File "/home/frankfurt/dev/EasyMocap/easymocap/dataset/base.py", line 461, in select_person
    keypoints = np.zeros((self.config['nJoints'], 3))
KeyError: 'nJoints'

Thank you very much!

**Comment by chingswy** [comment]
> 
>     1. After processing the videos:
> 

Did you run this script on `zju-ls-feng.zip`?  
If not, you should install and specify the path by `--openpose <openpose_path>`.
If so, it doesn't need run OpenPose. Can you show me the folder structure?

**Comment by FrankSpalteholz** [comment]
Hi Quing, and thank you for the fast replay. Although you are were right (haven't copied the openpose-folder to my testdata-folder it gives me the same error. here is my folder structure:

![Screenshot from 2021-06-09 13-36-35](https://user-images.githubusercontent.com/15378424/121347697-c6bb4000-c927-11eb-8a90-5c879e2dc36c.png)

**Comment by chingswy** [comment]
Download the data with annotation [here](https://zjueducn-my.sharepoint.com/:u:/g/personal/s_q_zju_edu_cn/EQY9Am-Vni5Gs4WgfAgfIW0BKu4YeIcnaZhgjmpZDsQ6Pw?e=K06K77) and extract it. Then run:
```bash
data=<path/to/zju-ls-feng-annot>
python3 scripts/preprocess/extract_video.py ${data} --no2d
python3 apps/demo/mv1p.py ${data} --out ${data}/output/smpl --undis --vis_smpl
```

**Comment by FrankSpalteholz** [comment]
Thanks again. After following your advice and run the script i got this one:

cameras:  1 10 11 12 13 14 15 16 17 18 19 2 20 21 22 23 3 4 5 6 7 8 9

  Demo code for multiple views and one person:

    - Input : /home/frankfurt/dev/EasyMocap/data/testData => 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23
    - Output: /home/frankfurt/dev/EasyMocap/data/testData/output/smpl
    - Body  : smpl=>neutral, body25

triangulation: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 800/800 [00:04<00:00, 175.61it/s]
dump: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 800/800 [00:00<00:00, 8895.38it/s]
loading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 800/800 [00:03<00:00, 212.35it/s]
Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 109, in <module>
    mv1pmf_smpl(dataset, args)
  File "apps/demo/mv1p.py", line 68, in mv1pmf_smpl
    body_model = load_model(gender=args.gender, model_type=args.model)
  File "/home/frankfurt/dev/EasyMocap/easymocap/smplmodel/body_param.py", line 50, in load_model
    regressor_path=reg_path)
  File "/home/frankfurt/dev/EasyMocap/easymocap/smplmodel/body_model.py", line 64, in __init__
    self.faces = data['f']
KeyError: 'f'

**Comment by chingswy** [comment]
Can you print `data.keys()` before this line?
> "easymocap/smplmodel/body_model.py", line 64,

**Comment by FrankSpalteholz** [comment]
loading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 800/800 [00:15<00:00, 52.62it/s]
-> dict_keys(['cam_t', 'poses', 'betas', 'focal_length'])
Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 109, in <module>
    mv1pmf_smpl(dataset, args)
  File "apps/demo/mv1p.py", line 68, in mv1pmf_smpl
    body_model = load_model(gender=args.gender, model_type=args.model)
  File "/home/frankfurt/dev/EasyMocap/easymocap/smplmodel/body_param.py", line 50, in load_model
    regressor_path=reg_path)
  File "/home/frankfurt/dev/EasyMocap/easymocap/smplmodel/body_model.py", line 65, in __init__
    self.faces = data['f']
KeyError: 'f'

**Comment by chingswy** [comment]
It's obvious that you used a wrong SMPL model. Please check it.

**Comment by FrankSpalteholz** [comment]
Thanks but i already wrote that you are using SMPL_FEMALE.pkl (also for NEUTRAL and MALE) but on the website you've mentioned there is no such model available with these names. I was downloading SMPL_python_v.1.0.0.zip (containing basicmodel_m_lbs_10_207_0_v1.0.0.pkl and basicModel_f_lbs_10_207_0_v1.0.0.pkl) and mpips-smplify_public_v2.zip (containing basicModel_neutral_lbs_10_207_0_v1.0.0.pkl) These are the ones i'm using (i've renamed them to SMPL_FEMALE.pkl etc to follow your naming-convention) but if these are not the correct ones where can i find them?
Thank you so much again for your help

**Comment by chingswy** [comment]
To check your model, run this:
```python
import pickle
with open('basicmodel_m_lbs_10_207_0_v1.0.0.pkl', 'rb') as f:
    model = pickle.load(f, encoding='latin1') 
    print(model.keys())
```
The output of mine is:
```bash
dict_keys(['J_regressor_prior', 'f', 'J_regressor', 'kintree_table', 'J', 'weights_prior', 'weights', 'vert_sym_idxs', 'posedirs', 'pose_training_info', 'bs_style', 'v_template', 'shapedirs', 'bs_type'])
```
You can set other gender when running the demo code:
```bash
python3 apps/demo/mv1p.py ${data} --out ${data}/output/smpl --undis --vis_smpl --gender male
python3 apps/demo/mv1p.py ${data} --out ${data}/output/smpl --undis --vis_smpl --gender female
```

**Comment by FrankSpalteholz** [comment]
Excellent ... my bad (of course) Thanks a lot for having so much patience with me!
