### ISSUE TITLE
Real-time motion capture capabilities

### ISSUE THREAD

**Issue by zzepphyyr** [zju3dv/EasyMocap#280]
Hi,

I am interested in using EasyMocap for real-time motion capture. I.e., live feed from cameras with real-time motion capture (no post processing).

Is this capability currently available? The documentation says: "3D Realtime visualization", but #131 suggests otherwise.

Any information would be greatly appreciated!

Thank you to the contributors for great software

**Comment by chingswy** [comment]
Hello, this `3D Reaaltime visualization` part is only for `visualization`. The software for real-time mocap is not public.

**Comment by zzepphyyr** [comment]
Thank you for the clarification
