### ISSUE TITLE
Are there any alternatives for low performance computer setup for EasyMocap?

### ISSUE THREAD

**Issue by edwardraymondhe** [zju3dv/EasyMocap#290]
Currently my laptop GPU is RTX3060 6GB, which was really not enough for training any model.
I'm quite new to tensorflow & pytorch, so don't know if it's possible to do any experiment for "Novel View Synthesis of Human Interactions from Sparse Multi-view Videos" on any online Jupyter-Platforms such as Google-Colab or Kaggle?

**Comment by chingswy** [comment]
Thank you for your inquiry. I’m sorry to hear that your GPU may not be sufficient to run our algorithm and that online platforms may not meet the computational requirements either. Our algorithm requires a significant amount of computational resources to run. I hope you understand.
