### ISSUE TITLE
3d skeleton / keypoints plot for zju-mocap 

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/EasyMocap#291]
@chingswy 
I hope you have a good day. 

From the last time, I have made advancements in my work, i have generated the top-view 3d reconstruction model for the zju-mocap dataset.  Your opinions helped a lot.

One additional thing that I want to do is, Keypoint/skeleton plotting on the 3d plane or even on images of the model. 

### In context of NEURAL BODY

**The params folder for a coreview subjects, consists of the array with : Rh, Th, Poses (24x3),  Shapes(10,)**

**The vertices folder consists of an array with size (6890,3**).

I believe- the poses are the Thetas in smpl which represent the Rotation of the joints in 3d. Shapes are the betas. Vertices is the j-regressor.

If that's the case, where are the 3d joint locations for coreview subjects?? 
Without these it's impossible to plot the points I suppose. Is there a way to retrive these 3d keypoints? 

 How do I plot the skeleton or atleast the 3d keypoints in the 3d space. If you could explain in a short way.

It would be really helpful.  Thank you once again 😁😁

**Comment by chingswy** [comment]
Yes, you are right.

**Comment by Dipankar1997161** [comment]
Thank you for the clarification,  I compared the Zju-mocap dataset that I have with the smpl format to understand properly because then I would try to plot the 3d skeleton in 3d plane without the mesh.

1. joints.npy in zju-mocap has a shape of (24,3) which is similar to the smpl joints.
2. poses in the Params folder are similar to the smpl_thetas which are of size 24,3 and represent the rotation of the 3d joints in space.
3. shapes in zju-mocap are the betas in smpl of size (10,)
4. Vertices is j_regressor
5. parents.npy is the kine_tree table
6. Rh and Th are the rotation in rodrigues and Th is the translation matrix for the 3d model in camera coordinates system.
7. The smpl_neutral.pkl model with the model ofc.

I guess that's all I would need to plot the smpl skeleton for zju-mocap.

How to actually plot the skeleton for 1 model frame of the reconstruction in neural_body.

Do you have a script which shows the plot? or any referral would also work for me. Most, of the papers I read stop after retrieving the Mesh. I just need to draw the skeleton.

I need the skeleton to use as the Ground Truth for my work along with the 3d reconstruction which I done.

Please let me know @chingswy 

Thank you for your help  and taking time to explain^^
