### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by AndreOliveira00** [zju3dv/EasyMocap#300]
I think there is an error in the link redirected by "visualization tutorial" in section "2. Recovering SMPL body model" -> "To visualize the results, see visualization tutorial" in EasyMocap/doc/mvmp.md.

It currently redirects to the link:
https://github.com/zju3dv/EasyMocap/blob/master/doc/doc/realtime_visualization.md

And I think it should be:
https://github.com/zju3dv/EasyMocap/blob/master/doc/realtime_visualization.md

**Comment by chingswy** [comment]
Thanks for pointing out this!
