### ISSUE TITLE
from numpy import bool, int, float, complex, object, unicode, str, nan, inf ImportError: cannot import name 'bool' from 'numpy' (C:\Users\C-RAIN\anaconda3\envs\easymocap\lib\site-packages\numpy\__init__.py)

### ISSUE THREAD

**Issue by chengFengOO** [zju3dv/EasyMocap#301]
![image](https://user-images.githubusercontent.com/131579551/233825915-995656c4-528c-4d16-9538-cf8aeba5dc06.png)

**Comment by chengFengOO** [comment]
Input python apps/demo/mocap.py 0_input/vky --work internet --ranges 150 600 1

**Comment by chingswy** [comment]
```bash
pip install git+https://github.com/mattloper/chumpy.git
```

**Comment by tleyden** [comment]
I ran into the same issue with numpy 1.24.3 and chumpy 0.70.  

Downgrading numpy to version 1.21.6 via:

```
pip install --force-reinstall "numpy==1.21.6"
``` 

seems to have fixed the issue
