### ISSUE TITLE
Expired link to dataset

### ISSUE THREAD

**Issue by AndreOliveira00** [zju3dv/EasyMocap#302]
Unfortunately it looks like the link shared in "EasyMocap/doc
/mvmp.md" -> "You can download our dataset here." is no longer available:
https://zjueducn-my.sharepoint.com/:u:/g/personal/s_q_zju_edu_cn/EZFGgpK2Y6RBkPbGvny_PC0BIS08qJvxGYEHYopjhHX_TQ?e=LY3pgm

Would it be possible to renew access?
Thanks!

**Comment by patrickESM** [comment]
+1

**Comment by AndreOliveira00** [comment]
Please can some one update the shared link as soon as possible?

**Comment by chingswy** [comment]
I will revised the `mvmp` code and dataset this week.
