### ISSUE TITLE
骨骼方向位置可否修复?

### ISSUE THREAD

**Issue by chengFengOO** [zju3dv/EasyMocap#304]
![image](https://user-images.githubusercontent.com/131579551/235313739-e0bc5f31-1c75-4017-9def-b36fe424b272.png)
在root骨骼是往前面倾斜,.会导致身体会扭曲的感觉.
大佬不知道是通过那个文件.那段可以修改?
还有那个c_shoulder.r c_shoulder.l2个点..已知这3个是最影响骨骼的问题...

**Comment by chengFengOO** [comment]
![Uploading image.png…]()
S型可以修复?

**Comment by chengFengOO** [comment]
![image](https://user-images.githubusercontent.com/131579551/235314119-6b29a193-4bd0-4752-83bf-e2e8fb5716eb.png)
S型可以修复?

**Comment by chengFengOO** [comment]
![image](https://user-images.githubusercontent.com/131579551/235314208-e0a8c82b-2d7b-4cb5-9bcb-b805cd14c7c0.png)
S型可以修复?

**Comment by chengFengOO** [comment]
大佬有联系的方式或者经常用的邮箱等方式..有几个软件使用的问题想问你...

**Comment by yoshua133** [comment]
Thank you for your brilliant work!
I have encountered this problem too. The "Rh" in the parameter folder seems to rotate downwards an angle. So if using the default SMPL model to calculate the xyz positions of joints based on "poses" and "Rh", the generated human is not facing towards the camera. 
like these:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/39624548/235329054-2f668117-c838-4417-a584-5c0714392e34.png">
<img width="247" alt="image" src="https://user-images.githubusercontent.com/39624548/235329067-54b00adb-7bff-4c3e-bd26-dea13fbdb72f.png">


Is there a way that we can get the SMPL rotation parameters that face towards the camera like this?
<img width="304" alt="image" src="https://user-images.githubusercontent.com/39624548/235329098-793f744c-2c3f-429a-9710-602e7a740478.png">

**Comment by chingswy** [comment]
不知道这是什么引起的问题
