### ISSUE TITLE
it's showing this while smpl reconstruction ImportError: cannot import name 'Renderer' from 'easymocap.visualize' (c:\mocap\easymocap-master\easymocap\visualize\__init__.py) how can i fix this?

### ISSUE THREAD

**Issue by Dev5896** [zju3dv/EasyMocap#31]
![1623835861814](https://user-images.githubusercontent.com/85992730/122195298-dd2b4380-ceb3-11eb-8ba8-426f602b976d.jpg)

**Comment by carlosedubarreto** [comment]
Can you run the instalaation again, copy the text and paste here?

I think there was a problem in the installation.

**Comment by chingswy** [comment]
Fix it.

**Comment by Dev5896** [comment]
ok i am trying to try to install it again
