### ISSUE TITLE
Docs are a bit confusing for getting the smpl_mean_params.npz file

### ISSUE THREAD

**Issue by tleyden** [zju3dv/EasyMocap#313]
In [these docs](https://chingswy.github.io/easymocap-public-doc/quickstart/prepare_mono.html) it mentions:

> Fetch the extra data [here](http://visiondata.cis.upenn.edu/spin/data.tar.gz) and place the smpl_mean_params.npz to data/models/smpl_mean_params.npz.

and gives an example:

```
wget -c http://visiondata.cis.upenn.edu/spin/data.tar.gz
# data/models/smpl_mean_params.npz
```

But the `data.tar.gz` is not actually a gzipped tar, it's just a tar file.  (you can see that's the case by [this script](https://github.com/nkolot/SPIN/blob/master/fetch_data.sh#L6)).  So if you try to `tar -xvfz data.tar.gz` or `gunzip data.tar.gz`, they will both fail.

It would probably help users to call that out explicitly, and/or give an example like:

```
wget -c http://visiondata.cis.upenn.edu/spin/data.tar.gz
tar -xvf data.tar.gz
```

**Comment by chingswy** [comment]
Thanks!
