### ISSUE TITLE
Minor docs issue - spin_checkpoint.pt vs spin_checkpoints.pt

### ISSUE THREAD

**Issue by tleyden** [zju3dv/EasyMocap#314]
In [the docs](https://chingswy.github.io/easymocap-public-doc/quickstart/prepare_mono.html) it says:

> Download pretrained SPIN model [here](http://visiondata.cis.upenn.edu/spin/model_checkpoint.pt) and place it to data/models/spin_checkpoints.pt.

But the code actually expects `data/models/spin_checkpoint.pt`

**Comment by chingswy** [comment]
Thanks for that!
