### ISSUE TITLE
Query on SMPL from Keypoints

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/EasyMocap#315]
@chingswy  Hope you are doing well,

Just a quick question regarding generating SMPL parameters.

I wish to generate smpl parameters directly from the groundtruth keypoints which I have, so
I saw a file here **smpl_from_keypoints.py** where we need to pass the 3dkeypoints of the dataset.

https://github.com/zju3dv/EasyMocap/blob/b44fa3c90b6bbdb3b3fece87fc891cbf154c99f8/apps/demo/smpl_from_keypoints.py#L20

so in this file, if I directly pass the 3dkeypoints of human3.6, will I receive the sample parameters of poses, shapes, Rh, and Th
Becoz I already have the 2d and 3d keypoints of h36m with me, so again conducting pose estimation would be unnecessary.

If there's anything I need to take care of while generating smpl from keypoints, do let  me know.

I await for your response.

**Comment by Dipankar1997161** [comment]
Thank you. I Completed this section so closing it

**Comment by ojss** [comment]
> Thank you. I Completed this section so closing it

Hi, could you help me out by telling me how you managed it?
