### ISSUE TITLE
EasyMocap Instance Segmentation file

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/EasyMocap#316]
Hello @chingswy,

I saw at the Easymocap webpage, under "Instance Segmentation", a python file is mentioned "extract_multi.py", could you tell me where is that file?? 

I cannot find it anywhere in this repo. 
![Screenshot 2023-05-25 015401](https://github.com/zju3dv/EasyMocap/assets/85514219/5122711b-8dd9-4392-8794-6b3ec19a0bae)

What is the "Data" in this? Image Directory?

I want to generate the mask files like zju-mocap, mask and mask_cihp
![000855](https://github.com/zju3dv/EasyMocap/assets/85514219/f9b402b7-e63f-4341-a7bf-5daefed3a3f6)

Do let me know. thank you once again

**Comment by chingswy** [comment]
https://github.com/chingswy/Self-Correction-Human-Parsing/blob/master/extract_multi.py

**Comment by Dipankar1997161** [comment]
Hello @chingswy,

I was going through the code you provided, could you tell me what "Demo.json" is? 

[    annotations = join(tmp_dir, 'Demo.json')](https://github.com/chingswy/Self-Correction-Human-Parsing/blob/6d98043a98a6cf1d5dc98bb17cc6b960b5017c21/extract_multi.py#L44)

**I believe those are the 2d keypoint annotations for the images we want to segment. Correct me in case.**

2. Secondly, how is "path" different from "--tmp" in the Argument parser?

https://github.com/chingswy/Self-Correction-Human-Parsing/blob/6d98043a98a6cf1d5dc98bb17cc6b960b5017c21/extract_multi.py#L119

Do we really need to pass a command for "--tmp" since, the annotations and images are all collected from "path" which passed on as "img_dir" and then as "tmp_dir" as shown in the below section.

https://github.com/chingswy/Self-Correction-Human-Parsing/blob/6d98043a98a6cf1d5dc98bb17cc6b960b5017c21/extract_multi.py#L38


## I am unable to understand how the file structure should be for its implementation. 
**root/img_dir or path/images**
**root/img_dir or path/frame1.json, frame2.json........so on**

do let me know about this. Have a great day

**Comment by chingswy** [comment]
- The `images` folder contains synchronized images from each camera, named in the format of `%06d.jpg`, starting from 0. Please note that the following code mainly uses the image folder. Therefore, if you have obtained videos directly, you need to convert the videos into images first.

```bash
313
├── images
│   ├── 01
│       └ %06d.jpg
│   ├── 02
│   ...
│   ├── 22
│   └── 23
├── extri.yml
├── intri.yml
└── videos
    ├── 01.mp4
    ├── 02.mp4
    ...
    ├── 22.mp4
    └── 23.mp4
```

**Comment by chingswy** [comment]
No. Just run the script once.
