### ISSUE TITLE
Missing file in Easymocap.estimator for DEMO

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/EasyMocap#317]
Hello @chingswy,

I ran the following code "extract_video.py" as seen in the demo for my own dataset. I have the videos as well as the Intri and Extri .yml files.
I am using Yolo-hrnet mode, and the images were extracted but further process stopped 
https://github.com/zju3dv/EasyMocap/blob/b44fa3c90b6bbdb3b3fece87fc891cbf154c99f8/scripts/preprocess/extract_video.py#L204

**ImportError: cannot import name 'Detector' from 'easymocap.estimator' (/home/ndip/EasyMocap/easymocap/estimator/__init__.py)**

Files under Estimator:
![Screenshot 2023-05-26 184314](https://github.com/zju3dv/EasyMocap/assets/85514219/0ad72347-d5ba-43df-a130-851c5bcf90d6)

I have install yolo with the weights under data/models
![Screenshot 2023-05-26 183140](https://github.com/zju3dv/EasyMocap/assets/85514219/6b682284-0e4b-4ad8-809c-8d55760bed6b)

for Installing Easymocap - I have the Quick installation guide from your webpage. "https://chingswy.github.io/easymocap-public-doc/install/install.html#install-easymocap-quickly"

Looking forward to hearing from you. Thank you

**Comment by chingswy** [comment]
I'll check it.

**Comment by Dipankar1997161** [comment]
Thank you @chingswy, 

One more thing, since I will be using the ground truth 3d keypoints  to generate the smpl directly from your demo file: "**_smpl_from_keypoints.py_**"

Should there will be separate .JSON file for every frame for each camera,  or One JSON file should have all the dictionaries of frames in it.

Eg1: idx_1.json, idx_2.json ..... for camera 1, then for camera 2
OR 
{Cam_1: {idx: 1, Keypoints3d:},  {idx: 2, Keypoints3d:}....} - camera 1.json, similary for camera2.json with  {Cam_2: {idx: 1, Keypoints3d:},  {idx: 2, Keypoints3d:}....}


Which would you advise

**Comment by chingswy** [comment]
Hello, I'll update a new script for this function.

**Comment by Dipankar1997161** [comment]
> Hello, I'll update a new script for this function.

Thank you so much for this

**Comment by Dipankar1997161** [comment]
@chingswy 

I wanted to ask, which 3dkeypoints of human3.6 dataset, are generally considered for smpl mapping.

I am directly using the 3d groundtruth of Human3.6m, so i needed to know. I searched the web, mostly I got skeletons of 17 joints.
when i used this, Ofc i will get an error for the missing joints,

do you have any information on this?

Would be helpful

**Comment by jpalachniak** [comment]
> > Hello, I'll update a new script for this function.
> 
> Thank you so much for this

Hello, I still have the same problem. Any cues? 

Still
`ImportError: cannot import name 'Detector' from 'easymocap.estimator'`

**Comment by Dipankar1997161** [comment]
> > > Hello, I'll update a new script for this function.
> > 
> > 
> > Thank you so much for this
> 
> Hello, I still have the same problem. Any cues?
> 
> Still `ImportError: cannot import name 'Detector' from 'easymocap.estimator'`

I think it isn't updated yet. So you can either use Openpose for the 2d estimation from here. Or extract the 2d joints from another repo and then do the remaining processing from here  just make sure to have 25 joints in total

**Comment by chingswy** [comment]
Please check the new interface [here](https://chingswy.github.io/easymocap-public-doc/develop/02_fitsmpl.html)
