### ISSUE TITLE
What is the difference between mvpose in this project and the code in paper ?

### ISSUE THREAD

**Issue by Taylorminer** [zju3dv/EasyMocap#318]
Thanks for your project. I want to know the difference between mvpose in this project and the [code](https://github.com/zju3dv/mvpose) in paper. Do this code support to train the dataset such as shelf or campus ?

**Comment by chingswy** [comment]
Thank you for your interest in our project. The code we provide is a simplified version of the original paper, and it may exclude some complex operations. However, it still retains the core functionality of the mvpose algorithm.

Regarding your second question, our code is designed to work with general multi-view datasets. This means that it can be applied to various scenarios, including datasets like shelf or campus. However, it may require some data format conversion to adapt the code to specific datasets.

If you have a shelf or campus dataset, you can apply our code by converting your data into the format expected by the algorithm. This typically involves organizing the images and corresponding annotations in a compatible structure. Once the data is appropriately formatted, you should be able to train and utilize the code for pose estimation on these datasets.

If you require assistance with the data format conversion or have any further questions, please feel free to ask. We are here to help you make the most of our code in your specific application.
