### ISSUE TITLE
What is the reason for the incorrect match result?

### ISSUE THREAD

**Issue by 13136983989** [zju3dv/EasyMocap#319]
![image](https://github.com/zju3dv/EasyMocap/assets/42019021/ba034339-e68d-4ee5-b1e8-0fb35e05e125)
We set up 23 cameras and used Blender to collect images of the human body, with 400 images per viewing angle. The match result is shown in the figure. Is it because the number of input images is too small or because the camera pose is incorrect? Or something else?

**Comment by chingswy** [comment]
Please make sure that your camera parameters are correct. We follow the standard OpenCV camera parameter, you can use `apps/calibration/vis_camera_by_open3d.py` to check this.
