### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Jerry-Master** [zju3dv/EasyMocap#320]
The documentation is completely missing, are you planning on finishing it? Most of the parameters are not explained anywhere, and the calibration process described in the current documentation is not fully reproducible. It would be nice to have a documentation that is exhaustive and contains all the things that are available.

**Comment by chingswy** [comment]
Thank you for your feedback. We apologize for the lack of time and resources to maintain a complete documentation at the moment.

However, we highly value your needs and inquiries. If you have any specific questions or need explanations regarding any particular section of the documentation, please let us know. We will do our best to provide assistance and explanations. Feel free to provide specific parameters or questions related to the calibration process, and we will make every effort to clarify and guide you.

We understand your expectations for comprehensive documentation, and we also aim to provide the support and assistance you require. If you have any further questions or need additional help, please don't hesitate to inform us. We are dedicated to providing the information and guidance you need. Thank you once again for your feedback, and we will continue striving to enhance the user experience.
