### ISSUE TITLE
SMPL from 3D Groundtruth for Human3.6

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/EasyMocap#321]
Hello @chingswy,

Since you are updating the "Detector function" for yolo-hrnet, I tried to generate smpl parameters directly from 3d-keypoints of H36m.

However, I am unsure, if only 3d keypoints are enough or if any other files would be needed like Camera files and images.
https://github.com/zju3dv/EasyMocap/blob/master/apps/demo/smpl_from_keypoints.py

Q. Also for Human3.6m, there are in total 32 3d joints, but how many to actually consider for smpl generation? 17 or 32
Q. Which args.body would be useful - body25 or h36m. and model would be smpl, -x, -h, or mosh

this is my command:

    python apps/demo/smpl_from_keypoints.py "/mnt/data/ndip/h36m_17joints_s1_Directions/S1/"  --skel3d "/mnt/data/ndip/h36m_17joints_s1_Directions/S1/"  --out "/mnt/data/ndip/h36m_17joints_s1_Directions/smpl_parameters/cam2/"   --annot "/mnt/data/ndip/h36m_17joints_s1_Directions/smpl_parameters/cam2/"  --model smpl --body h36m --write_smpl_full --vis_smpl --verbose --vis_mask

Q. Lastly, why is it the case that when we use **body25**, the code is actually using CONFIG of **body15**
 
https://github.com/zju3dv/EasyMocap/blob/b44fa3c90b6bbdb3b3fece87fc891cbf154c99f8/easymocap/pipeline/basic.py#L80

Line:
https://github.com/zju3dv/EasyMocap/blob/b44fa3c90b6bbdb3b3fece87fc891cbf154c99f8/easymocap/pipeline/basic.py#LL86C1-L86C1

Would appreciate your words on this.

**Comment by chingswy** [comment]
Hello, you'd better use the `MoSH` method to reconstruct SMPL from the markers like AMASS.

**Comment by Dipankar1997161** [comment]
@chingswy, 
Thank you for the response,  
I have to use it further in NeuralBody. Hence I am wondering will the MOSH method work

Actually, I got the processed file from Animatable_nerf but since it has just 1 action "Posing", I wanted to do the same for another action, let's say Directions and Eating.  Which method would be useful here?

What if I use the "https://github.com/zju3dv/EasyMocap/blob/master/apps/demo/mocap.py
And pass the original 3d keypoints and images. Will that work? 

Do let me know, which procedure would be helpful now.

**Comment by chingswy** [comment]
Maybe you can try [this](https://github.com/mks0601/I2L-MeshNet_RELEASE)

**Comment by Dipankar1997161** [comment]
@chingswy thanks for the response. 

Just making sure, do I need to process the file further, since they are already providing smpl-x files for human3.6m and other annotations. Or should I just use those values in NeuralBody directly
