### ISSUE TITLE
Quick Query on Motion Capture Workflow Files

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/EasyMocap#323]
Hello @chingswy,

I was checking the **Motion Capture for Monocular Video** and saw this command
python3 apps/demo/mocap.py ${data} --work internet

    internet:
      calibration: "python3 apps/calibration/create_blank_camera.py ${data}"
      extract_image: none
      extract_keypoints:
        hrnet: "python3 apps/preprocess/extract_keypoints.py ${data} --mode yolo-hrnet"
        openpose: "python3 apps/preprocess/extract_keypoints.py ${data} --mode feetcrop --hand"
      fit: mono-smpl-robust
      output: output-smpl-3d

I would like to know, 
Since I have my own Intri.yml files, what should I pass as --work,

Even when I passed my own intri.yml, it got overwritten with the new files. 

This is the intri.yml, I want to use:

      %YAML:1.0
      ---
      names:
        - "03"
      K_03: !!opencv-matrix
        rows: 3
        cols: 3
        dt: d
        data: [2664.22974522, 0.000, 511.78055391, 0.000, 2664.69277422, 567.12542926, 0.000, 0.000, 1.000]
      dist_03: !!opencv-matrix
        rows: 1
        cols: 5
        dt: d
        data: [0.000, 0.000, 0.000, 0.000, 0.000]
Can you help out here?

**Comment by chingswy** [comment]
Hello, you can comment this line`calibration: "python3 apps/calibration/create_blank_camera.py ${data}"`
