### ISSUE TITLE
Difference in detection and smpl

### ISSUE THREAD

**Issue by LegendTova** [zju3dv/EasyMocap#325]
Hello,

I am trying to get mocap from my own dataset and I think I got calibration down. I noticed that the detection looks fine but the reprojection onto smpl does not. Any ideas at what I can do to solve it? Is it a calibration problem? Is my data just not good enough?

Pictures below:

![000000](https://github.com/zju3dv/EasyMocap/assets/56600403/4520e3e4-1460-4597-b5a0-09c76669e18b)
![000000](https://github.com/zju3dv/EasyMocap/assets/56600403/0b030159-f1f7-4268-a383-07604be6a0e2)

**Comment by Dipankar1997161** [comment]
Which --body option are you using? Coz that matters too. 

If it's not accurate then you gonna get the error

**Comment by massinissa2021** [comment]
I had used these two commands 

python apps/preprocess/extract_keypoints.py 0_input/project  --mode mp-pose

python apps/demo/mocap.py 0_input/project  --work lightstage-dense-smpl --triangulator_min_views 2 --subs_vis 1

and they worked fine with some distortion 

I used also these commands 

python scripts\preprocess\extract_video.py 0_input\project --openpose C:\Users\*********\Desktop\Mpcap\openpose

python apps\demo\mv1p.py 0_input\project --out 1_output\project --vis_det --vis_repro --sub_vis 1 2  --vis_smpl 


and the results were very similar to your case...I understood that the cameras should face you or at least a bit higher, but it should not be above "too high" ...plus the image must be 1024x1024 or 1092*1080 ...

**Comment by massinissa2021** [comment]
for me , the problem I find out was the chessboard I was using is wrong ....it should not be similar in the edges " squares" ...choose another chessboard "9,6" with big surface  if you can afford it
