### ISSUE TITLE
unable to run the command 

### ISSUE THREAD

**Issue by massinissa2021** [zju3dv/EasyMocap#327]
hi

I have this error
when I run this command : 

python \apps\demo\mv1p.py 0_input\project --out 1_output\project --vis_det --vis_repro --undis --sub_vis 1 2 3 4 --vis_smpl

Traceback (most recent call last):
  File "C:\Users\******\Desktop\wolder\EasyMocapPublic\apps\demo\mv1p.py", line 11, in <module>
    from easymocap.pipeline import smpl_from_keypoints3d2d
ModuleNotFoundError: No module named 'easymocap.pipeline'
here the list of pip packages : 
PS C:\Users\*********> pip list
Package                       Version
----------------------------- ---------
anaconda-client               1.11.2   
anaconda-navigator            2.4.0    
anaconda-project              0.11.1   
attrs                         22.1.0   
backports.functools-lru-cache 1.6.4    
backports.tempfile            1.0      
backports.weakref             1.0.post1
beautifulsoup4                4.12.2   
boltons                       23.0.0   
brotlipy                      0.7.0    
certifi                       2023.5.7 
cffi                          1.15.1   
chardet                       4.0.0    
charset-normalizer            2.0.4    
click                         8.0.4    
clyent                        1.2.2    
colorama                      0.4.6    
conda                         23.5.0   
conda-build                   3.24.0   
conda-content-trust           0.1.3    
conda-pack                    0.6.0    
conda-package-handling        2.0.2    
conda_package_streaming       0.7.0    
conda-repo-cli                1.0.41   
conda-token                   0.4.0    
conda-verify                  3.4.2    
cryptography                  39.0.1   
defusedxml                    0.7.1    
fastjsonschema                2.16.2   
filelock                      3.9.0
future                        0.18.3
glob2                         0.7
idna                          3.4
Jinja2                        3.1.2
jsonpatch                     1.32
jsonpointer                   2.1
jsonschema                    4.17.3
jupyter_core                  5.3.0
libarchive-c                  2.9
MarkupSafe                    2.1.1
menuinst                      1.4.19
navigator-updater             0.4.0
nbformat                      5.7.0
opencv-python                 4.7.0.72
packaging                     23.0
pathlib                       1.0.1
Pillow                        9.4.0
pip                           22.3.1
pkginfo                       1.9.6
platformdirs                  2.5.2
pluggy                        1.0.0
ply                           3.11
psutil                        5.9.0
pycosat                       0.6.4
pycparser                     2.21
PyJWT                         2.4.0
pyOpenSSL                     23.0.0
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
pyrsistent                    0.18.0
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2022.7
pywin32                       305.1
PyYAML                        6.0
QtPy                          2.2.0
requests                      2.29.0
requests-toolbelt             0.9.1
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
ruamel-yaml-conda             0.17.21
setuptools                    65.6.3
sip                           6.6.2
six                           1.16.0
soupsieve                     2.4
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
tornado                       6.2
tqdm                          4.65.0
traitlets                     5.7.1
ujson                         5.4.0
urllib3                       1.26.16
wheel                         0.38.4
win-inet-pton                 1.1.0
wincertstore                  0.2
zstandard                     0.19.0

**Comment by Dipankar1997161** [comment]
Have you installed easymocap? 
Not cloning the repo but actually installation

**Comment by massinissa2021** [comment]
thanks for the reply 
I followed this tutorial ...https://www.youtube.com/watch?v=fgg1po6u9Tk

**Comment by massinissa2021** [comment]
I fixed the problem ...I messed with the python versions ...but it works fine for now ...
