### ISSUE TITLE
Quick start demo error

### ISSUE THREAD

**Issue by amberhappy** [zju3dv/EasyMocap#328]
<img width="397" alt="image" src="https://github.com/zju3dv/EasyMocap/assets/20748171/b4c9f126-85dd-451f-b46d-8de84c495ea5">

got error:
<img width="1354" alt="image" src="https://github.com/zju3dv/EasyMocap/assets/20748171/705b7e17-9d2f-4ea1-ba74-910871517a5b">

And seems like no annots was calculated, is that right?

**Comment by Dipankar1997161** [comment]
This happens when the code was unable to read your data.
Either wrong path or wrong data format.

Can you show your directory structure and script passed

**Comment by amberhappy** [comment]
Command likes that:
<img width="553" alt="image" src="https://github.com/zju3dv/EasyMocap/assets/20748171/d1026207-075b-4c46-b8eb-40bd34b2d83e">

And directory structure:
<img width="488" alt="image" src="https://github.com/zju3dv/EasyMocap/assets/20748171/51fb30d6-6b19-4c0c-8930-48090e7ff2b9">


Two videos in the folder 'videos'
<img width="469" alt="image" src="https://github.com/zju3dv/EasyMocap/assets/20748171/531d9370-0cf0-4459-857c-3475c966feb7">

And images was extracted from videos like that:
<img width="775" alt="image" src="https://github.com/zju3dv/EasyMocap/assets/20748171/2d54e4fe-f825-40f6-b5ef-a039d7c8bbca">

**Comment by amberhappy** [comment]
Run apps/demo/preprocess/extract_keypoints.py before running mocap.py can solve this problem.

**Comment by Dipankar1997161** [comment]
> Run apps/demo/preprocess/extract_keypoints.py before running mocap.py can solve this problem.

Ooh yes  you can calculate the annots by extract keypoints or pass your own groundtruth values before doing so. 

Just one more add on.
Make sure to use --mode mono-smpl because the --mono-smpl-robust, might not yield a good output. 
Just a suggestion
