### ISSUE TITLE
hi when i am trying to import the mocap in blender it's showing it couldnot find the pkl file can u plz help me with it i plz

### ISSUE THREAD

**Issue by Dev5896** [zju3dv/EasyMocap#33]
![blender showing pkl file not found](https://user-images.githubusercontent.com/85992730/122357159-1aa1d680-cf71-11eb-89ff-f4b3ab344e04.png)

**Comment by carlosedubarreto** [comment]
If you are using mocap import addon.
Actually it's only working doing some changes on 2 files.

The developer already made a command to export the data but i didn't update the addon yet.

So to make it work now, you will have to do these changes
https://github.com/zju3dv/EasyMocap/issues/25#issuecomment-842266080

Or following the instructions on this page
https://github.com/carlosedubarreto/b3d_mocap_import/tree/main/replace_easymocap_files

I plan to fix mocao import to get using the update easymocap code, but I'm just out of time to do it lately

**Comment by Dev5896** [comment]
![2](https://user-images.githubusercontent.com/85992730/122427609-e220ed80-cfae-11eb-87ff-f21729ce1acf.png)
when i replaced the mv1p file and body_model file with the ones given in the link https://github.com/carlosedubarreto/b3d_mocap_import/tree/main/replace_easymocap_files
 and again tried to reconstruct smpl it's showing this

**Comment by Dev5896** [comment]
after i replaced the file it's showing this
![Uploading 2.png…]()

**Comment by carlosedubarreto** [comment]
Hum, sorry, I didnt test with the new version of easymocap, probably its another problem.

I'll have to ask you to wait for me to make the addon work with this new version, or.... that you follow the instructions to do the convertion using easymocap script to create bvh files, explained in this link

https://github.com/zju3dv/EasyMocap/blob/master/doc/02_output.md#export-to-bvh-format
