### ISSUE TITLE
Distortion

### ISSUE THREAD

**Issue by LegendTova** [zju3dv/EasyMocap#330]
Hello,

is it possible to turn off the distortion of the images? some of my footage gets huge radial distortion for some reason. 
![000100](https://github.com/zju3dv/EasyMocap/assets/56600403/ff0bef6a-836a-4aa4-90d0-f778255362e9)

**Comment by Dipankar1997161** [comment]
There must be an option for " --undis " . You may check that out

**Comment by chingswy** [comment]
Do you calibrate the camera correctly?

**Comment by LegendTova** [comment]
> There must be an option for " --undis " . You may check that out

Yeah, I have been using that but this still happens. I used --tryfocal on an older attempt and that helped but it didn't really help here

> Do you calibrate the camera correctly?

In the check calibration, everything looks fine with the cube. Except it also distorts the camera a bunch here too

![1](https://github.com/zju3dv/EasyMocap/assets/56600403/e0276c84-18e2-471d-9620-9f4576107c88)
![2](https://github.com/zju3dv/EasyMocap/assets/56600403/8e0b5220-414f-4893-ae6e-8e5817ca066a)
![3](https://github.com/zju3dv/EasyMocap/assets/56600403/b1d2da3a-a278-489e-a881-0c66fe55994f)

**Comment by LegendTova** [comment]
So is there an option to turn it off distortion? Or can I orientate my camera in such away to prevent it. Does a wider shot cause it to distort for some reason?

**Comment by chingswy** [comment]
Hello, I believe your camera doesn't have significant distortion. I think the issue lies in the calibration process, where the number of images used for calibrating the camera's intrinsic parameters is insufficient or the coverage range is inadequate.

**Comment by massinissa2021** [comment]
hi, I had this kind of distortion and I fix it by converting the video to 1024x1024 ...!!

**Comment by LegendTova** [comment]
> hi, I had this kind of distortion and I fix it by converting the video to 1024x1024 ...!!

> Hello, I believe your camera doesn't have significant distortion. I think the issue lies in the calibration process, where the number of images used for calibrating the camera's intrinsic parameters is insufficient or the coverage range is inadequate.

Yeah, so I hadn't moved the chessboard to the edge of the frame in the intrinsic calibration so that caused distortion in the product.
