### ISSUE TITLE
Link to monocular dataset is broken

### ISSUE THREAD

**Issue by jamesWalker55** [zju3dv/EasyMocap#332]
When trying to download the dataset from https://chingswy.github.io/easymocap-public-doc/quickstart/quickstart.html#demo-on-monocular-videos it says the link is outdated / removed:

![image](https://github.com/zju3dv/EasyMocap/assets/30405220/75f7c013-a110-48ce-8fd8-60cb8613a517)

**Comment by chingswy** [comment]
Please check the new code and data [here](https://chingswy.github.io/easymocap-public-doc/develop/03_fitsmpl_monocular.html#try-the-code)
