### ISSUE TITLE
reconstruction issue

### ISSUE THREAD

**Issue by hutijblend** [zju3dv/EasyMocap#34]
https://github.com/zju3dv/EasyMocap/issues/25#issuecomment-842266080
 i have made changes according to the comments in mvip and body_model 
now it is is showing this error shutil not defined in shutil.cpoy

**Comment by chingswy** [comment]
No need for these changes now. @carlosedubarreto

**Comment by carlosedubarreto** [comment]
Hello @hutijblend i'm finisin the update to use the oficial way to have body and fingers inside blender.

I'll post here.
You just have to update your easymocap to the latest (it was updated today)

And to update, you can download the zip files and overwrite your previous unzipped folder.

**Comment by carlosedubarreto** [comment]
@hutijblend 
Here is the updated version.

You just have to run easymocap adding `--write_smpl_full`

for example
`python apps/demo/mv1p.py 0_input/sample --out 1_output/sample/smplx --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --body bodyhandface --model smplx --gender male --vis_smpl --write_smpl_full`

[Mocap_PE_data_import_0.722.zip](https://github.com/zju3dv/EasyMocap/files/6675736/Mocap_PE_data_import_0.722.zip)

**Comment by hutijblend** [comment]
thanks i will try it and will inform u if i get anymore trouble
