### ISSUE TITLE
converting videos causing distortion and bad results of smpl

### ISSUE THREAD

**Issue by massinissa2021** [zju3dv/EasyMocap#342]
hi there,

I would like to address my problem, when I do try synchronize the videos That I make " 2 cams" ...I use davinci resolve and it is fast and easy tool to use...however , even all the videos have the same formats "1920x1080 "after redering them" ,the cailbration "cube &  the smpl repro and smpl " are really bad results, however, if I use the origin videos " 1920x1080" I got a clean cube result and shape , but , with the converting the 2 videos that I did synchronise  to use them for repro smpl , there is distrotion & bad smpl results ...! what is the solution to solve this problem ?

**Comment by chingswy** [comment]
I'm sorry for the confusion. Could you please provide more details about the situation you are encountering and the specific issue you are facing? This will help me better understand your question and provide you with an appropriate response.

**Comment by massinissa2021** [comment]
> I'm sorry for the confusion. Could you please provide more details about the situation you are encountering and the specific issue you are facing? This will help me better understand your question and provide you with an appropriate response.
sorry for the confusion ...If I use the origin videos from two phones .... I get good calibration, but the repro smpl be messed up ...so I have to convert all the videos before using them ...

**Comment by massinissa2021** [comment]
sorry for the confusion ; every time if I synchronize the "2 videos" with divinci resolve that I use for smpl command ...python apps\demo\mv1p.py 0_input\project --out 1_output\project --vis_det --vis_repro --sub_vis 1 2  --vis_smpl 
I have to convert intri & extri videos and get the results ...like this one 
![000000](https://github.com/zju3dv/EasyMocap/assets/95708136/9958f5cb-ab08-4beb-9e99-2bfabaf02f5c)
but if I use the command  
python apps/demo/mocap.py 0_input/project  --work lightstage-dense-smpl --triangulator_min_views 2 --subs_vis 1 

I get it in this way 

![000000](https://github.com/zju3dv/EasyMocap/assets/95708136/2ba17ed8-089b-4f5b-b06e-98b677a1f89f)

is there anyway to solve

**Comment by massinissa2021** [comment]
I solved the problem by using other cam position !
