### ISSUE TITLE
Failure to run multiple person ballet_2person under develop

### ISSUE THREAD

**Issue by 1224K** [zju3dv/EasyMocap#343]
Hi, 
I try to run Multiple Person ballet_2person under develop
`emc --cfg config/mvmp/body/ballet_2person.yml --root data/examples/ballet_2person`

And I got this error
![messageImage_1689233073019](https://github.com/zju3dv/EasyMocap/assets/75677010/05aff2f7-f917-4b39-b530-46fc6c3a106a)

Does anyone have any ideas to this problem? 

Thanks!

**Comment by 1224K** [comment]
I found that the function _batch_triangulate(keypoints_, Pall, min_view=2)_ in Easymocap\easymocap\mytools\triangulator.py indicates that 
    The shape of keypoints_ is (nViews, nJoints, 3): Two-dimensional detection
    The shape of Pall is (nViews, 3, 4): the projection matrix for each view.

However when the function _remove_outjoint(kpts2d, Pall, out_joint, dist_max, dist_track, min_view=3, previous=None, debug= False)_ in EasyMocap\myeasymocap\operations
line 49 `comb_k3d = batch_triangulate(comb_kpts, comb_Pall)` brings in comb_Pall with shape (nViews, nJoints, 3, 4).
so I'll line 48
`comb_Pall = Pall_nj[comb_views]` to `comb_Pall = Pall_nj[comb_views[:, 0]]` in order to match the shape, 
and it works, but I want to make sure that my change is correct? Thanks!

**Comment by chingswy** [comment]
I have fixed this bug. Please pull.
