### ISSUE TITLE
where is output-vposer-3d generated from?

### ISSUE THREAD

**Issue by ellzeycunha0** [zju3dv/EasyMocap#349]
I want to use the data of "output-vposer-3d/stml", But i do not know how to generate it. Could you tell me how to do?

**Comment by zhuangqirong** [comment]
> 你好，请问你在哪里找到的？这是一个已弃用的功能。

![image](https://github.com/zju3dv/EasyMocap/assets/51116758/2781d2e9-e02d-4824-8f06-a481cba4555b)
