### ISSUE TITLE
MANO processing

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/EasyMocap#35]
I found the new options to process hands only, and whe trying, it gives this error

OSError: data/smplx\J_regressor_mano_RIGHT.txt not found.

![image](https://user-images.githubusercontent.com/4061130/122580817-c1977880-d02c-11eb-8079-c4d60d1812fe.png)

Where can I download it?

**Comment by chingswy** [comment]
Sorry, I forget to commit it. Thank you for reminding me!

**Comment by carlosedubarreto** [comment]
Thanks now its working
