### ISSUE TITLE
How to get a mask as good as in the zju-mocap dataset

### ISSUE THREAD

**Issue by CHDTevior** [zju3dv/EasyMocap#351]
As the title, which files in the Easymocap project should I run to use the obtained 3D key points and other information to obtain a more accurate mask? I tried to use the pre-trained model in SCHP to generate the mask and found that the effect was not very good.
![000019](https://github.com/zju3dv/EasyMocap/assets/96759520/ebaa7868-763b-4d70-869b-d07114dba711)

**Comment by chingswy** [comment]
Did you use the provided [scripts](https://chingswy.github.io/easymocap-public-doc/install/install_segment.html)?
