### ISSUE TITLE
Visualise key points and Skeletons after SMPL Reconstruction

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/EasyMocap#353]
hello @chingswy ,

**So I asked this question in NeuralBody repo and Pengsida informed me to ask you:**

**Q1.** In **neural-body**, we did not plot the skeleton nor the key points as it is usually not part of the reconstruction. However, I want to visualise the 3d and 2d skeleton/keypoints on the images or separately (**specially for Zju-mocap Dataset**)

I came across this vis_utils file there. Can I directly use it to plot the skeletons or even just the key points on the images (Maybe have a look)
https://github.com/zju3dv/neuralbody/blob/301ab711418dd118b59eed833e34aa4d39e1cc0b/lib/utils/vis_utils.py

OR If you can suggest me anything to plot both the 3d smpl in 3d plane and its respective 2d points in 2d plane and image, it would be great. There are many functions here, I need one for mostly "**monocular images**"

**Q2.** The 3d points to be used for plotting will be smpl_poses or smpl_joints? and do we need the vertices and j_regressor to plot the points or just the 3d joints are enough.

Thank you

**Comment by chingswy** [comment]
Check the old code [here](https://github.com/zju3dv/EasyMocap/blob/master/doc/realtime_visualization.md)

**Comment by Dipankar1997161** [comment]
@chingswy,
Thanks for the help, I successfully plotted the 3d smpl and its 2d skeleton representation on rgb images.

I have a small request. 
https://github.com/zju3dv/EasyMocap/blob/0ebb1d25b7b0fdcbf56ae4532daab7020873af13/easymocap/dataset/config.py#L626
like the configs and skeleton-tree in easymocap for different dataset. 

**Do you have one for the COCO skeleton??**  
If you have one or any reference, kindly share. 

Have a great week and do update me

**Comment by chingswy** [comment]
Check [here](https://github.com/zju3dv/EasyMocap/blob/0fb7de5499baee32e67aedcd31047d424815b197/easymocap/dataset/config.py#L153)

**Comment by Dipankar1997161** [comment]
That worked for me. Thank you!

@chingswy , **Do you know any methods to calculate the coordinates of missing joints for COCO?**

Query:
I converted the smpl joints to coco format, but the nose joint is missing, since there is nose in smpl and I want to add the "Nose Joint"
I tried an approximate method of calculating the distance between "**the shoulder joints and the center joint**" and performed symmetry. But the joint position was incorrect.

    def coco_with_nose_3d(pts):
        neck_joint_3d = pts[0, 4]
        left_shoulder_joint_3d = pts[0, 5]
        right_shoulder_joint_3d = pts[0, 6]
        
        # Find the direction vectors from neck to left shoulder and right shoulder

        left_shoulder_direction_3d = left_shoulder_joint_3d - neck_joint_3d
        right_shoulder_direction_3d = right_shoulder_joint_3d - neck_joint_3d
        
        # Compute the position of the approximated fourth joint

        approximated_joint_3d = neck_joint_3d + left_shoulder_direction_3d + right_shoulder_direction_3d
        offset_y = 0  # Adjust this value as needed
        
        # Push the approximated joint in the y-direction to form the nose position

        nose_position_3d = approximated_joint_3d + np.array([0, offset_y, 0])
        # Replace the fourth joint position with the approximated joint position
        pts[0, 0] = nose_position_3d
        return pts 

from front view, one can ignore, but from side, its wrong

![Screenshot 2023-08-07 132752](https://github.com/zju3dv/EasyMocap/assets/85514219/234b4d6e-2a84-46c4-a5d2-f15562a49748) ![Screenshot 2023-08-07 132627](https://github.com/zju3dv/EasyMocap/assets/85514219/c3a091fc-95b3-4a2c-82e9-a42adce5483b)

If you could inform or redirect me to some method, that would be great. Thanks once again

**Comment by chingswy** [comment]
Please check [this](https://github.com/zju3dv/EasyMocap/blob/0fb7de5499baee32e67aedcd31047d424815b197/apps/postprocess/write_vertices.py#L45)
