### ISSUE TITLE
About the rendering of mesh

### ISSUE THREAD

**Issue by KeepmovingBenLee** [zju3dv/EasyMocap#355]
Hi, thanks for your wonderful work!

I am wondering how the mesh in the image is rendered. Did you use pyrender, open3d or other tools?
<img width="833" alt="image" src="https://github.com/zju3dv/EasyMocap/assets/32378119/e2b2994a-c203-46b3-80d4-87e798c45bbd">

Thanks a lot!

**Comment by KeepmovingBenLee** [comment]
I also wonder that how the meshes are rendered, thanks again :)
<img width="857" alt="image" src="https://github.com/zju3dv/EasyMocap/assets/32378119/779b05f7-f346-4501-9758-4f7a52c16cef">
<img width="848" alt="image" src="https://github.com/zju3dv/EasyMocap/assets/32378119/ab56a33e-5ca7-4752-95a3-4b043f4c4d3f">

**Comment by chingswy** [comment]
I use pyrender. [Here](https://github.com/zju3dv/EasyMocap/blob/0fb7de5499baee32e67aedcd31047d424815b197/myeasymocap/io/vis3d.py#L12) is an example.
