### ISSUE TITLE
About the demo of Novel View Synthesis of Human Interactions From Sparse Multi-view Videos

### ISSUE THREAD

**Issue by y-kage** [zju3dv/EasyMocap#356]
Hello @chingswy , thanks for your wonderful work!

I'm trying to do the demo of 'Novel View Synthesis of Human Interactions From Sparse Multi-view Videos' following the page below using the example data. [https://chingswy.github.io/easymocap-public-doc/works/multinb_code.html](url)

However, I get some errors.  
When running the motion capture part, I get the the result below, which seems to not working well. 
- Reconstruct the human
`FileNotFoundError: [Errno 2] No such file or directory: 'config/data/mvmp.yml'`
- Reconstruct the object
`[run] none`
`sh: 1: none: not found`
`[Skip] Triangulation already done, skipping...`

If I skip the motion capture part and do the training, I get the error below. '../data' directory is where the example data is. 
<img width="1041" alt="スクリーンショット 2023-08-10 4 18 42" src="https://github.com/zju3dv/EasyMocap/assets/125951749/ae5fa8ff-0afc-4608-950b-19a93a9532aa">

The question is similar to #214 , 

Q1. Is it possible to do the demo of Novel View Synthesis of Human Interactions From Sparse Multi-view Videos now?

If so, 
Q2. Is the 'config/data/mvmp.yml' going to be released?
Q3. Is the result of reconstruct the object part correct?
Q4. At the training, should '../data/output-smpl-3d/vertices/1/000000.json' be in the data in advance, or is it going to be made in the process of motion capture? Or do I have to do other process before?

Looking forward to your reply! Thanks a lot!

**Comment by chingswy** [comment]
Q1: Just follow [this page](https://chingswy.github.io/easymocap-public-doc/works/multinb.html)
Q2: This part is released with different names.
Q3: See Q1. We have released the object annotations.
Q4: See Q1.

**Comment by y-kage** [comment]
I am able to train now. Sorry for the overlook of that page. 

About Q2, could I know which is the file released ? Is it 'config/data/multivideo-mp.yml' ?

Thanks!

**Comment by chingswy** [comment]
Hello, you can find the code [here](https://chingswy.github.io/easymocap-public-doc/develop/04_multiperson.html)

**Comment by y-kage** [comment]
Thanks!

**Comment by y-kage** [comment]
thank you!

**Comment by 1224K** [comment]
Hello @chingswy , thanks for your excellent work!

When I try to follow the tutorial [page ](https://chingswy.github.io/easymocap-public-doc/works/multinb.html) for the demo "Novel View Synthesis for Human Interaction in Sparse Multi-View Video"

I got this error, It seems that time_offset.json is missing, so I would like to ask what time_offset.json is?
![Untitled (2)](https://github.com/zju3dv/EasyMocap/assets/75677010/815962be-5d5e-479e-bbe9-ac3c470b469b)

Thank you very much!

**Comment by 1224K** [comment]
Oh, I see, but the download folder looks outdated, can I have it?

Thank you very much!

**Comment by chingswy** [comment]
I have updated the link.

**Comment by 1224K** [comment]
Thank you again for your help.

**Comment by shadel** [comment]
> I have updated the link.

The link is expired again, can I have it?
Thank you very much!
