### ISSUE TITLE
Color Calibration for Multi-Camera Systems

### ISSUE THREAD

**Issue by CHDTevior** [zju3dv/EasyMocap#357]
Thank you for your team's contribution to Motion capture, I am using Easymocap to make zju-mocap-like dataset that can be used for Enerf and neuralbody project, but there are some color differences in the pictures taken by my multi-camera system, I noticed your There is a 24 color Calibrite ColorChecker in the interface displayed by the project. Could you please tell me how to calibrate the color of your multi-camera system? 
![image](https://github.com/zju3dv/EasyMocap/assets/96759520/1bc2ed50-9d48-4796-8666-77db95d9a4c3)

Thank you very much!

**Comment by CHDTevior** [comment]
Thanks! Is the white balance adjustment in step 3 also using a color checker? Is this step an adjustment to the camera during shooting or an adjustment in the editing software after shooting? Looking forward to your reply. @chingswy

**Comment by chingswy** [comment]
Hello, our capture system has the function to adjust the camera during shooting. If your system doesn't have this function, you should adjust the captured video after shooting.

**Comment by CHDTevior** [comment]
Thanks for your answer. We will check for these issues.
