### ISSUE TITLE
Error using Mano

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/EasyMocap#36]
When trying Mano, looks like when the hand get hidden in one view, it throws error.

![image](https://user-images.githubusercontent.com/4061130/122636433-a1fd6000-d0bf-11eb-99e7-2ef21b35f100.png)

it can be coincidence, bu I think the error is when the hand get occluded in some view.

![image](https://user-images.githubusercontent.com/4061130/122636456-c22d1f00-d0bf-11eb-94eb-981a6f6ac18c.png)

the error is in frame 50, and this print above is from frame 40

**Comment by chingswy** [comment]
I can't reproduce this error.
```bash
python3 apps/demo/mv1p.py ${data} --body handl --model manol --out ${data}/output/manol --undis

  Demo code for multiple views and one person:

    - Input : /media/qing/Dataset/EasyMocap/test/zju-ls-feng => 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23
    - Output: /media/qing/Dataset/EasyMocap/test/zju-ls-feng/output/manol
    - Body  : manol=>neutral, handl

triangulation: 100%|█████████████████████████████████| 800/800 [00:04<00:00, 184.86it/s]
dump: 100%|████████████████████████████████████████| 800/800 [00:00<00:00, 10257.37it/s]
loading: 100%|███████████████████████████████████████| 800/800 [00:03<00:00, 219.73it/s]
-> [Optimize global RT  ]: 3590.0ms
-> [Optimize 3D Pose/800 frames]: 2817.1ms
-> [Optimize 2D Pose/800 frames]: 650.8ms
render: 100%|████████████████████████████████████████| 800/800 [00:03<00:00, 210.16it/s]
```

You can delete the output folder and try it again.

**Comment by carlosedubarreto** [comment]
Oh, my.... thanks Ill try it.

**Comment by carlosedubarreto** [comment]
Thankssssssssssssss

After erasing all the output it worked 😅
![image](https://user-images.githubusercontent.com/4061130/122637922-94e46f00-d0c7-11eb-8a6e-68156b13ac1b.png)
