### ISSUE TITLE
To obtain annots.npy similar to that provided in the zju-mocap dataset

### ISSUE THREAD

**Issue by CHDTevior** [zju3dv/EasyMocap#360]
I am using easymocap to make a self-built dataset that can be used for finetune on the Enerf project. I noticed that the annots.npy generated by the command 

python scripts/preprocess/extract_video.py 3_input\project --openpose F:\EasyMocap\openpose 

python apps/demo/mocap.py F:\EasyMocap\EasyMocap\3_input\project

python easymocap_to_neuralbody.py --input_dir F:\EasyMocap\EasyMocap\3_input\project --type annots

python easymocap_to_neuralbody.py --input_dir F:\EasyMocap\EasyMocap\3_input\project --type vertices

cannot read the image when it is used. What is the reason and how can I fix it.

**Comment by CHDTevior** [comment]
![image](https://github.com/zju3dv/EasyMocap/assets/96759520/8548a894-67b0-4f3a-9aec-a68b9f263ae8)

**Comment by CHDTevior** [comment]
Solved, because the path is wrong. \->/

**Comment by zhuangqirong** [comment]
> easymocap_to_neuralbody.py
Where is this file?
