### ISSUE TITLE
conversion of Standard SMPL to Easymocap or Zju-mocap format

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/EasyMocap#363]
Hello @chingswy,

I saw a issue regarding the conversion of output mocap smpl to standard smpl.  
I want to do the opposite, I have standard global orients and transl, I wish to get the Rh and Th.

**is this the conversion formula which is mentioned here**

""" We set the first 3 dimensions of poses to zero, and add a new parameter Rh to represents the global oritentation, the vertices of SMPL model V = RX(theta, beta) + T. Please note that the paramter Rh is not equal to global_orient in SMPL-X model. We take this representation because that changing paramters to new coordinate system in origin is difficult(see [this link](https://www.dropbox.com/scl/fi/zkatuv5shs8d4tlwr8ecc/Change-parameters-to-new-coordinate-system.paper?dl=0&rlkey=lotq1sh6wzkmyttisc05h0in0)).

In our representation, you can just use **R'@(RX + T) + T'** to convert the model, and the new global rotaion and translation is simply written as **R'@R and R'@T + T'** """

**R'@ R and R'@ T + T'**  is the **new Rh and Th which is used in Easymocap**, where R is the standard global orient and T is the standard transl of Stabdard smpl-x model. Is this correct?

**R'@(RX + T) + T'** - will this be used to convert the standard smpl poses and thetas to easymocap format? or whats the use case, if you can guide a bit here.   

OR we do not need to convert the poses and thetas at all but rather just the Rh and Th

**My goal is to convert my custom dataset into zju_mocap format.**
Thats all i wanna ask.

**Comment by chingswy** [comment]
Please check this [line](https://github.com/zju3dv/EasyMocap/blob/0fb7de5499baee32e67aedcd31047d424815b197/easymocap/bodymodel/smpl.py#L239)

**Comment by Dipankar1997161** [comment]
Thank you for the response. Can you quickly explain, what's the major difference between Rh and Global_orient 
similarly for Th and Trans.

Sometimes, trans can be used as Th but Global_orient cannot be used as Rh. This is something which I wish to understand.
@chingswy

**Comment by Dipankar1997161** [comment]
@chingswy 

I succesfully run mv1p with smpl model by using yolo-hrnet at the pose estimator.
But when I try to use **smpl-h model,** I got the following error, 

    File "/home/ndip/EasyMocap/easymocap/smplmodel/body_model.py", line 160, in __init__
        self.num_pca_comps = kwargs['num_pca_comps']
    KeyError: 'num_pca_comps'

Can you please tell me what does num_pca_comps mean here and how to resolve this?

        if self.model_type == 'smplh':
            # load smplh data
            self.num_pca_comps = kwargs['num_pca_comps']

https://github.com/zju3dv/EasyMocap/blob/0fb7de5499baee32e67aedcd31047d424815b197/easymocap/smplmodel/body_model.py#L158C9-L160C57

I wish to retrieve the finger/hand joints as well so the overall render on my custom data can be better.  The detection with YOLO+Hrnet looks great.

![000007](https://github.com/zju3dv/EasyMocap/assets/85514219/dd5478f7-35bc-4cbb-a123-a6941eeaca2f)

Lastly, is there any other way of getting the hand and leg joints OTHER THAN OPENPOSE?

**Comment by jinnan-chen** [comment]
> Please check this [line](https://github.com/zju3dv/EasyMocap/blob/0fb7de5499baee32e67aedcd31047d424815b197/easymocap/bodymodel/smpl.py#L239)

Hi, is this the code to convert global_orient and transl in SMPL dataset to Rh and Th in zju_mocap format? Or the other way around? If it is the first case, why set poses[:, :3] = 0? The input poses from SMPL is (23,3) and output poses in zju_mocap format should be [24,3], thus we should set poses_new= torch.cat ([ torch.zeros(3),poses],dim=0) as zju_mocap format, right?

**Comment by jinnan-chen** [comment]
> Hello @chingswy,
> 
> I saw a issue regarding the conversion of output mocap smpl to standard smpl. I want to do the opposite, I have standard global orients and transl, I wish to get the Rh and Th.
> 
> **is this the conversion formula which is mentioned here**
> 
> """ We set the first 3 dimensions of poses to zero, and add a new parameter Rh to represents the global oritentation, the vertices of SMPL model V = RX(theta, beta) + T. Please note that the paramter Rh is not equal to global_orient in SMPL-X model. We take this representation because that changing paramters to new coordinate system in origin is difficult(see [this link](https://www.dropbox.com/scl/fi/zkatuv5shs8d4tlwr8ecc/Change-parameters-to-new-coordinate-system.paper?dl=0&rlkey=lotq1sh6wzkmyttisc05h0in0)).
> 
> In our representation, you can just use **R'@(RX + T) + T'** to convert the model, and the new global rotaion and translation is simply written as **R'@r and R'@t + T'** """
> 
> **R'@ R and R'@ T + T'** is the **new Rh and Th which is used in Easymocap**, where R is the standard global orient and T is the standard transl of Stabdard smpl-x model. Is this correct?
> 
> **R'@(RX + T) + T'** - will this be used to convert the standard smpl poses and thetas to easymocap format? or whats the use case, if you can guide a bit here.
> 
> OR we do not need to convert the poses and thetas at all but rather just the Rh and Th
> 
> **My goal is to convert my custom dataset into zju_mocap format.** Thats all i wanna ask.

Hi, do you solve this problem?

**Comment by lxiaan** [comment]
hi, how exactly did you manage to get this to work with smplh?
