### ISSUE TITLE
About the demo of Novel View Synthesis of Human Interactions From Sparse Multi-view Videos

### ISSUE THREAD

**Issue by 1224K** [zju3dv/EasyMocap#364]
Hello @chingswy , thanks for your excellent work!

When I try to follow the tutorial [page ](https://chingswy.github.io/easymocap-public-doc/works/multinb.html) for the demo "Novel View Synthesis for Human Interaction in Sparse Multi-View Video"

I got this error, It seems that time_offset.json is missing, so I would like to ask what time_offset.json is?
![Untitled (2)](https://github.com/zju3dv/EasyMocap/assets/75677010/815962be-5d5e-479e-bbe9-ac3c470b469b)

Thank you very much!

_Originally posted by @1224K in https://github.com/zju3dv/EasyMocap/issues/356#issuecomment-1704890510_

**Comment by chingswy** [comment]
Seems the like the sep `/` and `\` error.
