### ISSUE TITLE
In extrinsic calibration, the orientation of each cute is inconsistent.

### ISSUE THREAD

**Issue by kuyum** [zju3dv/EasyMocap#369]
In extrinsic calibration, the orientation of each cute is inconsistent. To make them consistent, I have to change the orientation of the keypoints in the files which in the directory “EasyMocap\0_input\a_test\extri\chessboard”.

example as below：

![1](https://github.com/zju3dv/EasyMocap/assets/48179213/815538b9-455b-4562-8d63-bd2d3bdeff33)

![2](https://github.com/zju3dv/EasyMocap/assets/48179213/b3854f1b-a0ef-4ef2-9711-8180027a00e9)

In the first image, the blue keypoints is in the left side of the chessboard.  In the second image, the blue keypoints is in the right side of the chessboard. This make the orientation of the cutes in each image is inconsistent. And this make a fail of Mocap of Multi View.

I'm not sure if this is a bug or an inherent flaw of the chessboard. If it is a inherent flaw of the chessboard, how about using the following kind of graph to do the extrinsic calibration, this kind of graph seen to have orientation. I have seen someone using this kind of graph in his Mocap project on Youtube, but I forgot the link. It may works.
![AprilTag_1](https://github.com/zju3dv/EasyMocap/assets/48179213/f97bd67b-404d-4a13-b82c-1d07775708e9)
![AprilTag_2](https://github.com/zju3dv/EasyMocap/assets/48179213/7126499a-e424-4645-9ecf-b2fc4c8162e5)
Edit: AprilTag github link: https://github.com/AprilRobotics/apriltag

**Comment by chingswy** [comment]
Hello, you are using a symmetrical checkerboard pattern, which is incorrect.

**Comment by kuyum** [comment]
> Hello, you are using a symmetrical checkerboard pattern, which is incorrect.

Oh, my mistake! I missed something. Thank you so much for your reply.
