### ISSUE TITLE
SMPL Conversion to SMPLx or SMPL-H

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/EasyMocap#377]
@chingswy,

is it possible to change smpl to another family? like smplx maybe?   this would be great to know if that's possible here.  
I cannot use the original smpl repo since the smpl generated here is different from theirs.

do let me know. or maybe any other possible way

**Comment by Dipankar1997161** [comment]
Or maybe if you could tell me the way to create the obj files for the meshes.. that will work for me, then i can convert to smplx

**Comment by Dipankar1997161** [comment]
solved

**Comment by rexainn** [comment]
Hi, could you please tell me how did you save the mesh like obj files? I'm working on it and I'm very confused.
