### ISSUE TITLE
ModuleNotFoundError: No module named 'easymocap'

### ISSUE THREAD

**Issue by ading12** [zju3dv/EasyMocap#38]
Hi, Im stuck when trying to run
`python apps/demo/mv1p.py 0_input/sample --out 1_output/sample --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl`

It gives me this error:
`Traceback (most recent call last):
  File "apps/demo/mv1p.py", line 9, in <module>
    from easymocap.smplmodel import check_keypoints, load_model, select_nf
ModuleNotFoundError: No module named 'easymocap'`

I have tried reinstalling but same results. Any ideas?

heres the screenshot:
![image](https://user-images.githubusercontent.com/68722181/122860508-6a591700-d350-11eb-9396-2e199f9b05a0.png)

**Comment by chingswy** [comment]
Have you already run `python3 setup.py develop --user` at the root path of `EasyMocap`? See [this line](https://github.com/zju3dv/EasyMocap/blob/master/doc/installation.md#3-install)

**Comment by ading12** [comment]
Thanks! it works now.
How did I missed that one. Now I can sleep..
