### ISSUE TITLE
[Stages] Error in detect

### ISSUE THREAD

**Issue by yumfx** [zju3dv/EasyMocap#389]
Hello
I've a HD footage with one character. I've made the preprocess extract_keypoints with this result in json sequence files:
`  "filename": "images/chara1/chara1.000001.jpg",
    "height": 1080,
    "width": 1920,
    "annots": [
        {
            "personID": 0,
            "bbox": [784.41, 370.53, 953.27, 708.27, 0.97],
            "keypoints": [
              [ 845.75,  437.15,    0.96], 
              [ 866.64,  459.14,    0.88], 
              [ 825.97,  470.14,    0.88], 
              [ 803.98,  522.91,    0.91], 
              [ 814.97,  542.70,    0.94], 
              [ 907.32,  448.15,    0.91], 
              [ 946.90,  500.92,    0.92], 
              [ 920.51,  540.50,    0.91], 
              [ 883.13,  559.19,    0.80], 
              [ 858.95,  564.69,    0.84], 
              [ 863.35,  681.22,    0.93], 
              [ 878.74,  648.24,    0.45], 
              [ 907.32,  553.69,    0.80], 
              [ 938.11,  575.68,    0.87], 
              [ 938.11,  674.63,    0.92], 
              [ 836.96,  430.56,    0.95], 
              [ 850.15,  426.16,    0.96], 
              [ 830.36,  428.36,    0.86], 
              [ 867.74,  412.97,    0.97], 
              [   0.00,    0.00,    0.00], 
              [   0.00,    0.00,    0.00], 
              [   0.00,    0.00,    0.00], 
              [   0.00,    0.00,    0.00], 
              [   0.00,    0.00,    0.00], 
              [   0.00,    0.00,    0.00]
            ],
            "isKeyframe": false
        }
    ],
    "isKeyframe": false
}`

BUT when I run the following emc command
`emc --data config/datasets/svimage.yml --exp config/1v1p/hrnet_pare_finetune.yml --root ${data} --ranges 1 550 1 --subs chara`

I've and issue

`Fusing layers... 
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients
Adding AutoShape... 
[MultiStage] loading module keypoints2d
[MultiStage] loading module vis2d
[MultiStage] loading module infer
[Run] dataset has 549 samples
[Run]:   0%|                                                                                                                             | 0/549 [00:00<?, ?it/s]
[Stages] Error in detect
[Run]:   0%|                                                                                                                             | 0/549 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/.../EasyMocap/myeasymocap/stages/basestage.py", line 77, in at_step
    output = model(**inputs)
  File "/.../EasyMocap/myeasymocap/backbone/yolo/yolo.py", line 115, in __call__
    select = self.select_bbox(select, res, imgnames[nv])
  File "/.../EasyMocap/myeasymocap/backbone/yolo/yolo.py", line 147, in select_bbox
    frame = int(os.path.basename(imgname).split('.')[0])
ValueError: invalid literal for int() with base 10: 'chara'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../envs/easymocap2/bin/emc", line 33, in <module>
    sys.exit(load_entry_point('easymocap', 'console_scripts', 'emc')())
  File "/.../EasyMocap/apps/mocap/run.py", line 114, in main_entrypoint
    process(dataset, model, args)
  File "/.../EasyMocap/apps/mocap/run.py", line 12, in process
    ret = model.at_step(data, i)
  File "/.../EasyMocap/myeasymocap/stages/basestage.py", line 80, in at_step
    raise Exception
Exception
`

Does anyone have an idea what's going on?
Thank you for your help!

**Comment by raflitp** [comment]
Have you able to solve this error ??

Traceback (most recent call last):
File "/.../envs/easymocap2/bin/emc", line 33, in
sys.exit(load_entry_point('easymocap', 'console_scripts', 'emc')())
File "/.../EasyMocap/apps/mocap/run.py", line 114, in main_entrypoint
process(dataset, model, args)
File "/.../EasyMocap/apps/mocap/run.py", line 12, in process
ret = model.at_step(data, i)
File "/.../EasyMocap/myeasymocap/stages/basestage.py", line 80, in at_step
raise Exception
Exception

**Comment by yumfx** [comment]
Yes but I can't remember how ...
It was a long time ago :D
