### ISSUE TITLE
visualize的视角很奇怪

### ISSUE THREAD

**Issue by rexainn** [zju3dv/EasyMocap#392]
我是在服务器上进行visualize，可正常打开vis_server和发送数据，但是当我按下a按键想要转动视角的时候，发现视角很奇怪。是我的使用方法不对吗？按下a他是会自动转视角还是按照我的鼠标转动方向转视角。

![image](https://github.com/zju3dv/EasyMocap/assets/111296458/ac335558-ae24-4d3b-b6fb-6fc19b73d460)

**Comment by chingswy** [comment]
a的方向会根据相机参数的方向进行旋转，如果相机标定的时候的z轴不是垂直于地面向上，那么可能就不是正常的旋转了。
