### ISSUE TITLE
Multi-person tracking of body and face

### ISSUE THREAD

**Issue by ChristianNSchmitz** [zju3dv/EasyMocap#395]
We would like to perform body and facial tracking of video footage with more than one person included over a period up to 2 hours. We would like to ask you whether such a duration is already possible with EasyMocap and whether facial tracking is also supported with the mediapipe-wrapper? Thanks a lot!

**Comment by chingswy** [comment]
Thank you for your inquiry. Currently, EasyMocap does not support multi-person facial tracking.
