### ISSUE TITLE
可以跳过visualization吗，centos服务器安装mesa丢了半条命都没成功

### ISSUE THREAD

**Issue by forrest-lam** [zju3dv/EasyMocap#398]
RT，是否有一个开关可以skip visualization，只生成骨骼动画数据就可以了

**Comment by chingswy** [comment]
可能可以换成egl? Check [here](https://pyrender.readthedocs.io/en/latest/examples/offscreen.html#offscreen-guide)

**Comment by forrest-lam** [comment]
换过，也报错，ValueError: Invalid device ID (0)
<img width="1286" alt="image" src="https://github.com/zju3dv/EasyMocap/assets/135090192/c9efacb5-d6a6-495b-9acd-7da6d464f173">
本地是有GPU的

**Comment by chingswy** [comment]
是不是系统版本太新了。。我在Ubuntu22.04上也跑不了了。

**Comment by forrest-lam** [comment]
解决了，之前用的是虚拟GPU，egl识别不出，换一台机器就好了
