### ISSUE TITLE
Quickstart giving Error

### ISSUE THREAD

**Issue by kmcclenn** [zju3dv/EasyMocap#399]
I am trying to use the EasyMocap library to perform some video analysis. However, it is giving me an error when I try the quickstart. Do you know why this could be? 

![image](https://github.com/zju3dv/EasyMocap/assets/63942422/260dc667-7561-4673-8315-19d093202089)

**Comment by chingswy** [comment]
https://github.com/mkocabas/PARE/releases/tag/v0.1
Here is the new download link.
