### ISSUE TITLE
Can it work with 2 or 3 cameras?

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/EasyMocap#4]
I'm trying to undertand how to calibrate the cameras, but I dont have a way to record with 4 cameras.
Is it possible to make it work properly with 2 or 3 cameras only?

thanks a lot, by far this solution seems the best on I've seen.

**Comment by chingswy** [comment]
You can try it with only 2 or 3 cameras. It is supposed that the reconstruction quality is not as good as our example, which utilizes 23 cameras.

**Comment by carlosedubarreto** [comment]
Thanks a lot!!!
