### ISSUE TITLE
单目视频运行时需要下载的文件已经被删除

### ISSUE THREAD

**Issue by Livertl** [zju3dv/EasyMocap#402]
https://www.dropbox.com/s/aeulffqzb3zmh8x/pare-github-data.zip 无法下载
![9F79E537-C200-49FD-A026-2BDECFBDC42A](https://github.com/zju3dv/EasyMocap/assets/54663410/a2bf0d21-8e31-4e5e-924a-c941dafdb944)

![7429A7EE-C54E-4E90-AB50-D6AC04114A53](https://github.com/zju3dv/EasyMocap/assets/54663410/5ed1eb23-c102-457a-81c4-182781aea927)

**Comment by chingswy** [comment]
https://github.com/mkocabas/PARE/releases/tag/v0.1
Here is the download link
