### ISSUE TITLE
Missing pare_w_3dpw_config.yaml

### ISSUE THREAD

**Issue by raflitp** [zju3dv/EasyMocap#406]
Hi I'm trying to use the monocular script from the website but I found an error with missing yaml file, I don't know where to get this checkpoint file can anyone give me a download link. I've tried searching on google it told me to download from Virtual Human website but I can't find the yaml file

**Comment by NjustLocalSnake** [comment]
I have encountered the same problem. Have you solved it? I look forward to your reply!

**Comment by 4698to** [comment]
gdown 1qIq0CBBj-O6wVc9nJXG-JDEtWPzRQ4KC
unzip pare-github-data.zip
