### ISSUE TITLE
Demo on monocular videos  Error

### ISSUE THREAD

**Issue by NjustLocalSnake** [zju3dv/EasyMocap#409]
When I run this command
![1](https://github.com/zju3dv/EasyMocap/assets/48049273/89364ee0-f337-4f9d-b3ce-e490fbfe09a7)
![image](https://github.com/zju3dv/EasyMocap/assets/48049273/1e9e9605-863d-4461-8c51-6f95194ef6c4)

This download link is invalid and the file no longer exists. Where can I find it? Thank you very much!

**Comment by Lucas-1048** [comment]
Hey, how did you solve it? I look forward to your reply!

**Comment by NjustLocalSnake** [comment]
> Hey, how did you solve it? I look forward to your reply!嘿，您是如何解决的？我期待你的回复！

https://github.com/mkocabas/PARE/releases/tag/v0.1
Here is the download link

**Comment by Lucas-1048** [comment]
Thanks a lot!
