### ISSUE TITLE
Quick start error

### ISSUE THREAD

**Issue by Elsaam2y** [zju3dv/EasyMocap#41]
Thanks for this amazing work. I am just a bit confused as I keep getting this error after running the script to extract the SMPLx parameters. The problem is within this function smpl_from_keypoints3d2d as it returns:  
load_weight_shape() missing 1 required positional argument: 'opts'. I am not sure what I am missing. Any guidance or hints would be appreciated. 

Thanks

**Comment by chingswy** [comment]
Fix it. Thank you!
