### ISSUE TITLE
Camera calibration

### ISSUE THREAD

**Issue by raflitp** [zju3dv/EasyMocap#410]
Hi I've encountered some problem while doing the calibration, I entered the checkerboard as 9,6 but it can't detect any chessboard with 9,6 pattern for intrinsic calibration. When I tried using 8,5 for intrinsic it works and reads the checkerboard but the final result of calibration with extrinsic shows the camera a bit distorted. 

![000000](https://github.com/zju3dv/EasyMocap/assets/43334514/270daa89-0cae-4918-af1d-d017f43fb60d)

Here is the intrinsic for the camera picture. Am I missing something or should I do better setup ??
This is the code that I used : python apps/calibration/detect_chessboard.py input/calib_intri --out output/calibration --pattern 9,6 --grid 0.15

Can anyone help with this @chingswy

**Comment by raflitp** [comment]
![image](https://github.com/zju3dv/EasyMocap/assets/43334514/ccb8e06a-1d07-4d0f-9de5-1c4c47af4548)
This is the result of calibration you can see the distorted camera, not sure what I did wrong, can anyone help me pls ??

**Comment by chingswy** [comment]
Can you place your chessboard to different positions? It's so strange that the opencv can't detect the corner.

**Comment by raflitp** [comment]
> Can you place your chessboard to different positions? It's so strange that the opencv can't detect the corner.

I've tried to change the position of the checkerboard but still no luck, the opencv doesn't detect the chessboard as 9x6

**Comment by raflitp** [comment]
![000000](https://github.com/zju3dv/EasyMocap/assets/43334514/21f57141-7fa0-4376-9cfa-12964bd03e39)
Even on this close it doesn't detect the chessboard as 9x6 it's really weird

**Comment by raflitp** [comment]
I've found the problem and solution to this, not sure how to explain it but on every sides of the checkerboard need to have a white space to make opencv to detect the corners of the checkerboard. Not sure if it's understandable but here I show the example of what we did to the checkerboard to get it detect 9x6 checkerboard

![000081](https://github.com/zju3dv/EasyMocap/assets/43334514/ab2f568e-f5ef-461c-a869-0ce2100b6f22)

**Comment by chingswy** [comment]
Congratulate! I will add it to the documents.
