### ISSUE TITLE
Calibration Distortion

### ISSUE THREAD

**Issue by raflitp** [zju3dv/EasyMocap#413]
Hi, I'm using 8 GoPro Hero 12 to record from 8 angles. But it seems there's some trouble with the calibration when I check the calibration it shows the distortion like the image below :

![image](https://github.com/zju3dv/EasyMocap/assets/43334514/da6db2b2-6737-408b-aa8a-90503723ae46)

What we've done, intrinsic we just put the chessboard infront of the camera like this, no movement just stay still :

![000049](https://github.com/zju3dv/EasyMocap/assets/43334514/83cfc120-b7bb-46fe-9804-4d8cd31d29ff)

Extrinsic we just put the checkerboard on the floor where all cameras can see it, we use Linear on the gopro to reduce distortion on the lens and we use the highest resolution on it.

Is there a problem with the intrinsic calibration or extrinsic ? because I've got no clue about this, any suggestions or help are appreciated !! @chingswy

**Comment by chingswy** [comment]
Hello, when you calibrate the intrinsic parameters, you should move your calibration board to cover all the image range.

**Comment by raflitp** [comment]
![image](https://github.com/zju3dv/EasyMocap/assets/43334514/3f8fc178-7e8f-465c-99f0-b7ff4a3f33a6)

I've tried to move it calibration board to cover all the frames but it still shows some distortion but it looks better now and the result from extri and intri shows below : 

![image](https://github.com/zju3dv/EasyMocap/assets/43334514/f80ec683-6930-4063-8096-4c895b33fc29)

**Comment by chingswy** [comment]
You should caputre more (~200) different images to calibrate the intrinsic parameters.

**Comment by raflitp** [comment]
I've captured around 900 frame so should I use --num 200 and use --sample or not '??

**Comment by raflitp** [comment]
![image](https://github.com/zju3dv/EasyMocap/assets/43334514/094abb72-7c59-44d6-8ed7-1ad042516814)

This is the result when I run the code like this : 
python apps/calibration/calib_intri.py input/calib-intri-final --num 200
