### ISSUE TITLE
Multiview Multiperson Problem

### ISSUE THREAD

**Issue by raflitp** [zju3dv/EasyMocap#415]
Hi @chingswy I have some problem with mvmp method that I tried to run. In the process the person id keeps changing each person, some people are not detected even I've used max person to 8. Not sure if there's some rule that I missed on the start of the video or is this some problem with the method that we used.

Here's the keypoints2d where it read almost all the person inside the frame

![000000](https://github.com/zju3dv/EasyMocap/assets/43334514/f84b3228-b0d6-486b-b1e9-104ec57f9063)

But in vis_repro the person that detected are missing : 

![000000](https://github.com/zju3dv/EasyMocap/assets/43334514/ffb76953-fc44-4bcd-b4cd-fa1322df4879)

Script that I used : soccer1_6.yml (I've changed the max person and final max person to "8")
Cameras used : 7 cameras all calibrated
1 thing that I noticed in the script "dist_max" and "dist_track" what does it do since I didn't change it at all or is there a maximum to amount of person to be detected ?? I hope there's a fix or a solution to my problem :((

**Comment by xh57** [comment]
Hi @raflitp 
I was wondering if you might still have a copy of the demo data, especially the MVMP examples, and would be willing to share it with me. Any help would be greatly appreciated.
Thank you for your time and consideration.
