### ISSUE TITLE
Can I use it in WIN

### ISSUE THREAD

**Issue by zhanghongyong123456** [zju3dv/EasyMocap#42]
Can I install and use it under Windows 10

**Comment by chingswy** [comment]
@carlosedubarreto have tried this under Windows.

**Comment by carlosedubarreto** [comment]
Hi @zhanghongyong123456  I've made a playlist explaining instalation and calibration on easymocap.

Its a raw recording, long and difficult to watch but if you want to use it, I talk about several problems that you might find.

https://youtube.com/playlist?list=PLYzax7LPWaADMqDjc9rnAOC3tsd35zZGL

**Comment by zhanghongyong123456** [comment]
> @carlosedubarreto have tried this under Windows.

Thank you very much for your reply. OK, I will learn the installation tutorial from the predecessors

**Comment by zhanghongyong123456** [comment]
> Hi @zhanghongyong123456 I've made a playlist explaining instalation and calibration on easymocap.
> 
> Its a raw recording, long and difficult to watch but if you want to use it, I talk about several problems that you might find.
> 
> https://youtube.com/playlist?list=PLYzax7LPWaADMqDjc9rnAOC3tsd35zZGL
Thank you very much for your tutorial. I will install it according to the tutorial
