### ISSUE TITLE
Error on keypoints2d detection

### ISSUE THREAD

**Issue by raflitp** [zju3dv/EasyMocap#422]
Hi @chingswy, first of all thank you for your hard work into this project !! It's been amazing times since I know this project !!

I tried to record and process a 2 person scene with some props inside the set, we use 8 cameras to record it.
I got an error when running the emc config for mvmp, it seems about the keypoints error here :

Traceback (most recent call last):
  File "d:\easymocap\myeasymocap\stages\basestage.py", line 77, in at_step
    output = model(**inputs)
  File "d:\easymocap\myeasymocap\backbone\vitpose\vit_moe.py", line 602, in __call__
    return self.estimate_keypoints(bbox, images, imgnames)
  File "d:\easymocap\myeasymocap\backbone\vitpose\vit_moe.py", line 579, in estimate_keypoints
    kpts = np.zeros((_bbox.shape[0], self.num_joints, 3))
File "C:\Users\user\.conda\envs\easymocap\lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MyViT' object has no attribute 'num_joints'

I've tried to check the codes, it seems it trace back to at_steps in keypoints2d to read key_from_previous : [bbox]. I've found the problem is on the 7th camera which one of the person get blocked by an object causing yolo to not detect the person. Here's the picture :

![image](https://github.com/zju3dv/EasyMocap/assets/43334514/9c91ab5d-7ede-45a7-bc37-3b19c769cc71)
Left one is the 7th camera, the right one is the 8th camera.

I've tried several changes inside the code to help it, but I can't find the solution. If you know how to please let me know !! Thanks !!

**Comment by saswat0** [comment]
@raflitp Did you find a workaround for this issue?

**Comment by yumfx** [comment]
same problem here. Have you find an issue @raflitp ?
