### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by vinayakagarwal12** [zju3dv/EasyMocap#43]
Hello, I was running the easy mocap. I was doing the intrinsic calibration of camera using the script calib_intri.py but got this error. Anyone found similar issues or help me in solving this issue..
Thanks..
![image](https://user-images.githubusercontent.com/59793707/124351715-a4140280-dc19-11eb-9f99-612e982f65e7.png)

**Comment by chingswy** [comment]
What is your version of OpenCV?

**Comment by vinayakagarwal12** [comment]
Mine version was 4.1.2 but when I changes to 4.5 .2 it worked

**Comment by chingswy** [comment]
OK. I will update the `FileStorage` class later because different versions of OpenCV have different manners.

**Comment by chingswy** [comment]
OK. I will update the `FileStorage` class later because different versions of OpenCV have different manners.
