### ISSUE TITLE
SPIN model

### ISSUE THREAD

**Issue by chen-hao-ran** [zju3dv/EasyMocap#434]
![image](https://github.com/user-attachments/assets/832214bf-9dcb-4dea-a3de-e13076d1c374)
Hi, Why the SPIN model is needed here?

**Comment by raflitp** [comment]
SPIN model are used for monocular videos, it helps to reconstruct the pose and shape from the 2D images

**Comment by chen-hao-ran** [comment]
> d

Thanks a lot! I get it.

**Comment by chen-hao-ran** [comment]
> SPIN model are used for monocular videos, it helps to reconstruct the pose and shape from the 2D images

Thanks a lot! I get it.
