### ISSUE TITLE
Can't detect chessboard

### ISSUE THREAD

**Issue by J18040744MCV** [zju3dv/EasyMocap#440]
I've filmed it very carefully without motion blur and with stable lighting - still can't detect - tried 2 configurations 22,10 and 5,5 - 5cm squares.

**Comment by J18040744MCV** [comment]
![GOPR49360048](https://github.com/user-attachments/assets/bb7b52cf-40bb-459a-880a-d29ef2dc2b27)
![20241116_004412_GALAXY285](https://github.com/user-attachments/assets/16ccb004-4b01-4cb5-898a-4a7b25e3c79a)
![GOPR4935 MP4_snapshot_00 09 052](https://github.com/user-attachments/assets/f4235bb2-6f35-496b-a073-9727994fb3cc)
![20241115_171516_GALAXY mp4_snapshot_00 09 709](https://github.com/user-attachments/assets/4564f94f-2a6b-45e1-a8cc-464dd6419585)

**Comment by J18040744MCV** [comment]
found a discussion https://github.com/zju3dv/EasyMocap/issues/385

**Comment by junziAFAN** [comment]
> I've filmed it very carefully without motion blur and with stable lighting - still can't detect - tried 2 configurations 22,10 and 5,5 - 5cm squares.
I've seen it before, and no matter what, I can't identify it, and finally record static video and intercept hundreds of photos, and there's always one that can be identified
