### ISSUE TITLE
"pare-github-data.zip" The original link to this file is broken and cannot be found elsewhere

### ISSUE THREAD

**Issue by junziAFAN** [zju3dv/EasyMocap#441]
"pare-github-data.zip" The original link to this file is broken and cannot be found elsewhere

**Comment by chingswy** [comment]
Hello, please check [here](https://github.com/mkocabas/PARE/blob/master/scripts/prepare_data.sh).

```bash
gdown 1qIq0CBBj-O6wVc9nJXG-JDEtWPzRQ4KC
unzip pare-github-data.zip
```

and move it to `models/pare`
