### ISSUE TITLE
mode openpose change yolo-hrnet  error

### ISSUE THREAD

**Issue by zhanghongyong123456** [zju3dv/EasyMocap#45]
When I ran the script extract_video-.py, I changed the mode default openpose to yolo-hrnet and this error occurred. I'm not sure if this is caused by missing files
![54](https://user-images.githubusercontent.com/48466610/124548079-cac37a80-de5f-11eb-84b0-8d660bc33f3d.png)

**Comment by chingswy** [comment]
I have not released the yolo-hrnet part. Please use openpose model.

**Comment by zhanghongyong123456** [comment]
> I have not released the yolo-hrnet part. Please use openpose model.

Thank you very much for your prompt reply. 
I want to realize the multi-person pose estimation of my own data set  “Multiple views of multiple people“  This branch，
I noticed that Openpose also has 3D reconstruction，like this  
![55](https://user-images.githubusercontent.com/48466610/124568530-9a87d600-de77-11eb-9de2-8b51b13b7180.png)
1.  I wonder if our implementation is the same as the OpenPose implementation
2. What if i want to achieve real-time attitude estimation，like this link 
https://www.youtube.com/watch?v=Kmi8Skz4cLQ , 
3. How do I implement multi-camera real-time attitude estimation

**Comment by chingswy** [comment]
1. OpenPose's implementation is just for single person.
2. The real-time version is hard to implement. We implement this by add a real-time dataset which reads the outputs of IP camera and detects the 2D keypoints. Then the reconstruction part and visualization part are both released. You can use them directly.

**Comment by zhanghongyong123456** [comment]
> 1. OpenPose's implementation is just for single person.
> 2. The real-time version is hard to implement. We implement this by add a real-time dataset which reads the outputs of IP camera and detects the 2D keypoints. Then the reconstruction part and visualization part are both released. You can use them directly.
Thank you for your reply. I understand the difference between them.
Can I get real-time 2D pose estimation from multiple cameras through OpenPose? Is this possible
like this link
https://www.youtube.com/watch?v=Kmi8Skz4cLQ ,

**Comment by zhanghongyong123456** [comment]
> Yes.

OK,Thanks again for your answer. I'll have a try

**Comment by zhanghongyong123456** [comment]
> > Yes.
> 
> OK,Thanks again for your answer. I'll have a try



> Yes.
Hello, I have a question. If I process my own data set, I only have videos, after running the command
data=/path/to/data
python3 scripts/preprocess/extract_video.py ${data} --no2d
![57](https://user-images.githubusercontent.com/48466610/124709856-91a60b80-df2e-11eb-8bb1-7800b216000d.png)

 add --no2d  Parameter, I don't do OpenPose pose estimation, I won't get the annots folder that I need later.
![56](https://user-images.githubusercontent.com/48466610/124709878-98cd1980-df2e-11eb-8551-69cda4f8f86b.png)

Or there are other ways to get the annots folder without having to perform an openpose operation

**Comment by chingswy** [comment]
1. For yolo, you can use [PyTorch_YOLOv4](https://github.com/WongKinYiu/PyTorch_YOLOv4)
2. For HRNet, you can use [HRNet](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch)
And then convert the outputs as our format.

**Comment by zhanghongyong123456** [comment]
> 1. For yolo, you can use [PyTorch_YOLOv4](https://github.com/WongKinYiu/PyTorch_YOLOv4)
> 2. For HRNet, you can use [HRNet](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch)
>    And then convert the outputs as our format.

That is, there are three ways to get annots: 1.openpose 2. yolov4 3. HRNet，Which one has the advantage over implementing real-time multiplayer detection，Can you give me some advice

**Comment by chingswy** [comment]
In our real-time detection, we use the TensorRT version of OpenPose. It can run in real-time.

**Comment by zhanghongyong123456** [comment]
> In our real-time detection, we use the TensorRT version of OpenPose.

ok 

> In our real-time detection, we use the TensorRT version of OpenPose.

ok，Thank you very much for your advice.

**Comment by zhanghongyong123456** [comment]
> > In our real-time detection, we use the TensorRT version of OpenPose.
> 
> ok
> 
> > In our real-time detection, we use the TensorRT version of OpenPose.
> 
> ok，Thank you very much for your advice.
I'm sorry to bother you again，if I want to realize real-time attitude estimation. 1. What brand of camera do you choose? Is the quantity of four OK? 2.Is your real-time code implemented in Python or C ++? 3. For the estimation of Openpose pose, can I get the data directly without saving it as a JSON file
![58](https://user-images.githubusercontent.com/48466610/124892151-334f5a80-e00c-11eb-8198-a0fec9214dcc.png)

**Comment by chingswy** [comment]
1. We use 8 cameras for real-time version.
2. 3. See [OpenPose Python api](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_python/01_body_from_image.py), [OpenPose C++ api](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_cpp/01_body_from_image_default.cpp)

**Comment by zhanghongyong123456** [comment]
> 1. We use 8 cameras for real-time version.
> 2. 1. See [OpenPose Python api](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_python/01_body_from_image.py), [OpenPose C++ api](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_cpp/01_body_from_image_default.cpp)

thanks,i will look  into it

**Comment by zhanghongyong123456** [comment]
> 1. We use 8 cameras for real-time version.
> 2. 1. See [OpenPose Python api](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_python/01_body_from_image.py), [OpenPose C++ api](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_cpp/01_body_from_image_default.cpp)
Hello, I would like to ask how your video push stream is realized. I only use python-OpenCV multi-threading to display video delay of 400ms, but I haven't used Openpose pose estimation. Is it norma？

**Comment by chingswy** [comment]
We use cv::cudacodec::VideoReader.

**Comment by zhanghongyong123456** [comment]
> We use cv::cudacodec::VideoReader.

Thanks, I want to know whether you modify directly in OpenPose or read the video stream with OpenCv first and then use OpenPose for pose estimation. Can I use bin\ OpenPoseMo.exe to achieve this?Or do I need to compile the source code myself (OpenCV and Openpose)?

**Comment by zhanghongyong123456** [comment]
> > We use cv::cudacodec::VideoReader.
> 
> Thanks, I want to know whether you modify directly in OpenPose or read the video stream with OpenCv first and then use OpenPose for pose estimation. Can I use bin\ OpenPoseMo.exe to achieve this?Or do I need to compile the source code myself (OpenCV and Openpose)?
Not so familiar with C++,

**Comment by zhanghongyong123456** [comment]
> > > We use cv::cudacodec::VideoReader.
> > 
> > 
> > Thanks, I want to know whether you modify directly in OpenPose or read the video stream with OpenCv first and then use OpenPose for pose estimation. Can I use bin\ OpenPoseMo.exe to achieve this?Or do I need to compile the source code myself (OpenCV and Openpose)?
> > Not so familiar with C++,
Is this project achievable，
https://github.com/batselem/TensorRT-Openpose，Can you give me some advice，thanks a lot

**Comment by chingswy** [comment]
We have a member who is familiar with C++ and accelerates OpenPose by TensorRT. Not use that repo.

**Comment by zhanghongyong123456** [comment]
> We have a member who is familiar with C++ and accelerates OpenPose by TensorRT. Not use that repo.

thanks a lot
