### ISSUE TITLE
How to transform smpl from the world coordinate to the smpl coordinate?

### ISSUE THREAD

**Issue by ljq2020** [zju3dv/EasyMocap#48]
Hi,

Thanks for the great work! I have a question about how to get the params['Rh'] and params['Th'] when I want to transform smpl from the world coordinate to the smpl coordinate. There are camera intrinsic parameter, extrinsic parameter and original SMPL parameters(pose, betas), and I want to get the new global rotaion and translation.

**Comment by chingswy** [comment]
In our representation, it's simple by using `R^-1(X - T)`. This [function](https://github.com/zju3dv/EasyMocap/blob/master/easymocap/smplmodel/body_model.py#L262) can help you to convert SMPL parameters to `R, T`

**Comment by ljq2020** [comment]
Thank you very much for your prompt reply.
In this function(`def convert_from_standard_smpl(self, poses, shapes, Rh=None, Th=None, expression=None)`), are the Rh and Th parameters the camera extrinsic parameters? or they should be None?

**Comment by chingswy** [comment]
Just None
