### ISSUE TITLE
 smpl  model

### ISSUE THREAD

**Issue by wangdong0556** [zju3dv/EasyMocap#49]
Hello, I'm glad to see such an excellent project. When I run it, I find that the smpl model   "data / smplx / smpl does not exist!" is missing Which smpl model is used in this project? Can you provide the download link, thank you！

**Comment by carlosedubarreto** [comment]
Hello..

You must follow this instruction
https://github.com/zju3dv/EasyMocap/blob/master/doc/installation.md#01-smpl-models
