### ISSUE TITLE
Triangulated Points are crazy

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/EasyMocap#5]
Hi, thanks a lot for such great code.

I would like to ask for help. I did my intrinsic lens calibration, using a tutorial on OpenCV page, and dit the extrinsic calibration with the code provided here in the git hub, but my result is weird.

When I see the imagens on the keypoints images they look fine, like this one
![image](https://user-images.githubusercontent.com/4061130/110551644-a60b0080-8114-11eb-88ac-fe6bb5a50f61.png)

When I see the "repro" folder, the image looks like this (insted of having the skeleton on the body, there is only a point folllowing my face)
![image](https://user-images.githubusercontent.com/4061130/110551729-d3f04500-8114-11eb-874a-cb05379a7655.png)

And when I render with  SMPL, seems that the model, goes where that white dot was
![image](https://user-images.githubusercontent.com/4061130/110551621-9ab7d500-8114-11eb-8856-af9efa71cbff.png)

I dont know what to do know. Can you give me some directions?

Thanks a lot

**Comment by chingswy** [comment]
I think there may be some bugs in you extrinsic parameters. The unit of length must be **meter**. If there still exist bugs, you can share me a sample data orgnized as mine.
