### ISSUE TITLE
The up vector for the world coordinate and the the orientation of cameras and fitted SMPL.

### ISSUE THREAD

**Issue by ShenhanQian** [zju3dv/EasyMocap#51]
After successfully running the _Quick Start_ code on the _example dataset_, I am trying to render the same views with fitted SMPL parameters and camera matrices using PyTorch3D. However, I encounter some problems with the transformation between coordinates.

First, I use the `SMPLLayer` from this repo to generating an SMPL mesh from `Rh`, `Th`, `Pose`, `Shape` parameters. This process rotates the mesh to head up to the positive-Z direction from the positive-Y direction in the original SMPL coordinate. Is this relevant to the up vector of the world coordinate? And how does this world coordinate's configuration like (up vector, ground plane)? 

Second, in this repo you render SMPL with _PyRender_, but I have difficulty in render the same view with PyTorch3D. According to your code, you first rotate all the vertices for 180 deg around the X-axis, then transform them with the inverse transform of the RT matrix of the camera. What is the goal of this rotation and why not directly feeding the extrinsic parameters into the camera?

Thanks in advance!

**Comment by chingswy** [comment]
1. The ground plane is `z=0`, the up vector is `[0, 0, 1]^T`. You can check the world coordinate with our 3D visualization tool using Open3D.
2. In my experiments, I found that if directly feed the extrinsic parameters into the camera, the render results will be wrong and I don't no why. So I just convert the objects to the camera coordinate and render them. 
3. Rotate all the vertices for 180 deg around the X-axis is a common step, like [this line](https://github.com/mkocabas/VIBE/blob/master/lib/utils/renderer.py#L82).
4. If you use PyTorch3D, just calculate the mesh with `Rh, Th, poses, shapes`, and pass the mesh to the renderer with `K, R, T`.

**Comment by ShenhanQian** [comment]
Thanks for your rapid reply. But I am still confused about the rotation around the X-axis. According to your repo, you only conduct this rotation when rendering the mesh. But how can this be consistent with the parameters fitted without rotated SMPL?

**Comment by ShenhanQian** [comment]
Currently, in order to render the same view with the parameters of cameras and SMPL using PyTorch3D, I have to add an additional rotation by manually check the coordinates of the vertices. 
Trying to understand the basic reason for the rotation, I went through the code for SMPL fitting, but I couldn't find any clue of the flipping around the X-axis. 

I would appreciate it a lot if anyone can help spot out what I have missed.

**Comment by chingswy** [comment]
I don't know this either. What the additional rotation you added?

**Comment by ShenhanQian** [comment]
Here is my code snippet:

``` python
from easymocap.mytools.camera_utils import read_camera
from pytorch3d.renderer import PerspectiveCameras


cam_intri = os.path.join(self.data_root, 'intri.yml')
cam_extri = os.path.join(self.data_root, 'extri.yml')
cam_params = read_camera(cam_intri, cam_extri)

cam_names = cam_params.pop('basenames').keys()
cameras = {}
for cam_name in cam_names:
    param = cam_params[cam_name]

    # intrinsic parameters
    image_size = torch.Tensor((1024, 1024))
    focal_length = torch.Tensor([param['K'][0, 0], param['K'][1, 1]])
    principal_point = torch.Tensor(param['K'][:2, 2])

    # extrinsic parameters
    R = torch.Tensor(param['R']).transpose(0,1)  # R required by PyTorch3D is the transpose of that from EasyMocap
                                                 # because the implementation conduct matrix multiplication from 
                                                 # the right side of X:
                                                 #                       x = K (XR + T)
    T = torch.Tensor(param['T'])

    # additional rotation
    R_ = RotateAxisAngle(180, 'Z').get_matrix()[0, :3, :3]
    R = R @ R_
    T = R_ @ T

    camera = {
                'R': R,
                'T': T.squeeze(-1),
                'focal_length': focal_length,
                'principal_point': principal_point,
                'image_size': image_size,  # PyTorch3D needs this to compute K in the pixel space
            }
    cameras[cam_name] = camera

    cameras = PerspectiveCameras(**cameras)


```

As shown above, I always need to rotate along the Z-axis in the end to obtain the right result.

Note that I also tried to directly transform the vertices into camera space with [R, T] in the same way as your code does for SMPL rendering, and the additional rotation is always needed.

``` python
def get_smpl_mesh(frame_id): 
    params_json = os.path.join(data_root, 'smplx/smpl/%06d.json' % (frame_id))
    param = json.load(open(params_json, 'r'))[0]

    verts = torch.Tensor(body_model(return_verts=True, return_tensor=False, **param))
    faces = torch.Tensor(body_model.faces.astype(np.int64))[None]

    verts = verts.bmm(R) + T.transpose(1,2)  # transform verts into the camera space
    verts = RotateAxisAngle(180, 'Z').transform_points(verts)  # an additional rotation is also needed to get consistent results

    mesh = Meshes(verts=verts, faces=faces)
    return mesh
``` 

For my code, both methods produce consistent results, and now the only thing that confuses me is the additional rotation that I work out by exhaustive observation.

**Comment by chingswy** [comment]
Check [this line](https://github.com/facebookresearch/pytorch3d/blob/2f668ecefe9898e2224b35a6608937a44e5d8109/pytorch3d/renderer/cameras.py#L267) in pytorch3d.
The set the `screen_x = ... ( 1 - cam_x), screen_y = ... (1 - cam_y)`. So you should rotate around the z-axis, where the rotation matrix is:
```
-1  0 0
 0 -1 0
 0  0  1
```

**Comment by ShenhanQian** [comment]
Yes, this is the key point! Many thanks! Here is a further explanation of the problem:

![image](https://user-images.githubusercontent.com/23174052/126107182-46fc5d88-eaef-432c-afc6-3710edddcb07.png)

**Comment by chingswy** [comment]
Thanks for your explanation!
