### ISSUE TITLE
Error When use setup.py

### ISSUE THREAD

**Issue by eragondr** [zju3dv/EasyMocap#53]
I created a new environment with python 3.7 then i  have some error when use : python setup.py develop --user ( can not use python3)
And i have this one 
![image](https://user-images.githubusercontent.com/28474355/126034038-d688399d-8693-4a67-a093-056b57a87e03.png)

**Comment by chingswy** [comment]
I add `easymocap/__init__.py` now. Please retry.

**Comment by eragondr** [comment]
seen like it works now 
![image](https://user-images.githubusercontent.com/28474355/126040599-e77156c9-a481-4782-a0c1-99b5f201f526.png)

Thanks for the support :)
