### ISSUE TITLE
About camera parameters

### ISSUE THREAD

**Issue by BoMingZhao** [zju3dv/EasyMocap#55]
Hi！
After run the demo, I have a question about the camera parameters. Whether the rotation vector transforms the camera coordinate to the world coordinate or transforms the world coordinate to the camera coordinate? Because I found that my dataset provides world to camera rotation vector, maybe need to inverse.

**Comment by chingswy** [comment]
We follow this:
```bash
X_cam = RX_world + T
```

**Comment by BoMingZhao** [comment]
ok. Thanks!
