### ISSUE TITLE
The output is all zeros

### ISSUE THREAD

**Issue by BoMingZhao** [zju3dv/EasyMocap#56]
Hi.
After rendering, the output keypoints are all 0. Is there any possible error that could cause this problem？

**Comment by chingswy** [comment]
Please add flag `--vis_det --vis_repro --vis_smpl --verbose` for debug and provide more information.

**Comment by BoMingZhao** [comment]
So I find something strange, my output detec file have no skeleton on the body
![image](https://user-images.githubusercontent.com/26064261/126750710-b7ded154-7d88-4221-b64f-7ab1bcd87063.png)
And the repro is like this：
![image](https://user-images.githubusercontent.com/26064261/126750862-23e8142a-9bcf-42c7-8918-86a159593a01.png)
I added flag --vis_det --vis_repro --vis_smpl --verbose for debug,  it's just output loss functions.

**Comment by chingswy** [comment]
The unit of extrinsic parameters must be `meter`. You should check it.

**Comment by BoMingZhao** [comment]
> The unit of extrinsic parameters must be `meter`. You should check it.

sorry, what resolution do your data use?

**Comment by chingswy** [comment]
We use `1024x1024` or `1920x1080`

**Comment by BoMingZhao** [comment]
> We use `1024x1024` or `1920x1080`

Will it work if I change MAX_REPRO_ERROR? Because I found that check_repro_error sets all keypoints to 0.(I use 512 * 512 data)

**Comment by chingswy** [comment]
You can try it.

**Comment by BoMingZhao** [comment]
![image](https://user-images.githubusercontent.com/26064261/127613299-67ef7c28-19c6-4dce-b2f2-fd9137bb7523.png)

I fixed some intri parameters bug and got this repro. It seems that keypoints3D is not very accurate, and I can’t render the smpl model either

**Comment by MrMorning** [comment]
Hi Boming, I suspect that your camera parameter still has some errors, please carefully check them in rendering.
Here are some of the expected results if your parameters are correct:
![image](https://user-images.githubusercontent.com/8966584/127617654-044c81e7-218d-432f-bdf5-ef8e94d8676d.png)
![image](https://user-images.githubusercontent.com/8966584/127617714-011deac0-9687-4393-a53f-a6e6adf6b3d2.png)

**Comment by BoMingZhao** [comment]
> Hi Boming, I suspect that your camera parameter still has some errors, please carefully check them in rendering.
> Here are some of the expected results if your parameters are correct:
> ![image](https://user-images.githubusercontent.com/8966584/127617654-044c81e7-218d-432f-bdf5-ef8e94d8676d.png)
> ![image](https://user-images.githubusercontent.com/8966584/127617714-011deac0-9687-4393-a53f-a6e6adf6b3d2.png)

thanks! I'll check it.

**Comment by BoMingZhao** [comment]
I think I have found the problem. My openpose reverses the left and right hands when detecting some frames. And now I can render smpl model like this.
![image](https://user-images.githubusercontent.com/26064261/127947272-f7454e7f-f950-4e42-a272-04274c9c5492.png)

By the way, I wonder to know whether the openpose key_points of quick start demo dataset is annotated by yourself or generated directly with openpose code?
THANKS

**Comment by chingswy** [comment]
It's generated directly with openpose code. See `scripts/preprocess/extract_video.py` for more details.

**Comment by BoMingZhao** [comment]
我尝试去寻找相机参数的bug，但看起来相机参数好像真的找不出bug了，我现在keypoints 2d如下图，上面的三张可以看出整个人和keypoints是左右相反的，但下面的keypoints看起来比较准确。
![image](https://user-images.githubusercontent.com/26064261/128325519-27c09925-45aa-43d9-9bfa-18877ca7398c.png)
因此我尝试去修复openpose把左右手搞错的bug，我用数据集自带的点纠正了这些错误的点，并存为json重新运行。但还是和上图一样。
我又对输入的keypoints 2d做了visualize，如下图。
![image](https://user-images.githubusercontent.com/26064261/128326037-51b9c2a2-073a-4a0e-bf52-737608f1a93b.png)
![image](https://user-images.githubusercontent.com/26064261/128326064-dc4fce75-398b-49ba-b1d5-32e63d110a3d.png)
然后发现也没问题，如果输入的2d keypoints，那算出的3d keypoints也应当是对的啊。
此外相机参数如果有问题，不太确定为何会出现有的view对有的不对。
所以想请教一下还有什么可能的bug吗？十分感谢！

**Comment by MrMorning** [comment]
> 我尝试去寻找相机参数的bug，但看起来相机参数好像真的找不出bug了，我现在keypoints 2d如下图，上面的三张可以看出整个人和keypoints是左右相反的，但下面的keypoints看起来比较准确。
> ![image](https://user-images.githubusercontent.com/26064261/128325519-27c09925-45aa-43d9-9bfa-18877ca7398c.png)
> 因此我尝试去修复openpose把左右手搞错的bug，我用数据集自带的点纠正了这些错误的点，并存为json重新运行。但还是和上图一样。
> 我又对输入的keypoints 2d做了visualize，如下图。
> ![image](https://user-images.githubusercontent.com/26064261/128326037-51b9c2a2-073a-4a0e-bf52-737608f1a93b.png)
> ![image](https://user-images.githubusercontent.com/26064261/128326064-dc4fce75-398b-49ba-b1d5-32e63d110a3d.png)
> 然后发现也没问题，如果输入的2d keypoints，那算出的3d keypoints也应当是对的啊。
> 此外相机参数如果有问题，不太确定为何会出现有的view对有的不对。
> 所以想请教一下还有什么可能的bug吗？十分感谢！

Hi Boming, could you describe how you rendered your data? Seems that your data is synthesized rather than captured. Please pay attention to the fact that the definition of camera parameter in CG community and CV community is different, which may cause bugs.

**Comment by BoMingZhao** [comment]
> > 我尝试去寻找相机参数的bug，但看起来相机参数好像真的找不出bug了，我现在keypoints 2d如下图，上面的三张可以看出整个人和keypoints是左右相反的，但下面的keypoints看起来比较准确。
> > ![image](https://user-images.githubusercontent.com/26064261/128325519-27c09925-45aa-43d9-9bfa-18877ca7398c.png)
> > 因此我尝试去修复openpose把左右手搞错的bug，我用数据集自带的点纠正了这些错误的点，并存为json重新运行。但还是和上图一样。
> > 我又对输入的keypoints 2d做了visualize，如下图。
> > ![image](https://user-images.githubusercontent.com/26064261/128326037-51b9c2a2-073a-4a0e-bf52-737608f1a93b.png)
> > ![image](https://user-images.githubusercontent.com/26064261/128326064-dc4fce75-398b-49ba-b1d5-32e63d110a3d.png)
> > 然后发现也没问题，如果输入的2d keypoints，那算出的3d keypoints也应当是对的啊。
> > 此外相机参数如果有问题，不太确定为何会出现有的view对有的不对。
> > 所以想请教一下还有什么可能的bug吗？十分感谢！
> 
> Hi Boming, could you describe how you rendered your data? Seems that your data is synthesized rather than captured. Please pay attention to the fact that the definition of camera parameter in CG community and CV community is different, which may cause bugs.

Yes, this is a synthetic data downloaded from the renderpeople dataset.
Thank you very much, I will pay attention!

**Comment by BoMingZhao** [comment]
> > 我尝试去寻找相机参数的bug，但看起来相机参数好像真的找不出bug了，我现在keypoints 2d如下图，上面的三张可以看出整个人和keypoints是左右相反的，但下面的keypoints看起来比较准确。
> > ![image](https://user-images.githubusercontent.com/26064261/128325519-27c09925-45aa-43d9-9bfa-18877ca7398c.png)
> > 因此我尝试去修复openpose把左右手搞错的bug，我用数据集自带的点纠正了这些错误的点，并存为json重新运行。但还是和上图一样。
> > 我又对输入的keypoints 2d做了visualize，如下图。
> > ![image](https://user-images.githubusercontent.com/26064261/128326037-51b9c2a2-073a-4a0e-bf52-737608f1a93b.png)
> > ![image](https://user-images.githubusercontent.com/26064261/128326064-dc4fce75-398b-49ba-b1d5-32e63d110a3d.png)
> > 然后发现也没问题，如果输入的2d keypoints，那算出的3d keypoints也应当是对的啊。
> > 此外相机参数如果有问题，不太确定为何会出现有的view对有的不对。
> > 所以想请教一下还有什么可能的bug吗？十分感谢！
> 
> Hi Boming, could you describe how you rendered your data? Seems that your data is synthesized rather than captured. Please pay attention to the fact that the definition of camera parameter in CG community and CV community is different, which may cause bugs.

I have solved the problem, thank you and your excellent work!

**Comment by faneggs** [comment]
> > The unit of extrinsic parameters must be `meter`. You should check it.
> 
> sorry, what resolution do your data use?

Hey, would you please tell me if the resolution is different from that set by the author, will there be any influence on the reprojection result?

**Comment by puppet101** [comment]
@BoMingZhao 你好，我也遇到了同样的问题，3d关键点都是0，请问你是怎么解决的呢？
