### ISSUE TITLE
cpu version

### ISSUE THREAD

**Issue by raulbochka** [zju3dv/EasyMocap#57]
i'm trying to get cpu version but following a youtube tutorial that uses the gpu version
 should i remove only the cudatoolkit or what , 
(conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch)
this is where the code was taking from please take a look at the file and tell me if i should change anything, thank you
[anotacao_para_tutorial.txt](https://github.com/zju3dv/EasyMocap/files/6874523/anotacao_para_tutorial.txt)

**Comment by carlosedubarreto** [comment]
Hello @raulbochka .
When you install removing that line of code, does any error show up?

**Comment by chingswy** [comment]
You can directly run the code without cuda.
