### ISSUE TITLE
关于fbx导出

### ISSUE THREAD

**Issue by liuhaorandezhanghao** [zju3dv/EasyMocap#58]
您好，我之前参考vibe算法中关于fbx_output的代码，也是需要smpl的fbx模型，但是导出的动作文件中，人物以原点(0,0,0)为中心，没有人物的左右前后移动动作，动画中trans不是代表了它的平移么，我试图将pred_cam参数作为trans写入pose，但是结果不太对，请问你们导出bvh文件有解决相机参数的问题吗？人物是否以原点为中心呢？谢谢

**Comment by chingswy** [comment]
我们的不是以人物为中心的。 会考虑人物移动。

**Comment by liuhaorandezhanghao** [comment]
您好，有一点疑问就是你们json文件中的Rh,和Th是控制了人物的移动是吧，这两个具体是怎么计算出来的呢？有参考资料吗？谢谢




在2021年08月7日 17:25，Qing ***@***.***> 写道：

Closed #58.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chingswy** [comment]
通过优化关键点位置计算的，暂时没有参考资料。

**Comment by liuhaorandezhanghao** [comment]
您好，怎么改变你们可视化坐标系的默认z轴向上的定义呢，我的任务头朝向你们的-y轴，改不过来，谢谢。




在2021年08月9日 14:43，Qing ***@***.***> 写道：

通过优化关键点位置计算的，暂时没有参考资料。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chingswy** [comment]
建议修改相机参数，或者对每个人进行旋转变换
