### ISSUE TITLE
手指部分的捕捉准确率高吗？

### ISSUE THREAD

**Issue by Markjinli** [zju3dv/EasyMocap#59]
用过感觉比较不错的IPI soft，他们不支持手指部分的识别，感觉如果能支持上而且优化够好，那会变成很主流的产品了。现在虚拟制片越来越火，视觉识别的动捕需求处于快速上升的阶段。

**Comment by chingswy** [comment]
感谢关注，我们正在做针对手指部分的研究，会提高这部分的精度。
