### ISSUE TITLE
How to interpret Keypoints3d?

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/EasyMocap#6]
I was able to run the script to get the pose estimation.
Now I'm trying to use it in blender, but for that I have to convert the json to fbx, bvh ou something loadable inside blender.

I saw the keiponts3d files and was thinking of trying to create some sort of conversor to BVH files. 
But I dont have much info on these files.

Someone give more info on it?

I saw this on the documentation.

```
The data in keypoints3d/000000.json is a list, each element represents a human body.

{
    'id': <id>,
    'keypoints3d': [[x0, y0, z0, c0], [x1, y1, z0, c1], ..., [xn, yn, zn, cn]]
}
```

I guess the x, y and z are the usual 3d coordinates, but what does "c" means?

Thanks.

**Comment by chingswy** [comment]
I have updated the documentation of output, please check it.

**Comment by carlosedubarreto** [comment]
Wow, the documentation is much better than I expected.

Thanks a lot again.
