### ISSUE TITLE
Stuck at calib_intri.py 

### ISSUE THREAD

**Issue by eragondr** [zju3dv/EasyMocap#60]
I run the Stuck at calib_intri.py  for my chess board and it been like this for 3 days:
![image](https://user-images.githubusercontent.com/28474355/127343124-1c8e0fae-d4b0-43e7-a33b-a063368b9b2a.png)

**Comment by chingswy** [comment]
Sorry for that. I will add a more detailed documentation later.

**Comment by eragondr** [comment]
IT is ok. So It is useless if I keep watting like this? or it will be done if i wait longer ?

**Comment by chingswy** [comment]
It will be so slow when doing calibration with more than 100 images using OpenCV. You can stop this and sample less than 200 images to calibrate. 200 images will spend about 2 hours.

**Comment by eragondr** [comment]
hmm this is hard. becasue my fps is 60 if under 200 so my video only about 3s ?. Are you planning to update this in the short time ?

**Comment by chingswy** [comment]
You can notice that the `--step 5` flag is designed to sample the images. You can set this to `--step 50` which means use one image per 50 frames.
