### ISSUE TITLE
AssertionError: Only support MxN matrix, (72,)

### ISSUE THREAD

**Issue by liuhaorandezhanghao** [zju3dv/EasyMocap#62]
您好，我按照你们的json格式，把自己的pose姿势参数写进去后，尝试可视化，出现：AssertionError: Only support MxN matrix, (72,)。这个怎么解决呀。数据格式完全一致，我猜测是不是要保留三位小数？

**Comment by chingswy** [comment]
pose需要是(1x72)的，参考[文件定义](https://github.com/zju3dv/EasyMocap/blob/master/doc/02_output.md)，是否保留三位小数不重要。

**Comment by liuhaorandezhanghao** [comment]
> pose需要是(1x72)的，参考[文件定义](https://github.com/zju3dv/EasyMocap/blob/master/doc/02_output.md)，是否保留三位小数不重要。

谢谢，已解决。

**Comment by liuhaorandezhanghao** [comment]
您好，我测试你们的示例，是正常的。
当我测试自己生成的json文件时，人物的朝向不对，按理说我就改了poses的参数，其他都没变，这个你们在哪里更改的呢？
还有就是你们json中的的RH TH是怎么计算的呢？谢谢🙏




On 08/5/2021 13:18，Qing ***@***.***> wrote：

Closed #62.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chingswy** [comment]
人物的朝向和世界坐标系的定义有关。这个取决于相机标定时候的外参。
我们提供的数据里面默认世界坐标系为z轴垂直于地面向上。

**Comment by liuhaorandezhanghao** [comment]
已解决 谢谢




On 08/5/2021 14:49，Qing ***@***.***> wrote：

人物的朝向和世界坐标系的定义有关。这个取决于相机标定时候的外参。
我们提供的数据里面默认世界坐标系为z轴垂直于地面向上。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuhaorandezhanghao** [comment]
您好，在可视化smpl的过程中，smpl的pose一共有72个参数，这个参数是关节的axis-angle轴角式表达，那在做数据驱动的过程中不用转成四元数或者欧拉角吗？你们再传的过程中有对pose参数在做计算嘛？谢谢🙏




On 08/5/2021 ***@***.***> wrote：
已解决 谢谢




On 08/5/2021 14:49，Qing ***@***.***> wrote：

人物的朝向和世界坐标系的定义有关。这个取决于相机标定时候的外参。
我们提供的数据里面默认世界坐标系为z轴垂直于地面向上。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chingswy** [comment]
Unity是支持轴角的，可以直接使用轴角进行驱动。

**Comment by liuhaorandezhanghao** [comment]
但是每一个关节的轴角都是三维的，正常定义不应该是2维么，（哭了）




On 08/25/2021 14:24，Qing ***@***.***> wrote：

Unity是支持轴角的，可以直接使用轴角进行驱动。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chingswy** [comment]
三维空间中的角度都是三维的吧
