### ISSUE TITLE
投影问题

### ISSUE THREAD

**Issue by JACKYLUO1991** [zju3dv/EasyMocap#63]
请问一下，我在测试自己拍摄视频的时候发现人在转身的时候点位出现严重的“拧麻花”现象，这可能的原因是什么呢？同时，可视化3D点出现“横躺”的效果，求赐教！

**Comment by chingswy** [comment]
数据是什么样的？

**Comment by JACKYLUO1991** [comment]
数据是自己拍摄的，两路视频，其中人在转身的时候出现上述现象。感觉是三角化问题，不知道对不对？另外，不知道再加几路会不会解决该问题呢？

**Comment by chingswy** [comment]
多加几路相机会好一些，两个视角还是有一些歧义。
出现拧麻花现象是优化的时候没有初始化好，后续会更新一个版本可以解决这个问题。

**Comment by JACKYLUO1991** [comment]
@chingswy 给您发邮箱里面了...

**Comment by chingswy** [comment]
看上去是后面帧有多个人了，可以只使用前面一小段进行测试，增加`--end 100`选项

**Comment by JACKYLUO1991** [comment]
@chingswy 貌似并不是这个原因，前面的单人部分也会出现此问题

**Comment by chingswy** [comment]
确实会出现这个问题，我近期会更新一下代码。

**Comment by JACKYLUO1991** [comment]
@chingswy 多谢您，能否帮忙解析一下哪个步骤可能出现问题，三角化还是优化部分呢？我自己学习修正一下；还有代码的参考文献是否有呢？

**Comment by chingswy** [comment]
优化部分对人体的RT的优化。可能是smooth项加大了，导致优化过程收敛到局部最小值点了。
没参考文献。

**Comment by JACKYLUO1991** [comment]
@chingswy 多谢您
