### ISSUE TITLE
Questions about camera calibration

### ISSUE THREAD

**Issue by zhanghua7099** [zju3dv/EasyMocap#64]
I try calibrate our 3 cameras. But when I got to step 3 Intrinsic Parameter Calibration, an error occurred:

```
Traceback (most recent call last):
  File "apps/calibration/calib_intri.py", line 121, in <module>
    calib_intri(args.path, step=args.step)
  File "apps/calibration/calib_intri.py", line 101, in calib_intri
    k3ds, k2ds, gray.shape[::-1], None, None)
cv2.error: OpenCV(3.4.15) /tmp/pip-req-build-bnamxc70/opencv/modules/calib3d/src/calibration.cpp:3409: error: (-215:Assertion failed) nimages > 0 in function 'calibrateCamera'
```
I think it may be caused by the small chessboard that we used. The environment conditions will also affect the script.

Can you provide a set of demo video that can calibrate the camera's parameter?

I will change the scene according to you demo.

**Comment by chingswy** [comment]
Hello, we have updated our calibration tutorial. Please check it.
