### ISSUE TITLE
SMPL model for multiple views of multiple people

### ISSUE THREAD

**Issue by 19reborn** [zju3dv/EasyMocap#66]
Thanks a lot for this excellent project! 
I now try the MVMP code for my data with 42 cameras. Everything works for me except the reprojection of SMPL model.
I don't know why this happens, for all the 3D keypoints and keypoints reprojection fit the images.

**Comment by chingswy** [comment]
Hello @19reborn , I guess the main problem is that SMPL is a statistic model. If your calibration for the scale is not very accurate, the length of the skeleton will be different with this model. You should check the calibration and make sure that the unit length is `meter`.

**Comment by 19reborn** [comment]
@chingswy  Thanks for you helpful reply! Does **'calibration for the scale'** refer to camera calibration?  I now only have the camera parameters given by others, and it's impossible for me to calibrate the camera using your methods. ( The camera parameters is not very accurate, but I can confirm the unit length is **meter**)
In such case, are there any other ways to fix the SMPL models?

**Comment by chingswy** [comment]
I have no idea. You can try to calculate the length of the bone and compare it with the real length.

**Comment by 19reborn** [comment]
Thanks again. I may have to delete the reprojection image for the data is private.
