### ISSUE TITLE
For the two-dimensional pose estimation, can I use alphapose (17 key points) instead of openpose (25 key points), the number of his two key points is different, do I need to modify it?

### ISSUE THREAD

**Issue by zhanghongyong123456** [zju3dv/EasyMocap#67]
The number of key points obtained is different, what should I modify to use it?

**Comment by chingswy** [comment]
Please check this func [coco17tobody25](https://github.com/zju3dv/EasyMocap/blob/master/easymocap/dataset/config.py#L681)

**Comment by zhanghongyong123456** [comment]
> Please check this func [coco17tobody25](https://github.com/zju3dv/EasyMocap/blob/master/easymocap/dataset/config.py#L681)

thank you for your reply
