### ISSUE TITLE
Path issue when applying openpose

### ISSUE THREAD

**Issue by felixbastian** [zju3dv/EasyMocap#68]
When running the command:

`python scripts/preprocess/extract_video.py {PATH TO PROJECT FOLDER} --openpose {PATH TO OPENPOSE 1.5.1}`

I received the following error:

"C:\Users\myName\OneDrive\Documents\Python" does not exist.

It took me an awful long time to figure out that this has nothing to do with my python but the fact that my project is located in:
"C:\Users\myName\OneDrive\Documents\Python Projects"

Therefore, the space leads to an error. 
Unfortunately, the folder cannot be renamed and the project cannot be relocated because "The file is open in another project". (restarted the computer to make sure problem persists)
Is there any suggestion for a quick fix, or do I need to re-install easyMocap at another location?

Thanks for your work by the way, great project.

**Comment by chingswy** [comment]
Can you paste the full information in terminal?

**Comment by carlosedubarreto** [comment]
There is this pull request that I've done some time ago to be able to work on windows machines. at least worked for me 

https://github.com/zju3dv/EasyMocap/pull/18

**Comment by felixbastian** [comment]
> 
> 
> Can you paste the full information in terminal?

cameras:  1 2
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...

Error:
Folder C:\Users\felix\OneDrive\Dokumente\Python\ does not exist.

Coming from:
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\utilities\fileSystem.cpp:op::getFilesOnDirectory():312
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\utilities\fileSystem.cpp:op::getFilesOnDirectory():366
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\utilities\fileSystem.cpp:op::getFilesOnDirectory():408
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\producer\imageDirectoryReader.cpp:op::getImagePathsOnDirectory():22
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\producer\producer.cpp:op::createProducer():471
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1188
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():424
1         : 0it [00:00, ?it/s]
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...

Error:
Folder C:\Users\felix\OneDrive\Dokumente\Python\ does not exist.

Coming from:
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\utilities\fileSystem.cpp:op::getFilesOnDirectory():312
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\utilities\fileSystem.cpp:op::getFilesOnDirectory():366
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\utilities\fileSystem.cpp:op::getFilesOnDirectory():408
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\producer\imageDirectoryReader.cpp:op::getImagePathsOnDirectory():22
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\src\openpose\producer\producer.cpp:op::createProducer():471
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\include\openpose/wrapper/wrapperAuxiliary.hpp:op::configureThreadManager():1188
- D:\Users\gines\Desktop\openpose\openpose-1.5.1\openpose-1.5.1\openpose\include\openpose/wrapper/wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():424
2         : 0it [00:00, ?it/s]

**Comment by felixbastian** [comment]
> 
> 
> There is this pull request that I've done some time ago to be able to work on windows machines. at least worked for me
> 
> #18

Yes, actually I followed your tutorial! Thank you very much for your work.
I actually used your version of extract_video.py from the beginning.

Concerning the issue here, I eventually to set up easyMocap from scratch in another folder.
It now seems to work.
