### ISSUE TITLE
About the time of 3D reconstruction

### ISSUE THREAD

**Issue by zhanghongyong123456** [zju3dv/EasyMocap#69]
I have obtained whether the time for 2D pose during 3D reconstruction can be shortened to achieve real-time effects，
![100](https://user-images.githubusercontent.com/48466610/129319097-e0901a18-4e83-431a-8657-f457bc36614a.png)
How to achieve real-time

**Comment by chingswy** [comment]
Hello, it seems like that the bottleneck is the memory IO. You can just read the keypoints results and write the keypoints results.

**Comment by zhanghongyong123456** [comment]
> Hello, it seems like that the bottleneck is the memory IO. You can just read the keypoints results and write the keypoints results.

时间花费主要在于加载数据，只需要节约加载数据的时间就可以实现实时，为了节约加载数据时间，我只需要加载关键点信息就可以了，但是我看到运行脚本，python  apps/demo/mvmp.py 0_input/mvmp --out ./01_output/mvmp --annot annots --cfg config/exp/mvmp1f.yml --undis --vis_det --vis_repro  ，包括输入数据路径、标注信息，那我应该去掉那一部分来节约时间，
1. 是将标注信息，替换成二维关键点（openpose生成 的keypoints json 文件），也就是不进行标注信息的生成，直接使用关键点坐标。
2. 是减少标注信息的不必要信息，例如 图像大小，边界框坐标，是否关键帧 ，人物ID ，我该去掉哪些不必要信息呢

**Comment by chingswy** [comment]
```bash
python apps/demo/mvmp.py 0_input/mvmp --out ./01_output/mvmp --annot annots --cfg config/exp/mvmp1f.yml --undis
```

**Comment by zhanghongyong123456** [comment]
> ```shell
> python apps/demo/mvmp.py 0_input/mvmp --out ./01_output/mvmp --annot annots --cfg config/exp/mvmp1f.yml --undis
> ```
> 
> 去掉可视化部分。如果相机畸变为0可以去掉`--undis`

1. 我去掉可视化，达到22fps  ，去掉 undis 能达到37fps， 对于这个重要性如何评估，去掉影响大不大。
2.对于三维重建部分我们有c++ 实现吗，因为前期的视频流拉取，二维关键点估计都是c++实现的，还是说按照您代码里面一样，以调用openpose 发行版形式实现前期处理

**Comment by chingswy** [comment]
1. 根据使用的数据进行评估
2. 我们有C++的不开源版本；如果使用python版本，建议使用socket进行通信，将关键点的结果发送到python端。

**Comment by zhanghongyong123456** [comment]
> 1. 根据使用的数据进行评估
> 2. 我们有 C++ 的非开源版本；如果使用 python 版本，建议使用 socket 进行通信，将关键点的结果发送到 python 端。

嗯恩，非常感谢您提供的建议.我去尝试一下

**Comment by LRuid** [comment]
> > 1. 根据使用的数据进行评估
> > 2. 我们有 C++ 的非开源版本；如果使用 python 版本，建议使用 socket 进行通信，将关键点的结果发送到 python 端。
> 
> 嗯恩，非常感谢您提供的建议.我去尝试一下

您好，我想请问你最后的选择是怎么样的？1.是否用了8个相机，是否用的yolo-hrnet，用c++写了个加速？2.如果需求仅仅是单人实时，能否推荐一个理论上能实时方案？有学fpga写加速的成员
