### ISSUE TITLE
test mvmp on other datasets, the results are bad

### ISSUE THREAD

**Issue by visonpon** [zju3dv/EasyMocap#70]
Hi, thanks for your generous share of this wonderful work. I have tried to test the mvmp on [this dataset]( https://cloud.tsinghua.edu.cn/f/82b5512334344a4187ff/?dl=1) from[ 4d_association](https://github.com/zhangyux15/4d_association), but most of the time, the results are bad since only one person or no person's 3d points produced, hope you guys can also test on it to see if everything is normal, thanks~

**Comment by chingswy** [comment]
Can you provide the annotation and camera parameters converted from the original dataset? Maybe some bug on the processing steps.

**Comment by visonpon** [comment]
since they provide the calibration.json file which contains camera intri  and extri, I get the camera parameters  like below:
```
with open('./.json') as fp:
    temp = json.load(fp)
for ic cam in enumerate(camnames):
    with Timer('calibrate'):
        cameras[cam] = {'K':,np.reshape(np.array(temp[cam]['K']),(3,3). 'dist': np.reshape(np.array(temp[cam)['distCoeff']),(1,5))}

write_intri('./intri.yml'.cameras)

```

**Comment by visonpon** [comment]
Hi, I come to notice that my problem is the same in this [QA](https://github.com/zju3dv/EasyMocap/issues/66)
 you have mentioned that this may be caused by a skeleton scale if not calibrate the camera as you did, but why this chessboard calibration can solve this scale problem? hope you can help.thanks~

**Comment by chingswy** [comment]
![000000](https://user-images.githubusercontent.com/22812405/130314521-f11457db-2a71-4d8c-82dd-3426806d4520.jpg)
Hello, I test it on Human3.6M dataset. Everything works well.

**Comment by visonpon** [comment]
thanks for your patient response, so this is not a skeleton scale problem? I will look through my scripts, thanks~
