### ISSUE TITLE
How to render the `json` file?

### ISSUE THREAD

**Issue by ElegantLin** [zju3dv/EasyMocap#72]
Dear authors, 

Thanks for your nice work. I am puzzled about how I can render the `json` file. Could you please help me with this issue?

Thanks!

**Comment by ElegantLin** [comment]
Thanks for your reply. I am sorry that maybe I do not make myself clear. I am puzzled about the parameter `Rh` and `Th` in the output json. Is that possible for me to get the original 3D keypoints using that json file or could you please refer me to the related code?

Thanks!

**Comment by chingswy** [comment]
When you run `vis_server.py` and `vis_client.py`, [this line](https://github.com/zju3dv/EasyMocap/blob/master/easymocap/socket/o3d.py#L145) will calculate the keypoints give the paramenters.

**Comment by ElegantLin** [comment]
Sure. Thanks. And my last question is whether there is a way to get the original SMPL parameter from the output `json`. I think the parameters changed are the global orientation and translation. 

I tried the following steps which I think are incorrect.

1.  I tried to convert the `Rh` and `Th` from the Euler angle to the rotation matrix `R` and `T`, respectively. 
2. I did `R.T @ R` and `R.T @ T + T.T` to get the rotation and translation in matrix representation. 
3. I applied the `cv2.Rodrigues` transformation to the matrix representations and let use name them as `R_post` and `T_post`.
4. I found `R_post` is 0 for both two persons in the image and I think it is wrong because the global orientation of the two persons should not the same. 

Could you please tell me how to get the original SMPL parameters?

Thanks!

**Comment by chingswy** [comment]
[This line](https://github.com/zju3dv/EasyMocap/blob/master/easymocap/smplmodel/body_model.py#L265) shows how to convert SMPL parameters to ours. The inverse transform can be derived from this.

**Comment by ElegantLin** [comment]
Sure. Thanks!
