### ISSUE TITLE
More details of data/smplx/J_regressor_body25.npy

### ISSUE THREAD

**Issue by GongfaJiang** [zju3dv/EasyMocap#73]
Dear authors,

Thank you for your amazing work. I used 'data/smplx/J_regressor_body25.npy' with the 6890 smpl vertices and I got 25 joints, which are something like
![regress](https://user-images.githubusercontent.com/82385690/131993938-be722706-2c4e-4c95-8bbe-b41a3aadf8ca.jpg)
Is the skeleton exactly the same as the Openpose Body_25 skeleton? How did you get the regressor?

Thanks!

**Comment by chingswy** [comment]
The skelton is as the same as Body25 as possible. This regressor comes from previous work but I forget which one.

**Comment by GongfaJiang** [comment]
Thank you!
I will appreciate that if you send me a message when you remember where the regressor comes from.

**Comment by QiFuChina** [comment]
Hello, I have same question with J_regressor_body25 files . I 'm looking for the J_regressor_body25.npy and other .txt files that should be placed under `data/smplx` but I don't know which link can download them . Could you please tell me how to get this ?

**Comment by GongfaJiang** [comment]
I can download them from EasyMocap repo, https://github.com/zju3dv/EasyMocap/tree/2544c970ef7dce5cfc0e1f26f903a75dc4007963/data/smplx
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, May 27, 2022 09:26 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; "State ***@***.***&gt;; 
Subject: &nbsp;Re: [zju3dv/EasyMocap] More details of data/smplx/J_regressor_body25.npy (#73)

&nbsp;



 
Hello, I have same question with J_regressor_body25 files . I 'm looking for the J_regressor_body25.npy and other .txt files that should be placed under data/smplx but I don't know which link can download them . Could you please tell me how to get this ?
