### ISSUE TITLE
SMPL reconstruction fail

### ISSUE THREAD

**Issue by neilgogogo** [zju3dv/EasyMocap#74]
Thank you for your excellent work, I have a question when using the multiview camera one people to do the quick start demo:

When I tried to run the SMPL reconstruction using the CMU pano dataset, I get such result, it seems that the reconstruction failed, coz there is no smpl model and the shapes is really big, but I don't know the reason.

![image](https://user-images.githubusercontent.com/53148705/132157702-bfb23b38-298c-4c58-8853-b7dfeda7e1d9.png)

**Comment by chingswy** [comment]
Please check [this file](https://github.com/zju3dv/EasyMocap/blob/master/scripts/dataset/pre_panoptic.py) about the camera parameters.  The unit of the lenght must be **meter**.

**Comment by neilgogogo** [comment]
it's really helpful, thank you very much for you help
