### ISSUE TITLE
Badly fitted SMPL model

### ISSUE THREAD

**Issue by tejaswivg** [zju3dv/EasyMocap#75]

**Comment by chingswy** [comment]
More description?

**Comment by tejaswivg** [comment]
I have very weird artifacts that showed up(notice the weird twists here : https://vigaet.sharepoint.com/:i:/s/Graphics/EXV0zmFtrEhLoI0QsTfn3yoBwR9d7M9shs1nOXgv_4wOHA?e=v9Jkie ). Is there anything I could do apart from post processing cleanup?

**Comment by chingswy** [comment]
Sorry, I can't open your sharepoint.

**Comment by tejaswivg** [comment]
> Sorry, I can't open your sharepoint.

sorry about that. Could you please take a look now?

**Comment by chingswy** [comment]
The results are so bad. How many cameras do you use?

**Comment by tejaswivg** [comment]
We use 3 cameras. How many do you recommend?

**Comment by chingswy** [comment]
Three cameras are enough for easy pose. What about the `repro` results of skeletons.

**Comment by tejaswivg** [comment]
skeleton repro seems fine, but
![000000](https://user-images.githubusercontent.com/85922065/132338937-f4694e60-7635-40ff-91d3-72dd4d050b53.jpg)
![000066](https://user-images.githubusercontent.com/85922065/132338952-3a2593e7-ce34-41b6-b71e-fc7625c077dc.jpg)
but the images in repro_smpl have very bad detections
![000000](https://user-images.githubusercontent.com/85922065/132339023-6b1f7fb1-6b10-42be-af92-16ea7d223486.jpg)
![000108](https://user-images.githubusercontent.com/85922065/132339034-d6e4aff4-9f0c-4567-8796-15cdb28a607f.jpg)

**Comment by chingswy** [comment]
It seems that the calibration results are inaccurate. You should check your calibration step.

**Comment by tejaswivg** [comment]
> It seems that the calibration results are inaccurate

yeah, I was looking into that too, only a couple of points seem off, 
![000000](https://user-images.githubusercontent.com/85922065/132345674-77edb4d3-3482-4dab-929a-f1780ed8eeb5.jpg)

> You should check your calibration step. Besides, the unit of length must be meter.

automatic calibration was very bad in my case. So I tried to adapt this: https://github.com/zju3dv/EasyMocap/issues/23  to both intrinsics and extrinsics calibration. The way I do it is to use labelme and draw keypoints manually. I save the output(which has units as pixels) and then copy 2d keypoints and use the automatically generated 3d keypoints. Do you see any problems with this approach?

I've also had cases where the visualizer doesn't work , but bvh export or viewing SMPL works a little better. such as this: https://drive.google.com/file/d/1iq0LcoLSi6IJO_aJe_Sbpp0oDVYpTp-i/view?usp=sharing

**Comment by chingswy** [comment]
Your chessboard is so small. You'd better make a larger chessboard.
And you should calibrate your intrinsic first.

**Comment by tejaswivg** [comment]
> Your chessboard is so small. You'd better make a larger chessboard.
> And you should calibrate your intrinsic first.

Noted. Any thoughts on using [labelme](https://github.com/wkentaro/labelme) ?

It would also be great if you could release the annotation script mentioned [here](https://github.com/zju3dv/EasyMocap/blob/master/apps/calibration/Readme.md#25-finetune-the-chessboard-detection-result)

**Comment by tejaswivg** [comment]
Computed radial distortion was bad. I set them to zero and now I get decent results.

**Comment by chingswy** [comment]
> It would also be great if you could release the annotation script mentioned [here](https://github.com/zju3dv/EasyMocap/blob/master/apps/calibration/Readme.md#25-finetune-the-chessboard-detection-result)

This script is released at `apps/annotation/annot_calib.py`
