### ISSUE TITLE
A question for extrinsic parameter calibration

### ISSUE THREAD

**Issue by liuchangji** [zju3dv/EasyMocap#76]
标定外参的时候，是不是每个摄像头只需要一张照片（或者是视频中只需要出现一次有标定板的画面），这张照片或视频是多个摄像头在同一时刻拍摄的，标定板放在了地上。
此时，标定板代表了世界坐标系的原点？
When calibrating the extrinsic parameters, is it true that each camera needs only one photo, which was taken by multiple cameras at the same moment, with the calibration board placed on the ground.
At this time, the calibration board represents the origin of the world coordinate system?

**Comment by liuchangji** [comment]
![image](https://user-images.githubusercontent.com/43487003/132325854-e8630827-335e-4804-a91a-56b949f40867.png)
If the calibration board with multiple positions is used to calibrate the extrinsic parameters, where is the origin of the world coordinate system?
如果使用多个位置的标定板标定外参，那么世界坐标系的原点在哪里呢?

**Comment by chingswy** [comment]
只需要拍一张同一时刻的，标定板代表了世界坐标系的原点。

**Comment by NewCoderQ** [comment]
@chingswy 请问我在哪里可以下载到 多视角的相机内外参的标定数据呢？我们用了自己的标定数据，最后估计的结果总是不对，想下载你们提供的标定数据走下整个标定流程。

**Comment by chingswy** [comment]
如果标定不对,确认一下:
1. 棋盘格的模式是否正确,最好使用OpenCV的(9,6)的格子,并且确保棋盘格不是中心对称的
2. 如果棋盘格模式正确,确认棋盘格的检测结果是否正确

**Comment by niubiplus2** [comment]
@liuchangji 请问你的标定板是定制的吗，还是自己打印的棋盘格呢？如果是自己打印的话，会不会不太平整呢？
