### ISSUE TITLE
The question about repro and repro_smpl

### ISSUE THREAD

**Issue by MarcoG5** [zju3dv/EasyMocap#77]
First I would like to thank you for your greate work!
It seems that my detection and reprojection results are fine
![detec](https://user-images.githubusercontent.com/49357882/132442483-f6ad6c9f-f127-4256-ad1e-54364fb990c2.jpg)
![repro](https://user-images.githubusercontent.com/49357882/132442496-ac9ac92c-bb85-4c8d-891d-6abb3f2724fd.jpg)
but when it comes to repro_smpl and smpl, the results seems like it is rescaled. I dont know what seems to be the problem
![repro_smpl](https://user-images.githubusercontent.com/49357882/132442570-2dfa31cd-98b9-46fa-9658-524ca3144599.jpg)
![smpl](https://user-images.githubusercontent.com/49357882/132442589-f11b83a8-1196-4f94-bfa4-cbff61dc8e7c.jpg)
By the way, I think that it is vital to get accurate camera extrinsic by using bundle adjustment. Or the reproject results gets bad. I use other method to achieve that calib result and I am looking forward to see your implementation.

**Comment by chingswy** [comment]
Hello, the `repro_smpl` is wrong always because your scale is not the same as SMPL model. Your relative extrinsic parameters are right so the `repro` is right.

I implement the bundle adjustment by Ceres in C++. I don't release this part because it will be hard to compile and install this library.

**Comment by MarcoG5** [comment]
> Hello, the `repro_smpl` is wrong always because your scale is not the same as SMPL model. Your relative extrinsic parameters are right so the `repro` is right.
> 
> I implement the bundle adjustment by Ceres in C++. I don't release this part because it will be hard to compile and install this library.

@chingswy Thank you for your reply!
So I guess the scale problem is caused by my camera params? Is there any way to fix it? 
And I am not sure the steps you take to complete the bundle adjustment. I think it uses another set of feature point to finetune two cameras at the same time untill all the camera extri is corrected. Is that right?

**Comment by chingswy** [comment]
1. How do you get your camera parameters?
2. Yes, you are right.

**Comment by MarcoG5** [comment]
> 1. How do you get your camera parameters?
> 2. Yes, you are right.

I use Structure From Motion to get the camera parameters.

**Comment by chingswy** [comment]
SfM can not provide a right scale. You can rescale the camera parameters manually.

**Comment by MarcoG5** [comment]
Thanks a lot!
