### ISSUE TITLE
Human Mask Extraction 

### ISSUE THREAD

**Issue by Pallab38** [zju3dv/EasyMocap#78]
Hi, thank you so much for this amazing work. Can you please provide the human masks or can you explain how you extracted those? 
Thanks.
<img src="https://user-images.githubusercontent.com/11056707/132471481-9e6fb6fb-4ebf-43a9-86e7-4d7113283d23.jpeg" width="250" height="250">

**Comment by chingswy** [comment]
Hello, we first extract the mask using the previous work [CIHP_PGN](https://github.com/Engineering-Course/CIHP_PGN). When the network fails, we manually annotate the mask(It's robust for most case.).

**Comment by Pallab38** [comment]
Thanks a lot for your quick reply. Is there any possibility to provide those masks you extracted and annotated? 
:)

**Comment by chingswy** [comment]
In this [work](https://zju3dv.github.io/neuralbody/), we provide some masks we extracted.

**Comment by Pallab38** [comment]
thanks a lot :)
