### ISSUE TITLE
Using checkboard different from 9x6

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/EasyMocap#8]
Hello...

I was testing doing the extrinsic calibration using a checkboard that is 5x3 and the calibration goes fine (without error) but when doing the triangulation some odd things are happening.

![image](https://user-images.githubusercontent.com/4061130/111389287-7b2e2880-868f-11eb-950f-3a751190890e.png)

the points are out of place. And I took care to measure the size of the squares and used in meter. But it is not working.

The interesting point is that when I used a checkboard 9x6 it worked nice.

Do you have an idea of what could be the issue? I'm using this 5x3 because the square is bigger so it would be easier to do the calibration.

**Comment by chingswy** [comment]
Did you add the `--pattern` option when calibration? You can also add the `--debug` option to see whether the corner locations are right or not.

**Comment by carlosedubarreto** [comment]
Yeah, i used this code:

`python scripts/calibration/calib_extri.py -i ./data/examples/calibration/extri_images -o ./data/examples/calibration --debug --pattern 5,3 --grid 0.0465`

I'll do some research using the corner locations. thanks.

**Comment by chingswy** [comment]
The calibration board you show may be `4x3` rather than `5x3`?

**Comment by carlosedubarreto** [comment]
That really is confusing(for me to get the real size of checkboard), but I think it is a 5x3, here is a better picture
![FJIMG_20210316_080832](https://user-images.githubusercontent.com/4061130/111430741-90c84000-86d9-11eb-9670-2858669e9e3c.jpg)

**Comment by carlosedubarreto** [comment]
I'm working on another hypothesis.
Maybe my problem was that to calibrate I used  different image size from what was used on the video. I think that is the problem.
If i remember correctly the only time everything worked correctly was when I calibrated the camera with images from the same video I was trying to use on easymocap

**Comment by chingswy** [comment]
Thanks for your feedback, I will add it to the documentation.

**Comment by carlosedubarreto** [comment]
I tested using the same resolution and it worked...
Trying easymocap it´s been a fun ride.

**Comment by carlosedubarreto** [comment]
@chingswy another thing.
Today I've found that using a calibration code that uses fisheye calibration is where I got the best triangulation.

here is a code that I'm using for a 9x6 chessboard, and it outputs a string that only needs to copy and paste on intri.yml

[calibrate_fisheye_9x6.zip](https://github.com/zju3dv/EasyMocap/files/6217710/calibrate_fisheye_9x6.zip)
