### ISSUE TITLE
keypoints3d

### ISSUE THREAD

**Issue by hai8023** [zju3dv/EasyMocap#81]
Unable to get 3D keys.
If there is a character a in the video taken by camera a, and there is a character B in the video taken by camera B without character a, this is incorrect, isn't it?

**Comment by chingswy** [comment]
Yes. It's incorrect. You should assume that character A and only character A can be seen in different cameras.

**Comment by hai8023** [comment]
I have one more question.
I shot a group of videos with an iPhone. The chessboard is very large, but the chessboard cannot be extracted. Is this related to the camera parameters? If so, what parameters should be used?
`python3 apps/calibration/detect_chessboard.py ${data} --out ${data}/output/calibration --pattern 9,6 --grid 0.12`
![000000](https://user-images.githubusercontent.com/83195382/134801070-32a1e7e2-b1e4-4ee4-ba5e-536a29d9af7c.jpg)

**Comment by chingswy** [comment]
I can't detect it either. It's very strange. You can try to make the chessboard more closer to the camera.

**Comment by hai8023** [comment]
At close range, some pictures can be detected, and some cannot be detected. Does the light have a great influence on the detection?

**Comment by chingswy** [comment]
![000001](https://user-images.githubusercontent.com/22812405/134805085-bbe632a5-e496-4fbc-b1d2-66a327aa3781.jpg)
Maybe you can change your pants.

**Comment by hai8023** [comment]
膜拜
