### ISSUE TITLE
请问有方法可以输出对应的MESH吗？

### ISSUE THREAD

**Issue by Hagtaril** [zju3dv/EasyMocap#82]
作者们好！在smplmodel/lbs.py 中提供了输出vertices和joints的方法，我没有发现输出mesh的方法，是我忽略了什么地方吗？或者这部分操作是不被支持的？

**Comment by chingswy** [comment]
mesh只需要输出的vertices和模型对应的faces就好。暂时没有提供单独写成mesh文件的功能
