### ISSUE TITLE
How to interpret Affinity matrix and matchSVT algorithm in auto_track.py?

### ISSUE THREAD

**Issue by TheSeaOfStars123** [zju3dv/EasyMocap#85]
Hello, thanks a lot for this great code. 
Recently I am trying to run `mvmp` demo on the example dataset and read this [mvpose](https://arxiv.org/abs/1901.04111) paper of your team. By comparing these two jobs, I have two questions:

1. The overview of the paper's approach follows  (a)input images → (b) detected 2D poses → (c) cross-view matching(input is affinity matrix and output is permutation matrix) → (d) 3D poses, it looks like your team first establish the correspondences of the detected bounding boxes across views and then do 3D reconstruct. But in `mvmp` demo, the code first implements batch triangulation to generate original 3D keypoints and then track the human pose. **So I am confused whether these two different solutions lead to the different final results and which one is better?**
![image-20210930141052039](https://gitee.com/keaidicc/picgo/raw/master/pic/202109301410149.png)

2.  I am trying to read the `apps/demo/auto_track.py` code. Using debug tool and stepping into `compute_dist()` function in `track.py` I noticed these two lines of core code for tracking:

```python
dist = self._compute_dist(dimGroups, results_window)
res = matchSVT(dist, dimGroups, control=self.svt_args)
```

In the paper's section3.2 Multi-view correspondences, I found some interpretation to the affinity matrix and the matching algorithm. I wonder **what is the difference between the affinity matrix and matchSVT algorithm in this project and the Multi-view correspondences algorithm** in the [mvpose](https://arxiv.org/abs/1901.04111) paper?
<img src="https://gitee.com/keaidicc/picgo/raw/master/pic/202109301404442.png" alt="image-20210930140412410" width = "60%" height = "60%" />

**Comment by chingswy** [comment]
In `mvmp` code, we first apply `mvpose` algorithm to each frame and get 3D keypoints of each person in each frame. Then we track the keypoints in each frame to form the trajectories of each people.
The distance is defined as epipolar distance when doing cross-view matching. When doing temporal matching, we define the distance as the Euclidean distance of 3D keypoints.

**Comment by TheSeaOfStars123** [comment]
> In `mvmp` code, we first apply `mvpose` algorithm to each frame and get 3D keypoints of each person in each frame. Then we track the keypoints in each frame to form the trajectories of each people. The distance is defined as epipolar distance when doing cross-view matching. When doing temporal matching, we define the distance as the Euclidean distance of 3D keypoints.

Thanks! You're right, I was so careless that I missed the most important part. After reading the code again, you did use the matching algorithm twice, once in  `mvpose`  algorithm and another in track part.

**Comment by TheSeaOfStars123** [comment]
@chingswy Hello, I have another question. About the 3D pose reconstruction phase, now given the matched 2D poses in all views, did you use a 3DPS model (which was mentioned in `mvpose` algorithm) to infer the final 3D poses in this repo? Or you just implemented the direct triangulation algorithm in `batch_triangulate` function?  Thanks!

**Comment by chingswy** [comment]
We don’t use 3DPS.
