### ISSUE TITLE
Where to find the cylinder mesh of skeleton?

### ISSUE THREAD

**Issue by sunshinnnn** [zju3dv/EasyMocap#86]
Hi! I'd liked to ask that have you released [**the cylinder mesh**](https://github.com/zju3dv/EasyMocap/blob/master/doc/feng/mv1pmf-smplx.gif) used for skeleton mesh rendering? I could not find it in this repository. It is very cool when compared to a standard cylinder. Thanks!

**Comment by chingswy** [comment]
Please check the visualization [quick start](https://github.com/zju3dv/EasyMocap/blob/master/doc/realtime_visualization.md)
