### ISSUE TITLE
关于相机校准的问题

### ISSUE THREAD

**Issue by KeonAcute** [zju3dv/EasyMocap#88]
能麻烦问一下在校准内外参数时，所需图像的像素大小最好是多少呢。在用立方体检查结果时发现图像的畸变比较严重，请教下该如何用立方体检查校准结果的好坏吗？

**Comment by KeonAcute** [comment]
谢谢，但我在想是否因为相机视角个数的原因，也导致了实际可视化的效果不够好，经常没有骨架显示或是断断续续，我只用了四个相机来完成。

**Comment by Freestyle1024** [comment]
好用吗？跟那个Unity插件比是不是简单些
