### ISSUE TITLE
在自定义的dataset上不成功

### ISSUE THREAD

**Issue by YuLiHN** [zju3dv/EasyMocap#94]
你好，首先非常感谢能够分享你们的代码。
我在我自己的数据集上测试了一下，发现了这个问题。四张图分别来自det，repro，repro_smpl，smpl

这是带背景的smpl

我试着调了extract_video.py里的--low和 mv1p.py 里--thres2d这两个参数，但是都不太行。。。
请问有什么可以提升的办法吗

**Comment by chingswy** [comment]
请将check_repro关掉试试，在[这一行](https://github.com/zju3dv/EasyMocap/blob/master/apps/demo/mv1p.py#L38)

**Comment by chingswy** [comment]
OpenPose对于不是站着的人的检测效果会比较差，可以将渲染的角度改变成都站着的情况。

**Comment by YuLiHN** [comment]
> OpenPose对于不是站着的人的检测效果会比较差，可以将渲染的角度改变成都站着的情况。

对不起我没有完全明白你的意思，我的图片好像都是站着的吧？
因为我不是从视频里抓取帧的，而是一张一张独立的帧，有没有这种可能，我图片的人物动作不够连续导致openpose检测失败？

**Comment by chingswy** [comment]
人是站着的，但是在图片里不是竖着的。图片里竖着的检测效果会好一点。
和是否是独立的帧无关。

**Comment by caiyongqi** [comment]
> 你好，首先非常感谢能够分享你们的代码。 我在我自己的数据集上测试了一下，发现了这个问题。四张图分别来自det，repro，repro_smpl，smpl ![det](https://user-images.githubusercontent.com/82912827/137995790-dabc8d8a-140d-496f-8c36-64c633d2e837.png) ![repro](https://user-images.githubusercontent.com/82912827/137995856-a36f572f-ca63-4036-88ea-382507480e70.png) ![repro_smpl](https://user-images.githubusercontent.com/82912827/137995858-e0c1a2e3-704f-4be4-aa03-37951a225606.png) ![smpl](https://user-images.githubusercontent.com/82912827/137995863-2be13243-9054-416f-a35a-6e99f0f9392e.png)
> 
> 这是带背景的smpl ![image](https://user-images.githubusercontent.com/82912827/137996778-ff50236f-1b01-45fa-af96-2b8a0c2cf620.png)
> 
> 我试着调了extract_video.py里的--low和 mv1p.py 里--thres2d这两个参数，但是都不太行。。。 请问有什么可以提升的办法吗

你好，请问用自己数据集时，extri.yml中的R和T是世界坐标系到相机坐标系的旋转和平移吗？

**Comment by YuLiHN** [comment]
> > 你好，首先非常感谢能够分享你们的代码。 我在我自己的数据集上测试了一下，发现了这个问题。四张图分别来自det，repro，repro_smpl，smpl ![det](https://user-images.githubusercontent.com/82912827/137995790-dabc8d8a-140d-496f-8c36-64c633d2e837.png) ![repro](https://user-images.githubusercontent.com/82912827/137995856-a36f572f-ca63-4036-88ea-382507480e70.png) ![repro_smpl](https://user-images.githubusercontent.com/82912827/137995858-e0c1a2e3-704f-4be4-aa03-37951a225606.png) ![smpl](https://user-images.githubusercontent.com/82912827/137995863-2be13243-9054-416f-a35a-6e99f0f9392e.png)
> > 这是带背景的smpl ![image](https://user-images.githubusercontent.com/82912827/137996778-ff50236f-1b01-45fa-af96-2b8a0c2cf620.png)
> > 我试着调了extract_video.py里的--low和 mv1p.py 里--thres2d这两个参数，但是都不太行。。。 请问有什么可以提升的办法吗
> 
> 你好，请问用自己数据集时，extri.yml中的R和T是世界坐标系到相机坐标系的旋转和平移吗？

是的
