### ISSUE TITLE
Question about reconstruction on nonlinear video

### ISSUE THREAD

**Issue by neilgogogo** [zju3dv/EasyMocap#95]
Hi, thank you very much for your awesome work. I have a question about the project. I have a nonlinear video in which some sequences are deleted. But it seems that the reconstructed SMPL tries to be linear and shows some abnormal and inhuman twists during those deleted sequences. Is there a switch to turn of the automatic linear fitting? many thanks 👍🏾

**Comment by neilgogogo** [comment]
Sorry for the unclear expression, in the video, there are some broken frames that are deleted, meaning that some of the person’s movements are skipped. When fitting, will these deleted motions be automatically fitted?

**Comment by chingswy** [comment]
You'd better make sure that your videos have no broken frames.

**Comment by neilgogogo** [comment]
thank you very much for your advice
