### ISSUE TITLE
请问什么时候能支持除了openpose之外的关键点检测？

### ISSUE THREAD

**Issue by puppet101** [zju3dv/EasyMocap#98]
你好，我想使用introduction里面提到的hrnet进行关键点检测，但是from easymocap.estimator import Detector 目前导入失败，没有Detector的相关定义，请问什么时候可以支持呢？ 谢谢！

**Comment by chingswy** [comment]
HRNet和YOLO可能会有一些代码版权的风险，我近期会支持mediapipe的关键点检测。

**Comment by puppet101** [comment]
期待，感谢解答~
