### ISSUE TITLE
几段代码的问题

### ISSUE THREAD

**Issue by baojunshan** [zju3dv/EasyMocap#99]
非常感谢作者的工作与代码，但我有几点疑惑如下：

1. 这里的距离是不是要扣掉最后一个维度（置信度）
https://github.com/zju3dv/EasyMocap/blob/e7bcf6b3ed4881c8736201873e7ec1e1984d90a6/easymocap/assignment/criterion.py#L49

2. 这里一段我理解的是匹配到的所有组合，但这里当match有多个的时候，会把第一个去掉，后面的做组合，请问这样的原因是什么？
https://github.com/zju3dv/EasyMocap/blob/e7bcf6b3ed4881c8736201873e7ec1e1984d90a6/easymocap/assignment/associate.py#L55
```python
if len(match) > 0:
  match = match + dimGroups[nv]
  for proposal in proposals:
      proposal[nv] = match[0]
if len(match) > 1:
    proposals_new = []
    for proposal in proposals:
        for col in match[1:]:
            p = proposal.copy()
            p[nv] = col
            proposals_new.append(p)
    proposals = proposals_new
```

感觉应该把
https://github.com/zju3dv/EasyMocap/blob/e7bcf6b3ed4881c8736201873e7ec1e1984d90a6/easymocap/assignment/associate.py#L62
改成
```python
 for col in match
```

3. 少了一个list
https://github.com/zju3dv/EasyMocap/blob/e7bcf6b3ed4881c8736201873e7ec1e1984d90a6/easymocap/assignment/associate.py#L21

**Comment by chingswy** [comment]
感谢细心的阅读
1. 这是一个bug，但是由于一般两个相邻的关节点置信度都差不多，所以最后一维表示的置信度的差值一般比较小，所以之前就没有看出来这个问题。
2. 这部分我有点忘记了，我有空了会检查一下
